### ISSUE TITLE
Unrecognized feature: 'picture-in-picture'

### ISSUE THREAD

**Issue by kyawsithu** [sarbagyastha/youtube_player_flutter#100]
I tried very recent version cloned from GitHub ended up with following error:

W/VideoCapabilities( 3623): Unsupported mime video/divx
W/VideoCapabilities( 3623): Unsupported mime video/divx311
W/VideoCapabilities( 3623): Unsupported mime video/divx4
W/VideoCapabilities( 3623): Unrecognized profile 4 for video/hevc
W/VideoCapabilities( 3623): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 3623): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities( 3623): Unsupported profile 4 for video/mp4v-es
W/Utils   ( 3623): could not parse long range '175-174'
D/NetworkSecurityConfig( 3623): No Network Security Config specified, using platform default
I/chromium( 3623): [INFO:CONSOLE(108)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vfloS5Wsk/www-widgetapi.js (108)
I/flutter_exampl( 3623): ProcessProfilingInfo new_methods=501 is saved saved_to_disk=1 resolve_classes_delay=8000
W/ContentCatcher( 3623): Failed to notify a WebView
W/System  ( 3623): A resource failed to call release.

thanks

**Comment by sarbagyastha** [comment]
It's only warning logs, so shouldn't matter.

**Comment by kyawsithu** [comment]
In fact, I found the issue. For some reason, like Myanmar country, due to many concurrent users from same IP, Youtube blocked the video playing with the Robot check captcha. Then this error occurred and video stopped with the Error Code: 150.

**Comment by cmcoffee91** [comment]
These errors crash the app in android p

**Comment by thinhlh** [comment]
In my case, while playing around, setting `javascriptMode: JavascriptMode.unrestricted,` that solved the issue
