### ISSUE TITLE
forceHideAnnotation doesn't work for iOS

### ISSUE THREAD

**Issue by ferysyukur** [sarbagyastha/youtube_player_flutter#101]
Hi, When i play youtube video in ios and pause the video youtube title and youtube watermark still show. What i do to hide title and youtube watermark ? Btw forceHideAnnotation is true, so in Android the title and watermark is hide but not in ios.

**Comment by sarbagyastha** [comment]
Currently there's no way to hide watermark in iOS. Will update if figure out way to hide it.

**Comment by sarbagyastha** [comment]
This flag was removed.

**Comment by jaskiratAtNexG** [comment]
@sarbagyastha the issue is still not resolved but you have closed it
