### ISSUE TITLE
[FEATURE REQUEST] webview_flutter 4.10.0 Support

### ISSUE THREAD

**Issue by Kuhlemann** [sarbagyastha/youtube_player_flutter#1017]
**Is your feature request related to a problem? Please describe.**
Dependencies for other packages are not fulfilled, for example web 1.1.0 and webview_flutter 4.10.0 can't be used because of dependency constraints.

**Describe the solution you'd like**
Support up-to-date dependencies for webview_flutter (4.10.0).

**Comment by StefanTasevski** [comment]
@sarbagyastha is it possible to have this?

**Comment by DavidOrakpo** [comment]
Very important to have

**Comment by Kuhlemann** [comment]
Thanks for bumping the dependencies to latest versions in today's update 5.2.1.
