### ISSUE TITLE
[BUG] Youtube Videos Not playing on iOS

### ISSUE THREAD

**Issue by RohithKilaparthi** [sarbagyastha/youtube_player_flutter#102]
**Describe the bug**
The videos get played remarkably well on Android, but on iOS, it doesn't play saying 
```
[VERBOSE-2:platform_view_layer.cc(22)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(38)] Trying to embed a platform view but the PaintContext does not support embedding.
```
In the plist file, I have enabled embedded views. But still facing the same issue. 
``` 
        <key>io.flutter.embedded_views_preview</key>
	<true/>
```

**Technical Details:**
 I am running the code on an emulator(iphone x).

**Comment by sarbagyastha** [comment]
Did you perform full rebuild after updating info.plist ?

**Comment by RohithKilaparthi** [comment]
Yes, but that did not help.

**Comment by sarbagyastha** [comment]
Does the issue exist with example app ?

**Comment by sarbagyastha** [comment]
Reopen if the issue persists.
