### ISSUE TITLE
Detect when user plays video

### ISSUE THREAD

**Issue by jamesncl** [sarbagyastha/youtube_player_flutter#103]
I can't figure out how to detect when a user plays a video, without having to rewrite all the player controls. I want to do this to collect telemetry on what the user is doing. Here's what I've tried:

1. Wrapping in a GestureDetector:

```
GestureDetector(
    onTapDown: (TapDownDetails d) {
        print("TAP");
    },
    child: YoutubePlayer(
        context: context,
        initialVideoId: "videoId",
        flags: YoutubePlayerFlags(
            autoPlay: false,
            showVideoProgressIndicator: true,
        ),
    ),
)
```

The detector does not detect user taps (I think this is because the youtube player wins the gesture arena?)

2. Adding a listener to YoutubePlayerController:

```
YoutubePlayer(
    context: context,
    "videoId",
    flags: YoutubePlayerFlags(
        autoPlay: false,
        showVideoProgressIndicator: true,
    ),
    onPlayerInitialized: (YoutubePlayerController controller) {
        controller.addListener(() {
            print("TAP");
        });
    },
)
```

Unofrtunately the listener is called multiple times when the player loads, before it is played, and I can't see any way to detect what event has triggered the listener, or query the controlelr for the play state (e.g. controller.isPlaying)

Am I missing something? Can you think of a way to accomplish this? I'm aware that I could use hideControls property to hide the default controls and implement my own set of controls on top of the player, but I'd rather not rewrite the play button, fullscreen button, duration etc. just to detect plays. If not, could you consider adding either a property to the controller which tells us the playing state (playing, paused, stopped) or add an argument to the listener callback which will tell us what event has triggered it?

Many thanks!

**Comment by sarbagyastha** [comment]
```dart
controller.addListener(( ){
     if(controller.value.playerState == PlayerState.playing){
          print('playing');
     }
});
```

You can listen for events like this.

**Comment by jamesncl** [comment]
Fantastic, thanks I had missed that. I just tried, it works. Please close the issue.
PS awesome plugin :)
