### ISSUE TITLE
[BUG] Video player not working with an mobite network connection, i.e, LTE network.

### ISSUE THREAD

**Issue by Jonan2813** [sarbagyastha/youtube_player_flutter#104]
**Describe the bug**
Video is not playing while using mobile network connection. (LTE) Youtube player shows Unknown Error, Error Code: 150.

**To Reproduce**
Open your video player using any mobile connection. Tested with diferent videos and devices and using the example program.

**Expected behavior**
Youtube player working like iWifi network.

**Technical Details:**
 - Device: Samsung A50
 - OS: Android 9

Also tested in several android devices and different Android versions.

**Comment by sarbagyastha** [comment]
Tested with mobile network and it's working fine.  It might be an issue with your mobile network. You can try using a vpn, and see if the issue persist.

**Comment by Jonan2813** [comment]
Doesn't work if the video hasn't started. If I start the video using WiFi and then changes to Mobile Network, it works.

**Comment by sarbagyastha** [comment]
I tested with three different devices and video starts well with mobile network.
