### ISSUE TITLE
[BUG] Since 5.x it wont go into fullscreen mode

### ISSUE THREAD

**Issue by jonatadashi** [sarbagyastha/youtube_player_flutter#105]
**Describe the bug**
Since 5.x it wont go into fullscreen mode

**To Reproduce**
<pre>
import 'package:flutter/material.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Container(
          child: new Column(
        children: <Widget>[
          Expanded(
            child: new CustomScrollView(
              scrollDirection: Axis.vertical,
              shrinkWrap: false,
              slivers: <Widget>[
                SliverAppBar(
                  backgroundColor: Colors.black,
                  expandedHeight: 200.0,
                  flexibleSpace: FlexibleSpaceBar(
                    collapseMode: CollapseMode.pin,
                    centerTitle: true,
                    background: new YoutubePlayer(
                      context: context,
                      initialVideoId: "H0WqgF9RF0k",
                      flags: YoutubePlayerFlags(
                        autoPlay: false,
                        showVideoProgressIndicator: true,
                        forceHideAnnotation: true,
                      ),
                    ),
                  ),
                ),
                SliverToBoxAdapter(
                    child: Column(children: <Widget>[
                  new YoutubePlayer(
                    context: context,
                    initialVideoId: "H0WqgF9RF0k",
                    flags: YoutubePlayerFlags(
                      autoPlay: false,
                      showVideoProgressIndicator: true,
                      forceHideAnnotation: true,
                    ),
                  ),
                ])),
              ],
            ),
          ),
        ],
      )),
    );
  }
}
</pre>

**Comment by mrifni** [comment]
Can you add some unit tests/automated tests before any release for this plugin please.

**Comment by sarbagyastha** [comment]
Should fix with [Version 6.0.0](https://pub.dev/packages/youtube_player_flutter#600).

**Comment by sarbagyastha** [comment]
@mrifni Will be writing tests soon. Thank you for your suggestions.
