### ISSUE TITLE
"Error Code: 150" for some of the video[BUG]

### ISSUE THREAD

**Issue by tagerjump** [sarbagyastha/youtube_player_flutter#106]
Error Code 150 when try to play some videos. This might imply something wrong with the blacklist.

**To Reproduce**
play the video, id "Soa3gO7tL" in the example

**Screenshots**

![Screenshot_1572119661](https://user-images.githubusercontent.com/45743053/67625201-f2e48480-f808-11e9-855d-989fecfe95cf.png)

**Technical Details:**
No such error for the version 1.2.0
I got this error when I try to upgrade to 5.2.0

**Comment by sarbagyastha** [comment]
The video id you provided is invalid. Youtube Video Ids are exactly 11 characters.

**Comment by dmomotic** [comment]
I have same issue, i can't reproduce any video, always show that error.

**Comment by mrifni** [comment]
This also happens if there is a copyright issue with the video, like country

**Comment by tagerjump** [comment]
> This also happens if there is a copyright issue with the video, like country

However, old version of this package works well.

**Comment by sarbagyastha** [comment]
@tagerjump Is the youtube link below, with the id you provided working for you ?
https://www.youtube.com/watch?v=Soa3gO7tL

**Comment by tagerjump** [comment]
try "NUTGr5t3MoY". Not working.

**Comment by sarbagyastha** [comment]
#119
