### ISSUE TITLE
[Conflict with WebViewFlutterPlugin]

### ISSUE THREAD

**Issue by nivla360** [sarbagyastha/youtube_player_flutter#107]
After adding the library and I click on run I get this error:
`C:\Users\...\FlutterProjects\MyFlutterApp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:42: error: a type with the same simple name is already defined by the single-type-import of WebViewFlutterPlugin
import np.com.sarbagyastha.ytview.WebViewFlutterPlugin;
`

**Comment by sarbagyastha** [comment]
Upgrade to 5.1.0 or up in order to resolve the issue.
