### ISSUE TITLE
Discussion: why the "videoId" is inside the controller?

### ISSUE THREAD

**Issue by Xoshbin** [sarbagyastha/youtube_player_flutter#110]
Hi @sarbagyastha . Yesterday I did try to use the version 6.0 but I saw that you have passed the "videoId" to the controller which I think it's not a good experience especially in my situation which I think most fo the people would say that too. in my scenario my "videoId"s are inside my list index as I'm using the listview.builder and grabbing the data from an API. so it's almost impossible to map the "videoId"s outside the listview into the controller. I'm sure you  made this change for improvements but I think it's better to have the "videoId" inside the "youtubeplayer".
Thank you for this great library again.

**Comment by sarbagyastha** [comment]
@Xoshbin Moved `videoId` to the controller in order to maintain consistency (as i'll add support for flutter web soon) and to match the behavior of YouTube IFrame Player API. 

As per your issue with video lists, [the solution is here](https://github.com/sarbagyastha/youtube_player_flutter/blob/master/example/lib/video_list.dart).

**Comment by Xoshbin** [comment]
@sarbagyastha I know I did check that too. but in my situation the video id's are inside the "listview.builder"s index so it's almost impossible to map it to the controller especially when the controller is outside the listview. I'm not sure if you understand what I say.

**Comment by sarbagyastha** [comment]
```dart
ListView.separated(
        itemBuilder: (context, index) {
          return YoutubePlayer(
            controller: YoutubePlayerController(initialVideoId: data[index]),
            actionsPadding: EdgeInsets.only(left: 16.0),
            bottomActions: [
              CurrentPosition(),
              SizedBox(width: 10.0),
              ProgressBar(isExpanded: true),
              SizedBox(width: 10.0),
              RemainingDuration(),
              FullScreenButton(),
            ],
          );
        },
        itemCount: data.length,
        separatorBuilder: (context, _) => SizedBox(height: 10.0),
      ),
    );
```

You can do like this, if you aren't using controller elsewhere.

**Comment by Xoshbin** [comment]
@sarbagyastha Thanks it did work that way :)
