### ISSUE TITLE
[FEATURE REQUEST] Playing video without fullscreen on iOS

### ISSUE THREAD

**Issue by louisdeb** [sarbagyastha/youtube_player_flutter#111]
When I play the video, the player automatically goes into fullscreen. 

Is there a way of playing the video without fullscreen being forced?

If not, it would be a nice to have a flag to control this.

**Comment by Y-ndm** [comment]
Same issue here. And even when I get out of fullscreen mode the video pauses and if I resume it goes back to fullscreen mode again. Before I didn't do it like this.

**Comment by sarbagyastha** [comment]
is this behaviour on Android or iOS?

**Comment by Y-ndm** [comment]
> is this behaviour on Android or iOS?

iOS

**Comment by sarbagyastha** [comment]
@Y-ndm Will update with a fix soon.

**Comment by Y-ndm** [comment]
Thank you so much for all of the amazing work you're doing.

**Comment by louisdeb** [comment]
Thanks a lot

**Comment by zcr1** [comment]
This is due to a bug in `webview_flutter`. There's currently two open prs to fix it. I pulled down a copy of the plugin locally and added the 1 line change in https://github.com/flutter/plugins/pull/2309 and it worked for me.

**Comment by alexmarkley** [comment]
@zcr1 thanks for drawing some attention to my PR. Would you mind adding a 👍 to give it a little extra visibility? I am sure we would all like to get this issue resolved upstream ASAP.

Also, as a point of clarification for everybody, this behavior is isolated to iPhones due to the way Apple treats the smaller screen. iPads have a different default behavior. 🤷‍♂

**Comment by sarbagyastha** [comment]
@zcr1 I too have a PR for it flutter/plugins#2227 , opened almost a month ago. But got no response from the team.

**Comment by sarbagyastha** [comment]
@alexmarkley the flag shouldn't be always tru as in your PR, inline playback is not favored in ios ecosystem, so it should be optional.

**Comment by zeh-gil** [comment]
Hello, how's PR.
I have the same problem on IOS...

**Comment by victormanuelfrancodev** [comment]
I repair with the @alexmarkley PR . Thank you! 
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/27299953/71457998-0d74b300-27e4-11ea-9ae4-8fa1801b2504.png">

**Comment by sarbagyastha** [comment]
Sorry for the late response, was on a tight schedule. Will be working on the issue within this week.

**Comment by geekydiamond** [comment]
I feel really bad pestering because you created a great plugin, but the fullscreen issue is a blocker to us going live and we have a major conference we are demoing at in 2 weeks :s 
Any guidance on timelines and whether we should look at other options would be very helpful.

**Comment by sarbagyastha** [comment]
@geekydiamond currently there's [some issue with webview_flutter](https://github.com/flutter/flutter/issues/45695), so will work on this as soon as it gets solved.

**Comment by AGKireev** [comment]
Hey. Is there any information on this fix (preventing iOS go fullscreen when the playback starts)? Thanks!

**Comment by sarbagyastha** [comment]
Version 6.1.0 should fix the issue.
