### ISSUE TITLE
[Question] about loading next video

### ISSUE THREAD

**Issue by frgmt** [sarbagyastha/youtube_player_flutter#112]
@sarbagyastha Hi. Thank you for your great library!
Is this player available to load next video like below when current video reached the end?

```
if (_controller.value.playerState == PlayerState.ended) {
    _controller.videoId = '$id';
    _controller.play();
}
```

**Comment by sarbagyastha** [comment]
@frgmt use `load` or `cue` to load next video.
```dart
if (_controller.value.playerState == PlayerState.ended) {
    _controller.load(id);
}

```

**Comment by frgmt** [comment]
@sarbagyastha wow, nice! thanx

**Comment by amangautam1** [comment]
@sarbagyastha 
`if (_controller.value.playerState == PlayerState.ended) {
    _controller.load(id);
}`
`controller.value.playerState == PlayerState.ended` : It never becomes true, only PlayerState.stopped is called when video ends.

**Comment by sarbagyastha** [comment]
@amangautam1 `PlayerState.end` is being called as intended. Is the issue present in example app too ?
