### ISSUE TITLE
[FEATURE REQUEST] Show controls when opening the player

### ISSUE THREAD

**Issue by luuklelifeld** [sarbagyastha/youtube_player_flutter#113]
As the title says, I'd like to be able to show the player controls (pause/play button fullscreen button etc.) when the video starts instead of having them hidden when the video starts. This would make it clearer (in my situation at least) to my app users that the video has controls.

If there is a way to implement this at the moment, please let me know. I've been trying for way too long and can't figure it out.

**Comment by sarbagyastha** [comment]
The current behaviour is borrowed from the YouTube app's player. I guess, users will surely know that the player contains controls, althought it is not visible at the start.

**Comment by luuklelifeld** [comment]
The problem in my situation is that the player is used as a type of overlay, and it's not clear that the player is able to be closed without tapping it first. I've had some feedback from my users that they don't find it clear that the player has control buttons because they're not shown when the player is openend.

**Comment by sarbagyastha** [comment]
@luuklelifeld in that case, you can create your own controls fair easily (as there are readily available widgets supplied with this package for building custom controls). The behavior in the player itself cannot be changed as other users might not appreciate it.

**Comment by luuklelifeld** [comment]
Oh yeah I wasn't thinking of changing the default behavior, but adding a flag that would enable this.

**Comment by sarbagyastha** [comment]
Added `controlsVisibleAtStart` flag in [**Version 6.0.2**](https://pub.dev/packages/youtube_player_flutter#602).
