### ISSUE TITLE
Errors during build on version 6.0.0 Flutter 1.10.15-pre.424 • channel master 

### ISSUE THREAD

**Issue by wiseminds** [sarbagyastha/youtube_player_flutter#114]
I just upgraded flutter and also updated youtube_player_flutter, i tried to run my project and build failed with the following message

Compiler message:
../../applications/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-6.0.0/lib/src/player/raw_youtube_player.dart:56:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:
                             ^^^^^^^^^^
Exception: Errors during snapshot creation: null

i edited line 56 to "case AppLifecycleState.detached:" and it seems to work fine now.

**Comment by sarbagyastha** [comment]
It's due to [this PR](https://github.com/flutter/engine/pull/11913).

**Comment by sarbagyastha** [comment]
[The PR was reverted](https://github.com/flutter/engine/pull/13720) and the latest master doesn't reproduce this issue.

**Comment by ber4444** [comment]
I just switched to the master channel and upgraded flutter. Still getting this issue.

**Comment by sarbagyastha** [comment]
@ber4444 which version of the plugin are you on ?
