### ISSUE TITLE
[BUG] Cannot Build app using Flutter Master Channel

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [sarbagyastha/youtube_player_flutter#116]
**Describe the bug**
The app will launch and immediately crash. This seems to be an issue with the few Flutter Plugin View or something. I linked to a similar issue with the camera.
**To Reproduce**
add this plugin to the pubspec.yaml while on master and try to run it

**Technical Details:**
- [✓] Flutter (Channel master, v1.10.17-pre.58, on Mac OS X 10.15.2 19C39d, locale en-US)

**Additional context**
see https://github.com/flutter/flutter/issues/40423

### Stacktrace
D/FlutterActivityAndFragmentDelegate( 3255): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 3255): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
W/FlutterEngine( 3255): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@aa7959b) but could not find and invoke the GeneratedPluginRegistrant.
D/FlutterActivityAndFragmentDelegate( 3255): Attaching FlutterEngine to the Activity that owns this Fragment.

**Comment by sarbagyastha** [comment]
@ThinkDigitalSoftware It's an issue due to v2 embedding of PlatformViews. The workaround is to migrate from GeneratedPluginRegistrant to adding the plugin to flutter-engine.

[As in the example](https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example/android/app/src/main/java/io/flutter/plugins/webviewflutterexample), use MainActivity.java instead of old one(i.e. v1).

**Comment by ThinkDigitalSoftware** [comment]
Oh, I didn't realize this wasn't a plugin error. OK, thank you!

**Comment by ThinkDigitalSoftware** [comment]
What am i supposed to be adding? 
with the code 
```java

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    flutterEngine.getPlugins().add(new WebViewFlutterPlugin());
  }
}
```
> error: no suitable method found for add(WebViewFlutterPlugin)
> method PluginRegistry.add(FlutterPlugin) is not applicable
> (argument mismatch; WebViewFlutterPlugin cannot be converted to FlutterPlugin)
>

**Comment by sarbagyastha** [comment]
@ThinkDigitalSoftware Just tested on `Flutter (Channel master, v1.11.1-pre.48)` and got no crashes without even performing the workarounds.

**Comment by ThinkDigitalSoftware** [comment]
Wow. I don't know what to say then. I'll debug some more and let you know
if I find something.  Thank you!

**Comment by ThinkDigitalSoftware** [comment]
I flutter deleted the android folder and recreated it with `flutter create` and switched to stable and it builds fine. I'll switch to master and try again later
