### ISSUE TITLE
Cannot run the example project on Android

### ISSUE THREAD

**Issue by michealchow2324** [sarbagyastha/youtube_player_flutter#12]
I downloaded and run the project on my android emulator. I could see the thumbnail of the youtube link showing on the YoutubePlayer, however, i could not play the video.

Here are the logs appears when I pressed the play button of the YoutubePlayer

> W/System.err( 4071): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: JavaBridge
W/System.err( 4071):    at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/System.err( 4071):    at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/System.err( 4071):    at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
W/System.err( 4071):    at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
W/System.err( 4071):    at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:152)
W/System.err( 4071):    at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:95)
W/System.err( 4071):    at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:82)
W/System.err( 4071):    at io.flutter.plugins.webviewflutter.JavaScriptChannel$1.run(JavaScriptChannel.java:49)
W/System.err( 4071):    at io.flutter.plugins.webviewflutter.JavaScriptChannel.postMessage(JavaScriptChannel.java:53)
W/System.err( 4071):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 4071):    at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err( 4071):    at android.os.Looper.loop(Looper.java:136)
W/System.err( 4071):    at android.os.HandlerThread.run(HandlerThread.java:61)
I/chromium( 4071): [INFO:CONSOLE(24)] "Uncaught Error: Java exception was raised during method invocation", source: https://sarbagyadhaubanjar.github.io/youtube_player/player.js (24)
W/System.err( 4071): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: JavaBridge
W/System.err( 4071):    at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/System.err( 4071):    at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/System.err( 4071):    at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
W/System.err( 4071):    at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
W/System.err( 4071):    at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:152)
W/System.err( 4071):    at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:95)
W/System.err( 4071):    at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:82)
W/System.err( 4071):    at io.flutter.plugins.webviewflutter.JavaScriptChannel$1.run(JavaScriptChannel.java:49)
W/System.err( 4071):    at io.flutter.plugins.webviewflutter.JavaScriptChannel.postMessage(JavaScriptChannel.java:53)
W/System.err( 4071):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 4071):    at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err( 4071):    at android.os.Looper.loop(Looper.java:136)
W/System.err( 4071):    at android.os.HandlerThread.run(HandlerThread.java:61)
I/chromium( 4071): [INFO:CONSOLE(31)] "Uncaught Error: Java exception was raised during method invocation", source: https://sarbagyadhaubanjar.github.io/youtube_player/player.js (31)
W/System.err( 4071): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: JavaBridge
W/System.err( 4071):    at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/System.err( 4071):    at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/System.err( 4071):    at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
W/System.err( 4071):    at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:163)
W/System.err( 4071):    at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:152)
W/System.err( 4071):    at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:95)
W/System.err( 4071):    at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:82)
W/System.err( 4071):    at io.flutter.plugins.webviewflutter.JavaScriptChannel$1.run(JavaScriptChannel.java:49)
W/System.err( 4071):    at io.flutter.plugins.webviewflutter.JavaScriptChannel.postMessage(JavaScriptChannel.java:53)
W/System.err( 4071):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 4071):    at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err( 4071):    at android.os.Looper.loop(Looper.java:136)
W/System.err( 4071):    at android.os.HandlerThread.run(HandlerThread.java:61)
I/chromium( 4071): [INFO:CONSOLE(24)] "Uncaught Error: Java exception was raised during method invocation", source: https://sarbagyadhaubanjar.github.io/youtube_player/player.js (24)
E/eglCodecCommon( 4071): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 4071): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 4071): glUtilsParamSize: unknow param 0x000085b5

Is there any initial setup that i have missed?

**Comment by sarbagyastha** [comment]
No initial setup needed. Please include `flutter doctor -v` log

**Comment by JamalBelilet** [comment]
Have the same problem after upgrading to v1.5

**Comment by sarbagyastha** [comment]
https://github.com/flutter/flutter/issues/32315 It seems to be an issue due to changes in 1.5.x . Found some posts which confirms that there is no such issue in `dev branch`, haven't test it though.

**Comment by sarbagyastha** [comment]
[Version 1.1.1](https://pub.dev/packages/youtube_player_flutter#111) addresses the issue.
