### ISSUE TITLE
[BUG] Get AndroidX incompatibility issue

### ISSUE THREAD

**Issue by bahadurvaibhav** [sarbagyastha/youtube_player_flutter#121]
**Describe the bug**
Get AndroidX incompatibility issue

**To Reproduce**
List of dependencies in pubspec.yaml
dependencies:
  http: ^0.12.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.7+1
  path_provider: ^0.4.1
  flutter_rating_bar: ^3.0.0
  intl: ^0.16.0
  csv: ^4.0.3
  simple_permissions: ^0.1.9
  transparent_image: ^1.0.0
  video_player: ^0.10.2+5

I just added youtube_player_flutter: ^6.0.3+2

When I run the app, it gives this
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\76.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\61.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\66.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\86.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\56.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\71.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\51.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\81.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\1.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\2.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\3.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\0.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Apps\practice\build\app\intermediates\transforms\dexBuilder\debug\25.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Technical Details:**
 - Device: Emulator Nexus 6 API 28
 - OS: Android
 - Version: 9

**Comment by sarbagyastha** [comment]
@bahadurvaibhav  It might be an issue due to `simple_permissions` dependency.It's not AndroidX compatible i guess. Try once by removing it.

**Comment by bahadurvaibhav** [comment]
Run works if I remove simple_permissions.

Do you know any other flutter library to ask for user permissions to write to external storage (Android)?

**Comment by sarbagyastha** [comment]
Try [Permission Handler](https://pub.dev/packages/permission_handler).

**Comment by bahadurvaibhav** [comment]
cool. that works. thanks :)
