### ISSUE TITLE
I want to initialize controller with dynamic value

### ISSUE THREAD

**Issue by bahadurvaibhav** [sarbagyastha/youtube_player_flutter#123]
**Describe the issue**
**Issue 1**
On Android Emulator I am not able to see video. I can hear audio only. (Based on example given on https://pub.dev/packages/youtube_player_flutter#-readme-tab-)
Emulator Nexus 6 API 28
I can see video in actual Android device (Samsung S8)

**Issue 2**
I will mention 2 programs below. That will help to explain the issue.

**Program 1**
initState() {
    _youtubePlayerController = YoutubePlayerController(
      initialVideoId: 'vnwdTu6owHo',
      flags: YoutubePlayerFlags(
        mute: false,
        autoPlay: true,
        forceHideAnnotation: true,
      ),
    );
    super.initState();
}

build() {
    String videoId = YoutubePlayer.convertUrlToId(videoUrl);
    _youtubePlayerController.load(videoId);
    return YoutubePlayer(
      controller: _youtubePlayerController,
      showVideoProgressIndicator: true,
      progressIndicatorColor: Colors.blueAccent,
      onReady: () {
        print('is ready');
      },
      topActions: <Widget>[
        SizedBox(width: 8.0),
        Expanded(
          child: Text(
            _youtubePlayerController.metadata.title,
            style: TextStyle(
              color: Colors.white,
              fontSize: 18.0,
            ),
            overflow: TextOverflow.ellipsis,
            maxLines: 1,
          ),
        ),
      ],
      bottomActions: [
        CurrentPosition(),
        SizedBox(width: 10.0),
        ProgressBar(isExpanded: true),
        SizedBox(width: 10.0),
        RemainingDuration(),
        FullScreenButton(),
      ],
    );
}

**Program 2**
initState() {
    super.initState();
}

build() {
    String videoId = YoutubePlayer.convertUrlToId(videoUrl);    
    _youtubePlayerController = YoutubePlayerController(
      initialVideoId: videoId,
      flags: YoutubePlayerFlags(
        mute: false,
        autoPlay: true,
        forceHideAnnotation: true,
      ),
    );
    return YoutubePlayer(
      controller: _youtubePlayerController,
      showVideoProgressIndicator: true,
      progressIndicatorColor: Colors.blueAccent,
      onReady: () {
        print('is ready');
      },
      topActions: <Widget>[
        SizedBox(width: 8.0),
        Expanded(
          child: Text(
            _youtubePlayerController.metadata.title,
            style: TextStyle(
              color: Colors.white,
              fontSize: 18.0,
            ),
            overflow: TextOverflow.ellipsis,
            maxLines: 1,
          ),
        ),
      ],
      bottomActions: [
        CurrentPosition(),
        SizedBox(width: 10.0),
        ProgressBar(isExpanded: true),
        SizedBox(width: 10.0),
        RemainingDuration(),
        FullScreenButton(),
      ],
    );
}

Program #1 works on phone

Program #2 only shows cover photo. I can hear audio. But no video movement. Can click play button and click pause button. Can play audio and pause video. Bottom actions ProgressBar, RemainingDuration, FullScreenButton also won't show. 

**What I am looking for**
User enters URL in text field and then I want to show youtube video based on entered URL.
Please recommend how I should initialize and how I should load URL into controller.

**Comment by sarbagyastha** [comment]
Donot load video or initialize controllers inside build methods. Refer to example app.

**Comment by yeahse** [comment]
> Donot load video or initialize controllers inside build methods. Refer to example app.

if you initilize controllers inside initState then how do you change the intialVideoId ? I mean I get the url from database and so use futureBuilder for it. but when I try to change the initialVideoId using setState() after I got the url data from database, it give me errors like "you are not able to change initialVideoId while it is building"

**Comment by suthishan** [comment]
> Donot load video or initialize controllers inside build methods. Refer to example app.

where is the example app

**Comment by MakamuEvans** [comment]
Was this ever solved?

**Comment by suthishan** [comment]
> Was this ever solved?

Yes

**Comment by praveenb** [comment]
Hi @suthishan, how its solved. Pls let us know.
