### ISSUE TITLE
initialVideoId value

### ISSUE THREAD

**Issue by SayaGames** [sarbagyastha/youtube_player_flutter#124]
@sarbagyastha Thank you very much for dense effort. 

I have an issue or a question about initialVideoId value. I have a video list. First moment entering the page, when I click a video(from my list), initialVideo is trying to play. 

If I click again, my video (from my list) is playing... I don't intend to play initial video?

How to

Best regards

**Comment by sarbagyastha** [comment]
@SayaGames couldn't get you. Could you please explain with examples.

**Comment by SayaGames** [comment]
In the videosScreen.dart: (page newly loaded)
I have a ListView contains videos. 
In the ListTile **onTap** event I call below:

          _controller.load(YoutubePlayer.convertUrlToId(**videoUrl1**),startAt: 0);
          if (_isPlayerReady) {
            _controller.play();
          }
The first time onTap clicked, initialVideo is shown (I expect **videoUrl1** displayed).  afterwards clicks to list of the videos display proper video in the listView

**Comment by sarbagyastha** [comment]
@SayaGames Have you checked the [example app](https://github.com/sarbagyastha/youtube_player_flutter/blob/master/example/lib/video_list.dart) ?

**Comment by SayaGames** [comment]
Yes I checked the example. 

My case is a bit different: 

I set the initialVideoID. After the later process, I want to display videos. 

my code:

YoutubePlayerController _controller;

void initState() {
    _controller = YoutubePlayerController(
      initialVideoId: 'P7_xSbY-lDs', 
      flags: YoutubePlayerFlags(
        mute: false,
        autoPlay: true,
        disableDragSeek: false,
        loop: false,
        isLive: false,
        forceHideAnnotation: true,
        hideControls: false
      ),
    )..addListener(listener);
    _videoMetaData = YoutubeMetaData();
    _playerState = PlayerState.unknown;
 }
  void listener() {
    if (_isPlayerReady && mounted && !_controller.value.isFullScreen) {
      setState(() {
        _playerState = _controller.value.playerState;
        _videoMetaData = _controller.metadata;
      });
    }
  }

**Comment by sarbagyastha** [comment]
@SayaGames A sample app would be helpful.

**Comment by SayaGames** [comment]
I created list of YoutubePlayerController  up to number of my videos. 
List<YoutubePlayerController> _controllers = [];

categoryURLSByCategory.forEach((f){
        _controllers.add(YoutubePlayerController(
        initialVideoId: f,
          flags: YoutubePlayerFlags(
              mute: false,
              autoPlay: true,
              disableDragSeek: false,
              loop: false,
              isLive: false,
              forceHideAnnotation: true,
              hideControls: false
          ),
        )..addListener(listener));
      });

Because of I have One player:

YoutubePlayer(
              key: ObjectKey(_controllers[cIndex]),
              controller: _controllers[cIndex],
              showVideoProgressIndicator: true,
              progressIndicatorColor: Colors.red,
              topActions: <Widget>[
                Expanded(
                  child: Text(
                    _controllers[cIndex].metadata.title,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 18.0,
                    ),
                    overflow: TextOverflow.ellipsis,
                    maxLines: 1,
                  ),
                ),
              ],

              onReady: () {
                _isPlayerReady = true;
              },
              onEnded: (id) {


        });
                _controllers[cIndex].load(YoutubePlayer.convertUrlToId(globals.url));
                if (_isPlayerReady) {
                  _controllers[cIndex].play();
                }
              },
            ), 

So my issue is resolved. Thank you very much.

**Comment by sarbagyastha** [comment]
Great!
