### ISSUE TITLE
Question: onReady()

### ISSUE THREAD

**Issue by SayaGames** [sarbagyastha/youtube_player_flutter#126]
Hi, 

When the YoutubePlayer() is ready and when not? 

Because some cases,  although all the things is ok (controller is fine, controller.load method was called) _isPlayerReady variable is false... 

so .play() method not playing the video.

onReady: () {
                        _isPlayerReady = true;
                      },

**Comment by sarbagyastha** [comment]
@SayaGames `onReady` is called once the webview completely loads the iframe player.
