### ISSUE TITLE
deactivate() method gives error

### ISSUE THREAD

**Issue by SayaGames** [sarbagyastha/youtube_player_flutter#127]
When I navigating page contains video player to another page, it gives error at _controller.pause(); line.

void deactivate() {
_controller.pause();
super.deactivate();
  }

Event log below:
------------------------------------------
W/ScreenOrientationListener(17293): Removing an inexistent observer!
W/chromium(17293): [WARNING:aw_contents.cc(315)] SP>>> Destroy
I/chromium(17293): [INFO:synchronous_compositor_impl.cc(111)] [SynchronousCompositorImpl::SetClient] [0x0000007f359b5ec0]
I/MediaCodec(17293): [release]line:383 [OMX.google.opus.decoder]+++
I/ACodec  (17293): freeBuffersOnPort portIndex 0
I/ACodec  (17293): freeBuffersOnPort portIndex 1
I/MediaCodec(17293): [onMessageReceived]line:1268 [OMX.google.opus.decoder][what=kWhatShutdownCompleted][state 10][msg='AMessage(what = 'codc', target = 2) = {
I/MediaCodec(17293):   int32_t what = 1935896429
I/MediaCodec(17293): }' ]
I/MediaCodec(17293): [~MediaCodec]line:205 [][mState 0]+++
I/MediaCodec(17293): [release]line:383 [OMX.MTK.VIDEO.DECODER.VP9]+++
I/ACodec  (17293): freeBuffersOnPort portIndex 0
I/ACodec  (17293): freeBuffersOnPort portIndex 1
I/MediaCodec(17293): [onMessageReceived]line:1268 [OMX.MTK.VIDEO.DECODER.VP9][what=kWhatShutdownCompleted][state 10][msg='AMessage(what = 'codc', target = 5) = {
I/MediaCodec(17293):   int32_t what = 1935896429
I/MediaCodec(17293): }' ]
I/MediaCodec(17293): [~MediaCodec]line:205 [][mState 0]+++
E/flutter (17293): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel plugins.flutter.io/webview_0)
E/flutter (17293): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (17293): <asynchronous suspension>
E/flutter (17293): #1      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
E/flutter (17293): #2      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:626:39)
E/flutter (17293): #3      YoutubePlayerController._callMethod (package:youtube_player_flutter/src/utils/youtube_player_controller.dart:180:32)
E/flutter (17293): #4      YoutubePlayerController.pause (package:youtube_player_flutter/src/utils/youtube_player_controller.dart:194:19)
E/flutter (17293): #5      _VideosScreenState.deactivate (package:youvilist/videosScreen.dart:133:34)
E/flutter (17293): #6      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:4135:12)
E/flutter (17293): #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1756:13)
E/flutter (17293): #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5115:14)
E/flutter (17293): #9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
E/flutter (17293): #11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #12     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5115:14)
E/flutter (17293): #13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #14     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5115:14)
E/flutter (17293): #15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5115:14)
E/flutter (17293): #17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5115:14)
E/flutter (17293): #19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
E/flutter (17293): #21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
E/flutter (17293): #23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
E/flutter (17293): #25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5115:14)
E/flutter (17293): #27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
E/flutter (17293): #29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5115:14)
E/flutter (17293): #31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
E/flutter (17293): #33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
E/flutter (17293): #35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5115:14)
E/flutter (17293): #37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1758:13)
E/flutter (17293): #38 
W/chromium(17293): [WARNING:aw_network_delegate.cc(86)] https://r1---sn-nx5cvox-5uie.googlevideo.com/videoplayback?expire=1574443433&ei=ScXXXdWBL-TyxgKpl6m4Cw&ip=193.140.87.3&id=o-AF9ENbMJOc9OV4_Vekvta7EBAEi0vBUovMb0P1U1ZsBL&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-nx5cvox-5uie%2Csn-nv47lnsy&ms=au%2Crdu&mv=m&mvi=0&pl=22&initcwndbps=652500&mime=video%2Fwebm&gir=yes&clen=167339651&dur=1537.920&lmt=1570277496757063&mt=1574421761&fvip=1&keepalive=yes&fexp=23842630&c=WEB_EMBEDDED_PLAYER&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhAOsRGl_ihaPDxnSFt_2PeeuiQ9wAOw7qpXSrZLniIAn2AiEAgvZLPGOc2uPcqQtKuCuknRk6spcWaQ1Ops0Ff7ucV-Y%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgVci2Rv--Q2ngHQ_cosnpEL1lYD13oiqr71DdTHXOYMACIQDYW1uinNm8Mk6Esy8uLh2UObVCy7Eiw8HQGHgbhrtBNg%3D%3D&alr=yes&cpn=PjP8wnSh2Ki85Zot&cver=20191121&range=4746501-6314657&rn=9&rbuf=27201#-3#1
E/chromium(17293): [ERROR:deferred_gpu_command_service.cc(76)] No hardware renderer. Deadlock likely

**Comment by nikeshjobanputra** [comment]
I'm having a similar problem as well! Upon going to the `deactivate` method it calls `controller.pause();` but throws 
`Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel plugins.flutter.io/webview_0)`

Anyone have any idea on how to fix? Slightly confusing as implementation for the pause method exists so not sure how/why this is occuring?

**Comment by Codiyampa** [comment]
I am also facing this issue.

Did you already find a solution? @nikeshjobanputra

**Comment by sarbagyastha** [comment]
A reproducible example is required. Feel free to reopen.
