### ISSUE TITLE
glUtilsParamSize : unknow param

### ISSUE THREAD

**Issue by shipmant** [sarbagyastha/youtube_player_flutter#128]
Hello everyone, I contact you because I encounter an error that continuously sends the same message, I use the package youtube_player_flutter with version 6.0.3+2 and I have this error, it never stops, I have already done some research and I do not find, if someone has already had and solved the problem, I am taker thanks

![Capture d’écran du 2019-11-28 11-14-26](https://user-images.githubusercontent.com/43004430/69797612-47946a00-11d0-11ea-9269-7ec283f1cd00.png)

**Comment by despie** [comment]
This still happens on Android API level 26. 
Doesn't occur on Android API level 29. 
Haven't tested 27 & 28 jet...
