### ISSUE TITLE
Fullscreen play on mobile

### ISSUE THREAD

**Issue by komaromil** [sarbagyastha/youtube_player_flutter#130]
It is a fantastic plugin but I would like to use playback fullscreen on mobile and because the app is oriented  portraitUp I have to change the direction when  playing video. I could not solve it because it turns back and forth before playing in full screen. Plus there is an extra place under video so I can scroll if showVideoProgressIndicator: false and use my bottomactions and I add padding only bottom to see it.
So I want to remove the bottom extra place and would like to play on mobile left or right fullscreen if the main app is portraitUp.
Any good solution?
Thank you. 
Here is my code:

<pre><code>import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:uhu/main.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:uhu/common/widgets/base_stateless_widget.dart';

class YoutubeWidget extends StatefulWidget {
  @override
  _YoutubeWidgetState createState() => new _YoutubeWidgetState();
}

class _YoutubeWidgetState extends State<YoutubeWidget> {

  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey();
  YoutubePlayerController _controller;

  String _playerStatus = '';

  bool _isPlayerReady = false;
  PlayerState _playerState;
  YoutubeMetaData _videoMetaData;

  String _videoId = CommonThings.videoId;

  @override
  void initState() {
    super.initState();
    _controller = YoutubePlayerController(
      initialVideoId: 'KkxRiXVrkB8',
      flags: YoutubePlayerFlags(
        mute: false,
        autoPlay: true,
        forceHideAnnotation: true,
        disableDragSeek: true,
        loop: false,
        hideControls: false,
        controlsVisibleAtStart: false,
        hideThumbnail: false,
        enableCaption: true,
        captionLanguage: (MainDatas.currentLanguage == 'hu') ? 'hu' : 'en',
      ),
    )..addListener(listener);
    _playerState = PlayerState.unknown;
    _videoMetaData = YoutubeMetaData();
  }

  void listener() {
    if (_isPlayerReady && mounted && !_controller.value.isFullScreen) {
      setState(() {
        _playerState = _controller.value.playerState;
        _videoMetaData = _controller.metadata;
      });
    }
    if (_isPlayerReady) {
      if (_controller.value.playerState == PlayerState.ended) {
        Navigator.pop(context);
        SystemChrome.setPreferredOrientations([
          DeviceOrientation.portraitUp,
        ]);
      }
    }
  }

  @override
  void deactivate() {
    _controller.pause();
    super.deactivate();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    _controller.fitHeight(MediaQuery.of(context).size);
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
//         DeviceOrientation.portraitUp,
      DeviceOrientation.landscapeRight
    ]);
    return WillPopScope(
        onWillPop: () async {
          SystemChrome.setPreferredOrientations([
            DeviceOrientation.portraitUp,
          ]);
          return true;
        },
        child: Scaffold(
            key: _scaffoldKey,
            backgroundColor: Colors.black.withOpacity(0.88),
            body: Center(
                child: SingleChildScrollView(
                    child: Column(children: [
              YoutubePlayer(
                controller: _controller,
                aspectRatio: 16 / 9,
                showVideoProgressIndicator: false,
                controlsTimeOut: Duration(seconds: 2),
                progressIndicatorColor: Colors.red,
                actionsPadding: EdgeInsets.only(bottom: 50),
                topActions: <Widget>[
                  IconButton(
                    icon: Icon(
                      Icons.arrow_back_ios,
                      color: Colors.white,
                      size: 20.0,
                    ),
                    onPressed: () {
                      Navigator.pop(context);
                      SystemChrome.setPreferredOrientations([
                        DeviceOrientation.portraitUp,
                      ]);
                    },
                  ),
                  Expanded(
                    child: Text(
                      'Pastel Painting: Animals',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 18.0,
                      ),
                      overflow: TextOverflow.ellipsis,
                      maxLines: 1,
                    ),
                  ),
                ],
                bottomActions: [
                  CurrentPosition(),
                  SizedBox(width: 10.0),
                  ProgressBar(isExpanded: true),
                  SizedBox(width: 10.0),
                  RemainingDuration(),
                  FullScreenButton(),
                ],
                onReady: () {
                  _isPlayerReady = true;
                },
              ),
            ])))));
  }
}</code></pre>

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.

**Comment by asamprabin** [comment]
This issue still exists @sarbagyastha
