### ISSUE TITLE
[BUG] Invalid Video ID = Error Code: 1

### ISSUE THREAD

**Issue by pulstar** [sarbagyastha/youtube_player_flutter#132]
**Describe the bug**
The message "Invalid Video ID = Error Code: 1" appears and the video don't play, despite its preview is showing in the background. 

**To Reproduce**
Sometimes, when I tap de fullscreen control, the player enter the fullscreen mode, but it don't play, showing the message above. 

Also, because of this message, I can't leave the fullscreen mode and return my device to a normal state, because the Android back button and the status bar are both disabled... The only way I found to solve this was restarting my device.

**Expected behavior**
It should play the video, since the video ID was supplied and is a working video.

**Screenshots**

**Technical Details:**
 - Device: Blu Vivo XI+
 - OS: Android
 - Version: 9

**Additional context**
Sometimes, after playing a video, the controls disappear and only the play button is visible. In order to display the controls, I must navigate away and come back to the video screen to redraw the widget.

Another problem I noticed is a big padding around the video at the left, top and right. To solve this,  I did try to use the aspectRatio property, but this value should be calculated *from the video itself*, and I don't have such metadata to provide it before the widget is built. Any idea?

Best regards,

Edemilson Lima

**Comment by LeeLoHoon** [comment]
Same problem.!

**Comment by sarbagyastha** [comment]
Similar to #119

**Comment by scognito** [comment]
Happens to me only on iOS.
Same video, live version (NASA TV Live)

**Comment by scognito** [comment]
It's different than 119.
Anyway it isn't possible to exit from the "Invalid Video ID" page.
I've added a FullScreenButton() on youtube_player.dart to at least exit from the error:

```
errorWidget: Container(
              color: Colors.black87,
              padding: EdgeInsets.symmetric(horizontal: 40.0, vertical: 20.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Row(
                    children: [
                      Icon(
                        Icons.error_outline,
                        color: Colors.white,
                      ),
                      SizedBox(width: 5.0),
                      Expanded(
                        child: Text(
                          errorString(
                            controller.value.errorCode,
                            videoId: controller.metadata.videoId ??
                                controller.initialVideoId,
                          ),
                          style: TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.w300,
                            fontSize: 15.0,
                          ),
                        ),
                      ),
                    ],
                  ),
                  SizedBox(height: 16.0),
                  Text(
                    'Error Code: ${controller.value.errorCode}',
                    style: TextStyle(
                      color: Colors.grey,
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                  FullScreenButton(), // added this
                ],
              ),
            ),
```

**Comment by scognito** [comment]
I fixed also changing the line 248 of youtube_player.dart:

`controller.load(_videoId, startAt: _cachedPosition.inSeconds),`
to
`controller.load(controller.initialVideoId, startAt: _cachedPosition.inSeconds),`

Probably doesn't work if you have multiple files queued, but this is not my case.

**Comment by geekydiamond** [comment]
This appears to happen again on the latest version (6.1.0+4). I've rolled back to 6.0.3+2 and it is working, so I think the fix has been regressed.

**Comment by catchme1412** [comment]
With latest version 6.1.1 the problem exists.
