### ISSUE TITLE
[BUG] Fullscreen mode on iOS device

### ISSUE THREAD

**Issue by channdara** [sarbagyastha/youtube_player_flutter#133]
**Describe the bug**
after exit fullscreen mode on iOS, the app becomes fullscreen too (the status bar is gone. I didn't make the app in fullscreen mode)

**Expected behavior**
after exit fullscreen, the app status bar should visible normally

**Technical Details:**
 - Device: maybe all iPhone device (Android doesn't have this problem)
 - Version: any

**Screenshot Detail**
![IMG_0440](https://user-images.githubusercontent.com/39755325/70905317-24721300-2036-11ea-8832-5334e0c6e2b7.PNG)

**Comment by the-badcoder** [comment]
Is there any way I can stop playing video "Full Screen" automatically when the video is prepared?

**Comment by sarbagyastha** [comment]
Sorry for the late response, was on a tight schedule. Will be working on the issue within this week.

**Comment by tasleem96** [comment]
Is there any update regarding this issue?

**Comment by sarbagyastha** [comment]
Should fix with version 6.1.0
