### ISSUE TITLE
[BUG] 404 error getting image from youtube

### ISSUE THREAD

**Issue by sgehrman** [sarbagyastha/youtube_player_flutter#134]
**Describe the bug**

Today I'm getting this:

Exception has occurred.
NetworkImageLoadException (HTTP request failed, statusCode: 404, https://i3.ytimg.com/vi_webp/iT1hpbS-Qxo/sddefault.webp)

 - Device: Android simulator
 - OS: Android 10

That link works in the browser.

**Comment by sgehrman** [comment]
found out one of my youtube links was bad, said video not available, but it shouldn't throw an exception.

**Comment by jpiabrantes** [comment]
How did you fix this? I am getting the same issue

**Comment by Evenson19** [comment]
> How did you fix this? I am getting the same issue

I'm facing the same issue, did you find a way to fix that?

**Comment by Luktm** [comment]
I am facing this issue too!

**Comment by Luktm** [comment]
Duplicate of #164

**Comment by venky9885** [comment]
Still we are facing same issue
