### ISSUE TITLE
Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view,

### ISSUE THREAD

**Issue by kalismeras61** [sarbagyastha/youtube_player_flutter#137]
**Describe the bug**
On android when i listed more than 1 video i got this error.

**Technical Details:**
 - Device: Huawei Mate 10 Pro / Real device
 - OS: [e.g.  Android 9.1
 

**Additional context**
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 2
E/flutter (32477): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (32477): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (32477): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (32477): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (32477): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (32477): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (32477): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (32477): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/flutter (32477): 	at android.os.Looper.loop(Looper.java:175)
E/flutter (32477): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/flutter (32477): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32477): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/flutter (32477): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/flutter (32477): , null)
E/flutter (32477): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter (32477): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:321
E/flutter (32477): <asynchronous suspension>
E/flutter (32477): #2      AndroidViewController._create 
package:flutter/…/services/platform_views.dart:640
E/flutter (32477): #3      AndroidViewController.setSize 
package:flutter/…/services/platform_views.dart:557
E/flutter (32477): #4      RenderAndroidView._sizePlatformView 
package:flutter/…/rendering/platform_view.dart:174
E/flutter (32477): #5      RenderAndroidView.performResize 
package:flutter/…/rendering/platform_view.dart:155
E/flutter (32477): #6      RenderObject.layout 
package:flutter/…/rendering/object.dart:1703
E/flutter (32477): #7      RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
E/flutter (32477): #8      RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #9      RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
E/flutter (32477): #10     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #11     RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
E/flutter (32477): #12     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #13     RenderStack.performLayout 
package:flutter/…/rendering/stack.dart:505
E/flutter (32477): #14     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #15     RenderAspectRatio.performLayout 
package:flutter/…/rendering/proxy_box.dart:520
E/flutter (32477): #16     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #17     RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
E/flutter (32477): #18     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #19     RenderConstrainedBox.performLayout 
package:flutter/…/rendering/proxy_box.dart:259
E/flutter (32477): #20     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #21     RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
E/flutter (32477): #22     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #23     RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
E/flutter (32477): #24     _RenderCustomClip.performLayout 
package:flutter/…/rendering/proxy_box.dart:1232
E/flutter (32477): #25     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
E/flutter (32477): #26     RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
E/flutter (32477): #27     RenderObject.layout 
package:flutter/…/rendering/object.dart:1724

**Comment by sarbagyastha** [comment]
Might be a problem in platform view. Similar issue exist for [google_maps_flutter](https://github.com/flutter/flutter/issues/45695)

**Comment by Babwenbiber** [comment]
I had the same bug.
What helped me was this [StackOverFlow answer](https://stackoverflow.com/questions/59511692/google-maps-trying-to-create-a-platform-view-of-unregistered-type)

1. Clean App data & Uninstall the current app.
2. Run flutter clean & flutter build.
3. Run Your App again
