### ISSUE TITLE
Does this app Violate YouTube Terms on Android?

### ISSUE THREAD

**Issue by sumitgohil** [sarbagyastha/youtube_player_flutter#14]
The player hides YouTube logo, and title.
It doesn't show ads as well.
Does this violate YouTube terms?

**Comment by sarbagyastha** [comment]
@sumitgohil , ads are not showing because of HTML5 player in mobile based browser, it's not the issue of plugin. So it shouldn't be violation against YouTube TOS.
Also the player doesn't hides YouTube's logo and title, it just minifies them. If you zoom in more, you'll be able to see it 😉.

**Comment by sumitgohil** [comment]
Woaah, That's a smart move. 
I appreciate. 

Though is there any way we could get back them to Normal state?

**Comment by sarbagyastha** [comment]
@sumitgohil will also include the option to toggle it, once the iOS part fixes.

**Comment by sumitgohil** [comment]
@sarbagyastha  Yes that would be really great. 
By when can we expect a new version with iOS fix and the Toggle thing?

**Comment by sarbagyastha** [comment]
I will try to work on it this weekend if i get some spare time.

**Comment by sarbagyastha** [comment]
With [Version 2.0.0](https://pub.dev/packages/youtube_player_flutter#200) `forceHideAnnotation` is exposed, which is disabled by default. Enabling it will only hide the title and other youtube stuffs.

**Comment by ahmedelameer34** [comment]
Should I care about copyright of videos?
