### ISSUE TITLE
[BUG] How to dispose the controller if I'm looping in multiple videos ( ListBuilder )

### ISSUE THREAD

**Issue by heshaShawky** [sarbagyastha/youtube_player_flutter#141]
**Describe the bug**
I'm building kinda a blog/social media something similar to FB in the video part, So looping the posts ( with youtube video ) in `ListView.builder` and as the documentation, I have to pass the `YoutubePlayerController` in each `YoutubePlayer` on the list! 

My question is how to dispose those controllers? to avoid memory leaks especially my case?!!

Also when I start scrolling down then back getting up to the previous video the video start from the beginning, not from the point I  left off every time.

**Comment by sarbagyastha** [comment]
You can maintain a list of all the controllers you created and dispose them all when needed. 
Also using the player in larger listview is not recommended as it'll be heavy on performance.

**Comment by samatzhusup** [comment]
> **Describe the bug**
> I'm building kinda a blog/social media something similar to FB in the video part, So looping the posts ( with youtube video ) in `ListView.builder` and as the documentation, I have to pass the `YoutubePlayerController` in each `YoutubePlayer` on the list!
> 
> My question is how to dispose those controllers? to avoid memory leaks especially my case?!!
> 
> Also when I start scrolling down then back getting up to the previous video the video start from the beginning, not from the point I left off every time.

hi you found answer how fix scroll lags)?
