### ISSUE TITLE
Can you add a feature to hide the Full screen button in the player controls. 

### ISSUE THREAD

**Issue by kushalmahapatro** [sarbagyastha/youtube_player_flutter#142]
** Thank for this Plugin**

Can you please add a feature by which we can be able to hide the Fullscreen button in the player controls?

**Comment by MatthewManageMy** [comment]
This is already possible by giving the YoutubePlayer a new list of bottomActions, and not including the FullScreenButton:

`YoutubePlayer(
        controller: _controller,
        showVideoProgressIndicator: true,
        bottomActions: <Widget>[
          const SizedBox(width: 14.0),
          CurrentPosition(),
          const SizedBox(width: 8.0),
          ProgressBar(isExpanded: true),
          RemainingDuration(),
          const PlaybackSpeedButton(),
        ],
      );`

Hope this is what you're after!

**Comment by kushalmahapatro** [comment]
Yeah it worked, Thank You,
