### ISSUE TITLE
FullScreen mode is not rendering  smoothly. 

### ISSUE THREAD

**Issue by SSVernekar** [sarbagyastha/youtube_player_flutter#143]
Hello,
In this package player is not rendering smoothly when full screen button is tapped.
and  when full screen is rendered it is taking some time  to  play video. the continuation flow is missing here. this is my request to you guys please solve this issue as soon as possible.

**Comment by SSVernekar** [comment]
@sarbagyastha  any solution for this.....?

**Comment by sarbagyastha** [comment]
Currently there's no solution for this.

**Comment by nirav4273** [comment]
@sarbagyastha  Is there any alternate way to render video smoothly in in full screen & normal view for youtube video ?
