### ISSUE TITLE
[BUG]  _controller.fitHeight does not works

### ISSUE THREAD

**Issue by dungnv2602** [sarbagyastha/youtube_player_flutter#145]
**To Reproduce**
`
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

class YoutubePlayerPage extends StatefulWidget {
  final String id;

  const YoutubePlayerPage({Key key, @required this.id})
      : assert(id != null),
        super(key: key);

  @override
  _YoutubePlayerPageState createState() => _YoutubePlayerPageState();
}

class _YoutubePlayerPageState extends State<YoutubePlayerPage> {
  YoutubePlayerController _controller;

  PlayerState _playerState;
  // double _volume = 100;
  // bool _muted = false;
  bool _isPlayerReady = false;

  @override
  void initState() {
    super.initState();
    _controller = YoutubePlayerController(
      initialVideoId: widget.id,
      flags: const YoutubePlayerFlags(
        mute: true,
        autoPlay: true,
        loop: true,
        disableDragSeek: true,
        forceHideAnnotation: true,
        hideControls: true,
        hideThumbnail: true,
        enableCaption: false,
        controlsVisibleAtStart: false,
        isLive: false,
      ),
    )..addListener(listener);
  }

  void onReady() {
    _controller.fitHeight(MediaQuery.of(context).size);  // wonder put in this place is appropriate
    _isPlayerReady = true;
  }

  void listener() {
    if (_isPlayerReady && mounted && !_controller.value.isFullScreen) {
      setState(() {
        _playerState = _controller.value.playerState;
      });
    }
  }

  @override
  void deactivate() {
    // Pauses video while navigating to next page.
    _controller.pause();
    super.deactivate();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    //_controller.fitHeight(MediaQuery.of(context).size); => tried in this but not work either
    return YoutubePlayer(
      controller: _controller,
      onReady: onReady,
    );
  }
}
`

**Expected behavior**
The video player fit the screen's height

**Screenshots**
![fitHeight](https://user-images.githubusercontent.com/19910775/73215214-29be9380-4186-11ea-827d-2ada290dc9fe.png)

**Comment by sarbagyastha** [comment]
Fixed in v6.1.0
