### ISSUE TITLE
[BUG]The method 'addListener' was called on null.

### ISSUE THREAD

**Issue by mubaraknet** [sarbagyastha/youtube_player_flutter#146]
Getting the below error from initState()
@override
  void initState(){
    super.initState();
    _initVideo();
    _initPlayer();
  }

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building _BodyBuilder:
flutter: The method 'addListener' was called on null.
flutter: Receiver: null
flutter: Tried calling: addListener(Closure: () => void from Function 'listener':.)
flutter:
flutter: The relevant error-causing widget was:
flutter:   Scaffold file:///Users/zade/Inkers/sinai/sinai/lib/screens/liveStream.dart:50:12
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
flutter: #1      _YoutubePlayerState.initState (package:youtube_player_flutter/src/player/youtube_player.dart:200:37)
flutter: #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
flutter: #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)

**Comment by sarbagyastha** [comment]
You need to pass the controller in YoutubePlayer widget.
