### ISSUE TITLE
[Question] Videos don't play in release mode

### ISSUE THREAD

**Issue by dustincatap** [sarbagyastha/youtube_player_flutter#149]
When in debug and profile mode, videos play normally. Am I missing something?

Using the latest version of the plugin, tested on Android device running Android 29.

Have not checked yet in iOS.

**Comment by stelselim** [comment]
same issue, too.
IOS devices was working

**Comment by pastordee** [comment]
Did you Run flutter build ios

**Comment by sarbagyastha** [comment]
Did you add internet permission ?

**Comment by dustincatap** [comment]
> Did you add internet permission ?

That did it. I didn't add the internet permission. Thanks!

**Comment by jimmyff** [comment]
@dustincatap could I ask what it is you did to add the internet permission? 

I've added this to my `Info.plist` but it hasn't fixed the issue for me:

```
		<key>NSAppTransportSecurity</key>
		<dict>
			<key>NSAllowsArbitraryLoads</key>
			<true />
		</dict>
```

Thanks

**Comment by pastordee** [comment]
Have you run flutter build ios

**Comment by jimmyff** [comment]
@pastordee yes, I'm running `flutter build ios` then switching to Xcode (via the `Runner.xcworkspace` file) - then I hit Run in Xcode. 

I have been to `Product -> Edit Scheme and set it to `Release` as I am running this on a physical iPhone. 

It's worth noting that when I test the `Debug` scheme on the simulator my videos load and play as expected. They dont load only when I'm using a physical iphone.

I have tested using earlier versions of this package as well as stable, dev & master channel of flutter. I am currently using the master channel.

**Comment by dustincatap** [comment]
@jimmyff The permission I was referring to was for the Android part, which I added to the manifest.

For the iOS, I only added this to `Info.plist`:
```xml
...
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
...
```

Mine was working.

**Comment by jimmyff** [comment]
Ah, I've found my issue. For some reason on physical device it's just showing the youtube mobile site where the video should be. I've created a ticket for it:
https://github.com/sarbagyastha/youtube_player_flutter/issues/176
