### ISSUE TITLE
No podspec found for `webview_media` in `.symlinks/plugins/webview_media/ios`

### ISSUE THREAD

**Issue by vitulgoyani** [sarbagyastha/youtube_player_flutter#152]
No podspec found for `webview_media` in `.symlinks/plugins/webview_media/ios`

can't run in ios get an error for webview_media, also i did update pod but it can't update,

Please help me @sarbagyastha🙏🏻

**Comment by sarbagyastha** [comment]
Updated webview, try `flutter clean` and `flutter pub get`.

**Comment by nickpnmrv** [comment]
Having the same problem:
`Launching lib/main_dev.dart on iPhone 8 Plus in debug mode...
Xcode build done.                                            2.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
   ...flutter/.pub-cache/hosted/pub.dartlang.org/webview_media-0.1.1+1/ios/Classes/FlutterWebView.m:91:50: error: expected ';' after expression
        configuration.allowsInlineMediaPlayback = YES
                                                     ^
                                                     ;
    .../flutter/.pub-cache/hosted/pub.dartlang.org/webview_media-0.1.1+1/ios/Classes/FlutterWebView.m:407:20: warning: 'loadData:MIMEType:characterEncodingName:baseURL:' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      return [_webView loadData:nsData MIMEType:mimeType characterEncodingName:encoding baseURL:nsUrl];
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from ...flutter/.pub-cache/hosted/pub.dartlang.org/webview_media-0.1.1+1/ios/Classes/FlutterWebView.h:6:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebView.h:116:1: note: 'loadData:MIMEType:characterEncodingName:baseURL:' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    - (nullable WKNavigation *)loadData:(NSData *)data MIMEType:(NSString *)MIMEType characterEncodingName:(NSString *)characterEncodingName baseURL:(NSURL *)baseURL API_AVAILABLE(macos(10.11), ios(9.0));
    ^
   .../flutter/.pub-cache/hosted/pub.dartlang.org/webview_media-0.1.1+1/ios/Classes/FlutterWebView.m:407:20: note: enclose 'loadData:MIMEType:characterEncodingName:baseURL:' in an @available check to silence this warning
      return [_webView loadData:nsData MIMEType:mimeType characterEncodingName:encoding baseURL:nsUrl];
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning and 1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone 8 Plus.
Exited (sigterm)`

**Comment by sarbagyastha** [comment]
@nickpnmrv Cloud you please check again whether it's working now?

**Comment by nickpnmrv** [comment]
It doesn't build still, but now another problem with pod install this time:
`[!] CocoaPods could not find compatible versions for pod "webview_media":
  In Podfile:
    webview_media (from `.symlinks/plugins/webview_media/ios`)

Specs satisfying the `webview_media (from `.symlinks/plugins/webview_media/ios`)` dependency were found, but they required a higher minimum deployment target.
`

**Comment by sarbagyastha** [comment]
Tested on ios and it's working now. Could you please once again and confirm ?

**Comment by nickpnmrv** [comment]
Ok, I finally got it. My app has another dependency on webview_flutter: ^0.3.19+8 which somehow collides with youtube_player_flutter
Deleting on of the dependencies solves the build problem

**Comment by sarbagyastha** [comment]
@nickpnmrv The package exports **webview_media** which is actually a fork of webview_flutter. So you can use Webview widget exported from `import package:youtube_player_flutter/youtube_player_flutter.dart;`

**Comment by nickpnmrv** [comment]
@sarbagyastha it doesn't look like youtube_player_flutter.dart exposes any of the classes I am using:
WebViewController
WebView
Were you able to actually use it as per the last comment? Do you have an example to share?

**Comment by sarbagyastha** [comment]
try using `import package:webview_media/webview_flutter.dart` then

**Comment by mayurdhurpate** [comment]
`import package:webview_media/webview_flutter.dart` this works in my case. But I have some apprehensions with the fork. `webview_flutter` is a major package used by us, and will the `webview_media` be kept updated with the latest version of the `webview_flutter`?

**Comment by sarbagyastha** [comment]
@mayurdhurpate Any major update or improvements will be updated. Also will be working on resolving the conflict with `webview_flutter` package.

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.
