### ISSUE TITLE
iOS disable fullscreen

### ISSUE THREAD

**Issue by despie** [sarbagyastha/youtube_player_flutter#153]
On iOS, video always plays in fullscreen. 

Is there a way to play video without going fullscreen on iOS?
This feature works ok on Android.

It seems that [webview_flutter can support this](https://github.com/flutter/flutter/issues/25630#issuecomment-519944597)?

**Comment by sarbagyastha** [comment]
@despie What's the version you're using ?

**Comment by despie** [comment]
I was using `youtube_player_flutter: ^6.1.0+2`. But I see that this is fixed now in `youtube_player_flutter: ^6.1.0+4`.
@sarbagyastha Thank you!
