### ISSUE TITLE
Buffer indicator is not stopping

### ISSUE THREAD

**Issue by dheerajsarwaiya** [sarbagyastha/youtube_player_flutter#154]
HI,

After i upgraded from 6.0.3+2, the buffer indicator is not stopping on video. Even when onReady function is getting executed. I am keeping autoPlay as false. 

![Screenshot from 2020-02-22 15-28-00](https://user-images.githubusercontent.com/18539875/75100197-fb1ab980-5587-11ea-9db2-b783226b5244.png)

Here is flutter doctor.
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_US.UTF-8)
 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (3 available)

I see following logs, which I was not seeing in last version.

V/ViewRootImpl(14763): The specified message queue synchronization  barrier token has not been posted or has already been removed
I/chromium(14763): [INFO:CONSOLE(139)] "Unrecognized feature: 'picture-in-picture'.", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl2dBoXz/www-widgetapi.js (139)
E/SensorManager(14763): registerListenerImpl sensorName:Game Rotation Vector  Non-wakeup,isWakeUpSensor:false,callingApp: com.notestring.notestring,callingPid:14763,callingUid:10346
E/SensorManager(14763): unregisterListenerImpl sensorName:Game Rotation Vector  Non-wakeup,isWakeUpSensor:false,callingApp: com.notestring.notestring,callingPid:14763,callingUid:10346
W/System  (14763): A resource failed to call release.

-- I see this error as well, when I close the app

E/BufferQueueProducer(14763): [SurfaceTexture-0-14763-20] dequeueBuffer: BufferQueue has been abandoned
I/Surface (14763): opservice is null false
E/InputMethodManager(14763): b/117267690: Failed to get fallback IMM with expected displayId=409 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{300b220 VFEDHVC.. ........ 0,0-1349,759}

**Comment by sarbagyastha** [comment]
Fixed with new patch version **v6.1.0+4**
