### ISSUE TITLE
[BUG] Not able to import webview widget with   youtube_player_flutter: ^6.1.0+4

### ISSUE THREAD

**Issue by madhu-1stmain** [sarbagyastha/youtube_player_flutter#155]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Technical Details:**

**Additional context**

**Comment by sarbagyastha** [comment]
The package already exports webview. So you can remove webview_flutter dependency.

**Comment by madhu-1stmain** [comment]
But i can't able to import webview

**Comment by marcinsiedlik** [comment]
Have the same issue.
I removed `webview_flutter` dependency. Adding this import: `import 'package:youtube_player_flutter/youtube_player_flutter.dart';` does not import WebView

**Comment by shpy2001** [comment]
> Have the same issue.
> I removed `webview_flutter` dependency. Adding this import:
> `import 'package:youtube_player_flutter/youtube_player_flutter.dart';`
> does not importing WebView

I removed `webview_flutter` and add this :
import 'package:webview_media/webview_flutter.dart';

It's work. But i dont know the version of this webview_flutter.dart.

**Comment by marcinsiedlik** [comment]
> I removed `webview_flutter` and add this :
> import 'package:webview_media/webview_flutter.dart';
> 
This is correct import.
It is listed in dependencies but I think that it's also worth mentioning in readme

**Comment by madhu-1stmain** [comment]
this works 
import 'package:webview_media/webview_flutter.dart';

**Comment by madhu-1stmain** [comment]
shpy2001 solutions worked for  me
