### ISSUE TITLE
[BUG] I/flutter (27483): The controller is not ready for method calls. With latest version

### ISSUE THREAD

**Issue by madhu-1stmain** [sarbagyastha/youtube_player_flutter#156]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Technical Details:**

**Additional context**

**Comment by furaiev** [comment]
This one is reproducible only on Simulator but works on real device.

**Comment by madhu-1stmain** [comment]
Same issue on real device also

**Comment by madhu-1stmain** [comment]
Any update on this, we are really stuck because of this.

**Comment by jimmyff** [comment]
I also have this issue which is preventing me for putting app in to App Store.

Not sure if it's related to:
https://github.com/sarbagyastha/youtube_player_flutter/issues/149#issuecomment-589932914

**Comment by sarbagyastha** [comment]
Duplicate of #120
