### ISSUE TITLE
Some enhancements needed

### ISSUE THREAD

**Issue by Xoshbin** [sarbagyastha/youtube_player_flutter#16]
Thank you for that great plugin I really love it, But there is some enhancements needed:
1- It's not working on iPhone, You already talked about that in another issue.
2- When there's more than two videos in a list it's kinda getting weird a video stops and another one starts and vice versa. so there must be away to tell which video is on the center of the screen.
3- Adding something like `autoPlay: true,` for the mute at start would be great like `mute: true,`

Again thank you for this great plugin

**Comment by sarbagyastha** [comment]
Thank you for your suggestions, will definitely look into it.

**Comment by sarbagyastha** [comment]
Updated to [Version 2.0.0](https://pub.dev/packages/youtube_player_flutter#200)
