### ISSUE TITLE
[BUG] Videos are not playing in release apk

### ISSUE THREAD

**Issue by shahidcodes** [sarbagyastha/youtube_player_flutter#161]
**Describe the bug**
Everything works as expected in debug mode. Once release apk built it keeps showing circular progress bar.

**To Reproduce**
- Build release apk

**Technical Details:**
 - Device: Oppo K3
 - OS: Android
 - Version: 28

**Comment by shahidcodes** [comment]
My mistake I forgot to put permissions in Manifest, was expecting that flutter will put there.

**Comment by ag84ark** [comment]
I have the same problem, so I do not understand if this is fixed or not.
Thank you!
