### ISSUE TITLE
Fullscreen still shows Scaffolds bottomNavigationBar 

### ISSUE THREAD

**Issue by jimmyff** [sarbagyastha/youtube_player_flutter#163]
I have a media player UI in my Scaffolds bottomNavigationBar, when the video is taken fullscreen the bottomNavigationBar UI is still showing over it. 

Is it not possible to take this above the scaffolds UI? Perhaps using something like an Overlay?

I have tried using bottomSheet and this also has the same issue.

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.
