### ISSUE TITLE
Thumbnail 404 errors causes exceptions

### ISSUE THREAD

**Issue by jimmyff** [sarbagyastha/youtube_player_flutter#164]
I quite often get the following expcetion when opening videos:

```

════════ Exception caught by image resource service ════════════════════════════
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, https://i3.ytimg.com/vi_webp/BP979AMuuP8/sddefault.webp

When the exception was thrown, this was the stack
#0      NetworkImage._loadAsync 
package:flutter/…/painting/_network_image_io.dart:90
<asynchronous suspension>
#1      NetworkImage.load 
package:flutter/…/painting/_network_image_io.dart:47
#2      ImageProvider.resolveStreamForKey.<anonymous closure> 
package:flutter/…/painting/image_provider.dart:491
#3      ImageCache.putIfAbsent 
package:flutter/…/painting/image_cache.dart:344
...
Image provider: NetworkImage("https://i3.ytimg.com/vi_webp/BP979AMuuP8/sddefault.webp", scale: 1.0)
Image key: NetworkImage("https://i3.ytimg.com/vi_webp/BP979AMuuP8/sddefault.webp", scale: 1.0)
```

I think the thumbnail image needs to be loaded in a way to handle 404 errors.

**Comment by jwhijazi** [comment]
Having the same issue... there must be a way to add Alternative thumbnail image if the youtube video doesn't have one.

**Comment by jimmyff** [comment]
@jwhijazi you can specify a thumbnail for the video, although if you do it will not attempt to fetch the youtube one. 

The behavior you have described is possible but it would require the YT thumbnail to be loaded in a different way to catch the 404 and then use the fallback image. I'm a bit too busy at the moment otherwise I would implement this.

**Comment by jwhijazi** [comment]
@jimmyff 
No problem... Once you have time it will be a good fix.
Thanks,

**Comment by codepushr** [comment]
Same, anyone have a solution?

**Comment by dheerajsarwaiya** [comment]
this is how i solved the problem

Youtube provide's a thumbnail images for all its video. All you need to is to insert the VideoID in the provided URL.

`YoutubePlayer(
      controller: _controller,
      thumbnailUrl: "https://img.youtube.com/vi/${videoID}/hqdefault.jpg",
     
    )`

**Comment by Salman-Official** [comment]
@dheerajsarwaiya there is no param for thumbnailUrl in the plugin, can you please describe the same, I'm getting the same exception again and again.

**Comment by dheerajsarwaiya** [comment]
After 7.0.0+2 he removed the thumbnailUrl.   Now you can use any widget in thumbnail parameter. 

**Added thumbnail parameter to YoutubePlayer, removed thumbnailUrl. Now any widget can be used as thumbnail.**

**Comment by Salman-Official** [comment]
@dheerajsarwaiya If I'm getting it correct, the thumbnail param only shows the respective widget till the youtube player loads the correct thumbnail. Correct me if I'm wrong.

**Comment by dheerajsarwaiya** [comment]
no .. it shows whatever you set in thumbnail. If you dont set it, then it will show whatever it get from the video..  I do this

`thumbnailUrl: "https://img.youtube.com/vi/${widget.videoID}/hqdefault.jpg",`
