### ISSUE TITLE
onEnded is not called if in fullscreen mode

### ISSUE THREAD

**Issue by jimmyff** [sarbagyastha/youtube_player_flutter#167]
if video is in full screen when the video ends, `onEnded` does not get called. if I manually toggle fullscreen after it's ended then triggers the `onEnded` however at this point interacting with the controller is buggy - resulting in lots of errors.

**Comment by rafaelmaeuer** [comment]
experience the same problem

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.

**Comment by khmergeo** [comment]
This issue still exists on 8.0.0
