### ISSUE TITLE
[BUG] Circular indicator keeps going on even when video is ended

### ISSUE THREAD

**Issue by shahidcodes** [sarbagyastha/youtube_player_flutter#171]
**Describe the bug**
The circular indicator for video buffering keeps going on even when video is ended. 

**To Reproduce**
* Play a video
* Seek to a little while before end
* Wait till video finishes
* Indicator keeps running

**Expected behavior**
The buffering indicator should never show when video ends. 

**Screenshots**
![untitled](https://user-images.githubusercontent.com/17620737/76147912-33adad80-60c7-11ea-82fa-fe37373bb54a.gif)

**Technical Details:**
 - Device: Android Emulator
 - OS: Android 10

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.

**Comment by baraghiffari** [comment]
I have this problem too, but the problem disappear if i set the autoPlay to false. I use the latest version, 7.0.0+7

**Comment by tnaseem** [comment]
Same. Still happens on the latest version, if auto play is set to true.
