### ISSUE TITLE
[BUG] "request contains an invalid parameter value" error code: 2

### ISSUE THREAD

**Issue by Lunedor** [sarbagyastha/youtube_player_flutter#175]
When trying to play with my android app the video getting below error;
"request contains an invalid parameter value" error code: 2
It was working fine yesterday and I didn't change anything on code..

**Comment by Lunedor** [comment]
It was temporary thing I think, it works now, sorry for false alarm.

**Comment by YashMakan** [comment]
I am having the same issue & it is not resolving. What should I do?

**Comment by sanchaykasturey** [comment]
@YashMakan  could you solve the problem? I am also facing the same problem. Please help

Thanks

**Comment by Lunedor** [comment]
This is usually a temporary issue and solved by itself in time.

**Comment by ApWin** [comment]
@YashMakan could you solve the problem? I am also facing the same problem. Please help

**Comment by goatandsheep** [comment]
My issue is I was using url as ID. make sure to do `initialVideoId: YoutubePlayer.convertUrlToId(url)`

**Comment by Shubham-Narkhede** [comment]
@goatandsheep @sarbagyastha when I'm using the youtube shorts video URL in `initialVideoId: YoutubePlayer.convertUrlToId(url)` this section then I'm getting the  error code: 2

**Comment by iaht0201** [comment]
Check url protocol. Instead of http change to https
