### ISSUE TITLE
[BUG] Invaild Video id when press full screen

### ISSUE THREAD

**Issue by BoshiLee** [sarbagyastha/youtube_player_flutter#178]
**Describe the bug**
The player shows "Invalid Video id" when press full screen button.

[](url)

**To Reproduce**

Just use the sample code.

`class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  YoutubePlayerController _controller;

  @override
  void initState() {
    this._controller = YoutubePlayerController(
      initialVideoId: "bebuiaSKtU4",
      flags: YoutubePlayerFlags(
        autoPlay: true,
        isLive: true,
      ),
    );
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: YoutubePlayer(
        controller: _controller,
        showVideoProgressIndicator: true,
        progressIndicatorColor: Colors.amber,
        progressColors: ProgressBarColors(
          playedColor: Colors.amber,
          handleColor: Colors.amberAccent,
        ),
        onReady: () {
          print('Player is ready.');
        },
      ),
    );
  }
}`

**Expected behavior**
Normall Full Screen player and not stuck with the error message.

**Screenshots**

![IMG_0010](https://user-images.githubusercontent.com/20209263/77047463-bb68b580-69ff-11ea-9dbc-b5264a127c84.PNG)

**Technical Details:**
 - Device: [ iPhone 8]
 - OS: [e.g. iOS13.1]
 - Version [6.1.0+4]

**Additional context**

**Comment by rafaelmaeuer** [comment]
happens for me too when going fullscreen before starting playback

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.
