### ISSUE TITLE
Can you help support Queueing functions

### ISSUE THREAD

**Issue by phattranky** [sarbagyastha/youtube_player_flutter#18]
In the [https://developers.google.com/youtube/iframe_api_reference](https://developers.google.com/youtube/iframe_api_reference) have support Queueing functions like Play, Stop, SeekTo to control the video. Can you help to implement as well

**Comment by sarbagyastha** [comment]
Those functions are already available through controller. [See here](https://pub.dev/documentation/youtube_player_flutter/latest/youtube_player_flutter/YoutubePlayerController-class.html)

**Comment by phattranky** [comment]
@sarbagyastha  Thanks for the quick response. Because I didn't see in the DOCS. So I guess it's still not support
