### ISSUE TITLE
Flutter build apk Failed

### ISSUE THREAD

**Issue by arulselvan** [sarbagyastha/youtube_player_flutter#183]
**Describe the bug**
Unable to create a release build,  its throwing error in our youtube_player_flutter plugin

**To Reproduce**
Command : flutter build apk --split-per-abi

FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':youtube_api:verifyReleaseResources'.        
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/abasker/.gradle/caches/transforms-2/files-2.1/0a271e99b6771ad4a84318244d532fb7/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
     /Users/abasker/.gradle/caches/transforms-2/files-2.1/0a271e99b6771ad4a84318244d532fb7/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 10s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      16.4s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the
incompatibility.
Building plugin webview_media...
The plugin webview_media could not be built due to the issue above.   

**Expected behavior**
It should give release apk file

**Technical Details:**
 - Device: [Samsung]
 - OS: macOS Catalina

**Screenshot***
![image](https://user-images.githubusercontent.com/6116938/77849505-b5d25300-71e9-11ea-87f9-353f8da8318d.png)

**Comment by twoabd** [comment]
Using the older flutter version (v1.9.1+hotfix.2) solved my issue.
