### ISSUE TITLE
Crashes or shutdown the app when exit the fullscreen video

### ISSUE THREAD

**Issue by ShohidulProgrammer** [sarbagyastha/youtube_player_flutter#187]
W/PlatformViewsController(18956): 
Creating a virtual display of size: [1440, 810] may result in problems.
It is larger than the device screen size: [1344, 720].
W/ContentCatcher(18956): Failed to notify a WebView
E/libc    (18956): Access denied finding property "vendor.debug.bq.line"

**Comment by ClemaX** [comment]
This could be related to #188 
Did you enable `forceHideAnnotation: true`?

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.
