### ISSUE TITLE
Crash on fullscreen mode Android 8.0.0 [BUG]

### ISSUE THREAD

**Issue by nazamov** [sarbagyastha/youtube_player_flutter#191]
App crashed after switching to fullscreen mode on Samsung A5 2017. Android Version 8.0.0

Here log. 

F/libc    (14315): Fatal signal 6 (SIGABRT), code -6 in tid 14747 (RenderThread)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a5y17ltexx/a5y17lte:8.0.0/R16NW/A520FXXUCCSK1:user/release-keys'
Revision: '8'
ABI: 'arm64'
pid: 14315, tid: 14747, name: RenderThread  >>> pro.nabi.funny_videos <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'Failed to set damage region on surface 0x77b5ec4080, error=EGL_BAD_ACCESS'
    x0   0000000000000000  x1   000000000000399b  x2   0000000000000006  x3   0000000000000008
    x4   4500000000000000  x5   4500000000000000  x6   4500000000000000  x7   0000000000008045
    x8   0000000000000083  x9   3d7174455c83f0c4  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000002  x14  ffffffffffffffff  x15  4500000000000000
    x16  00000078041572f8  x17  00000078040f8408  x18  0000000000000000  x19  00000000000037eb
    x20  000000000000399b  x21  00000077f51a9618  x22  00000077cbb916d0  x23  00000077f51a5848
    x24  00000077f51a57dc  x25  00000077ccbff1e8  x26  00000077ccbff1d0  x27  00000077ffcad978
    x28  7fffffffffffffff  x29  00000077ccbfe700  x30  00000078040aabd4
    sp   00000077ccbfe6c0  pc   00000078040f8410  pstate 0000000060000000
backtrace:
    #00 pc 000000000006b410  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000001dbd0  /system/lib64/libc.so (abort+88)
    #02 pc 0000000000007f44  /system/lib64/liblog.so (__android_log_assert+304)
    #03 pc 000000000004ff1c  /system/lib64/libhwui.so (_ZN7android10uirenderer12renderthread10EglManager11damageFrameERKNS1_5FrameERK6SkRect+352)
    #04 pc 000000000004d6cc  /system/lib64/libhwui.so (_ZN7android10uirenderer12renderthread14OpenGLPipeline4drawERKNS1_5FrameERK6SkRectS8_RKNS0_12FrameBuilder13LightGeometryEPNS0_16LayerUpdateQueueERKNS0_4RectEbRKNS0_15BakedOpRenderer9LightInfoERKNSt3__16vectorINS_2spINS0_10RenderNodeEEENSM_9allocatorISQ_EEEEPNS0_19FrameInfoVisualizerE+76)
    #05 pc 000000000004b6a4  /system/lib64/libhwui.so (_ZN7android10uirenderer12renderthread13CanvasContext4drawEv+176)
    #06 pc 000000000004ed80  /system/lib64/libhwui.so (_ZN7android10uirenderer12renderthread13DrawFrameTask3runEv+184)
    #07 pc 00000000000558ac  /system/lib64/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+348)
    #08 pc 000000000001160c  /system/lib64/libutils.so (_ZN7android6Thread11_threadLoopEPv+280)
    #09 pc 00000000000fcce0  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+136)
    #10 pc 0000000000067d04  /system/lib64/libc.so (_ZL15__pthread_startPv+200)
    #11 pc 000000000001f348  /system/lib64/libc.so (__start_thread+68)
Lost connection to device.

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.
