### ISSUE TITLE
[FEATURE REQUEST] Access metadata before the video is displayed

### ISSUE THREAD

**Issue by alekskuzmin** [sarbagyastha/youtube_player_flutter#193]
Currently the only way to access video metadata is to start playing the video.

It would be nice for `YoutubePlayerController.metadata` to return metadata even if the video has not been played yet.

**Comment by sarbagyastha** [comment]
@alekskuzmin The iframe player doesn't provide such API. You'll have to do it with [Youtube Data API](https://developers.google.com/youtube/v3)
