### ISSUE TITLE
I got message error for IOS [VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding

### ISSUE THREAD

**Issue by SunryTeang** [sarbagyastha/youtube_player_flutter#20]
[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding

**Comment by someoneNameGrey** [comment]
I guess you might need to register [webview_flutter](https://pub.dev/packages/webview_flutter#-readme-tab-) to solve this problem.

**Comment by sarbagyastha** [comment]
`Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with the key io.flutter.embedded_views_preview and the value YES.`

You'll need to enable embedded view in iOS.
