### ISSUE TITLE
[BUG] Thumbnail does not hide when click on fullscreen

### ISSUE THREAD

**Issue by ManKeomorakort** [sarbagyastha/youtube_player_flutter#202]
Firstly view video in portrait, then click on fullscreen. Then thumbnail display and hear only sound.

**Comment by sarbagyastha** [comment]
https://github.com/sarbagyastha/youtube_player_flutter/issues/227#issue-620337005

**Comment by sarbagyastha** [comment]
Should be fixed with v7.0.0
