### ISSUE TITLE
[BUG] Live Stream won't play

### ISSUE THREAD

**Issue by GuiOliveira1995** [sarbagyastha/youtube_player_flutter#204]
When I try to play a Live video, the play button and the thumbnail appears like it should appears. But, when I click on the play button, the error "The requested content cannot be played by the player" is shown.

Version being used: **youtube_player_flutter: ^6.1.0+7**

The below code reproduces the error. You should change **livestream_video_id** to a live stream video_id.
```dart
import 'package:flutter/material.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

class VideoList extends StatefulWidget {
  @override
  _VideoListState createState() => _VideoListState();
}

class _VideoListState extends State<VideoList> {
  final List<YoutubePlayerController> _controllers = [
    '**livestream_video_id**'
  ]
      .map<YoutubePlayerController>(
        (videoId) => YoutubePlayerController(
          initialVideoId: videoId,
          flags: YoutubePlayerFlags(
            isLive: true,
            autoPlay: false,
          ),
        ),
      )
      .toList();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('NASA Live'),
      ),
      body: ListView.separated(
        itemBuilder: (context, index) {
          return YoutubePlayer(
            key: ObjectKey(_controllers[index]),
            controller: _controllers[index],
            actionsPadding: EdgeInsets.only(left: 16.0),
            bottomActions: [
              CurrentPosition(),
              SizedBox(width: 10.0),
              ProgressBar(isExpanded: true),
              SizedBox(width: 10.0),
              RemainingDuration(),
              FullScreenButton(),
            ],
          );
        },
        itemCount: _controllers.length,
        separatorBuilder: (context, _) => SizedBox(height: 10.0),
      ),
    );
  }
}
```

**Expected behavior**
When I play any video (with **isLive** configured to **false**), everything works great. I think that just by putting a live video id and changing **isLive** to true should be enough to play the live stream.

**Screenshots**
![image](https://user-images.githubusercontent.com/37703267/80850920-f4966700-8bf4-11ea-96e4-2e53c8ec6317.png)

![image](https://user-images.githubusercontent.com/37703267/80850911-e7797800-8bf4-11ea-828f-76acc90c24b4.png)

**Technical Details:**
- Android Emulator: Nexus 5, API 29 with PlayServices

**Comment by sarbagyastha** [comment]
Working fine for me though. Can you provide me with the id, the issue occured on ?

**Comment by VictorJPimentel** [comment]
I'm having the same issue, any solution?
