### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shailendra-rajpoot** [sarbagyastha/youtube_player_flutter#205]
youtube_player_flutter: 6.1.0+7 create issue with flutter_html: 1.0.0-pre.1
plz resolve it my project need  flutter_html: 1.0.0-pre.1

**Comment by vptcnt** [comment]
Hello,

Same problem here with 


youtube_player_flutter: ^6.1.1
flutter_widget_from_html: ^0.3.3+2
flutter_html: ^1.0.0-pre.1

youtube_player_flutter alone works.
flutter_widget_from_html & flutter_html without youtube_player_flutter work

But all together, there are some build errors.

**Comment by ceokin** [comment]
I have the same issue. In Android, videos from youtube do not work anymore. In iOS, there is a crash once the app is launched. Please, could someone solve this problem? Both packages are using the same plugins.

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.
