### ISSUE TITLE
Why is it so memory intensive?

### ISSUE THREAD

**Issue by jeromeall** [sarbagyastha/youtube_player_flutter#21]
Thanks for this player, it's awesome! 

Is there a way to limit how much ram this player uses? I cloned the example app and it keeps crashing my emulator.

**Comment by sarbagyastha** [comment]
Currently there is no way to limit usage as it's a webview painted using PlatformView. I am constantly looking for newer techniques possible, but for now it's what you can get. If you need only Android support then you can consider using youtube_player plugin instead. But cannot guarantee it's violation against Youtube TOS.

**Comment by sarbagyastha** [comment]
Checkout beta [**v3.0.0-beta.4**](https://pub.dev/packages/youtube_player_flutter/versions/3.0.0-beta.4).
