### ISSUE TITLE
How can I hide pop-up window within Youtube after stopping video in player?

### ISSUE THREAD

**Issue by sk784** [sarbagyastha/youtube_player_flutter#210]
![Screenshot_20200509-125220](https://user-images.githubusercontent.com/44239544/81470583-1a72cb80-91f4-11ea-95bd-887dce681423.png)

**Comment by sarbagyastha** [comment]
Iframe API doesn't provides any way to hide those.

**Comment by designwithshoeb** [comment]
you hide it with javascript function
pull request for that 
[pull request](https://github.com/sarbagyastha/youtube_player_flutter/pull/216)

**Comment by kamathprasad9** [comment]
> you can hide it with javascript function
> [pull request for that ](https://github.com/sarbagyastha/youtube_player_flutter/pull/216)

Hey there, i tried out implementing your edit in my personal project. It didnt work out. Did it work well with you? If yes share the screenshots please

**Comment by sarbagyastha** [comment]
Duplicate of #227
