### ISSUE TITLE
[BUG] Cannot play more than one video at a time

### ISSUE THREAD

**Issue by nitnahtnit** [sarbagyastha/youtube_player_flutter#211]
**Describe the bug**
Having two separate controllers for two separate youtube videos loads correctly but cannot play more than one at a time. Playing another video stops playback of the one currently playing.

**To Reproduce**
Create two separate controllers and click 'play' on the second when first is playing.

**Expected behavior**
Expected to run two separate videos at the same time

**Screenshots**
n/a

**Technical Details:**
 - Device: Android
 - OS: Android
 - Version 9

**Comment by sarbagyastha** [comment]
I guess, this cannot be fixed.
