### ISSUE TITLE
Live streaming and Fullscreen errors

### ISSUE THREAD

**Issue by nkrishnika** [sarbagyastha/youtube_player_flutter#212]
1st bug- When I am using a live stream, the debugging app is paused and video also stops. But audio can listen. Then I press continue(F5), Video can be watch and app work fine. This not happen when using a normal video.

2nd bug- When I rotate the phone, the app keeps crashing and the debug console shows this.
"I/Process ( 3859): Sending signal. PID: 3859 SIG: 9"
Then lost the connection to the phone

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0. Feel free to reopen if the issue persists.

**Comment by navinSing** [comment]
Looks like still open,, still getting the same issue.
