### ISSUE TITLE
this plugin not work with   flutter_html: ^1.0.0-pre.1

### ISSUE THREAD

**Issue by shailendra-rajpoot** [sarbagyastha/youtube_player_flutter#215]
this plugin not work with   flutter_html: ^1.0.0-pre.1 please resolve it as soon as possible.

**Comment by whatamelon** [comment]
same here

**Comment by shailendra-rajpoot** [comment]
flutter_html: ^1.0.0
  webview_flutter: ^0.3.19+5
  youtube_player_flutter: 6.0.3+2
  
you can use this combination bro its working togather

**Comment by whatamelon** [comment]
@shailendra-rajpoot Thx. Its working for me.

**Comment by Shamik07** [comment]
@shailendra-rajpoot Thanks bro!

**Comment by hktom** [comment]
i got the the same proble and I used an alternative for flutter HTML 
flutter_widget_from_html_core 0.3.3+4
with the last version of  youtube_player_flutter and everything worked fine.

**Comment by sarbagyastha** [comment]
Starting from v7.0.0 this issue should be fixed.

**Comment by mirkarpude** [comment]
which version of webview_flutter I will use to solve this issue with 6.1.1
