### ISSUE TITLE
Experiments on introducing newer approach

### ISSUE THREAD

**Issue by sarbagyastha** [sarbagyastha/youtube_player_flutter#22]
The current approach is based on playing videos on top of webview, which is using PlatformViews ([Android](https://api.flutter.dev/flutter/widgets/AndroidView-class.html) & [iOS](https://api.flutter.dev/flutter/widgets/UiKitView-class.html)). And PlatformViews are known to have issues and are resource hungry too. (See [here](https://github.com/flutter/flutter/labels/a%3A%20platform-views) and [here](https://github.com/flutter/flutter/labels/p%3A%20webview)).

Some of the issues in current approach:
* Memory Intensive #21 
* Not working for iOS as expected(rarely  works in 3/4 builds) #2 
* Problem while resizing or refreshing screens.
* Couldn't adapt aspect ratios. #6 
* Crashes the app when rapidly navigating through screens. #8 

I intend to address all these issues with a new approach. If I succeed with this new approach then:
* Player will be lot more faster.
* Will have more controls over the player.
* Addresses all the issues listed above.
* Will also support Android KitKat devices (API Level 19).

So, I will be working on this from today and won't be replying to newer issues in this repo until something is decided regarding the newer approach.

Thank you for love and support folks. :heart: 
Your feedbacks will be appreciated.

**Comment by sumitgohil** [comment]
Sounds Great. Please make sure it's in a way that it does not violate YouTube terms.

**Comment by GeertJohan** [comment]
What technique will you be using to implement this? Can you share some details about how it will work?

**Comment by sarbagyastha** [comment]
Sorry but it did not work intended, was intending to draw the player on canvas and export the texture to flutter.
