### ISSUE TITLE
flutter_webview dependency issue

### ISSUE THREAD

**Issue by geoffroycochard** [sarbagyastha/youtube_player_flutter#220]
**Describe the bug**
If another package use flutter_webview as dependency, cause plugin configuration is loading twice.

**To Reproduce**
In a project, install flutter_html and youtube_player_flutter and see `android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java` call `flutterEngine.getPlugins().add(new io.flutter.plugins.webviewflutter.WebViewFlutterPlugin());`

**Comment by sarbagyastha** [comment]
The dependency is remove now.
