### ISSUE TITLE
Add Quality option

### ISSUE THREAD

**Issue by Khawlah-Mohammed** [sarbagyastha/youtube_player_flutter#223]
Add quality option to default Controls

**Comment by habeebrahman021** [comment]
Waiting for this feature.

**Comment by shaheemMPM** [comment]
My application very much depends on this package, so if you can add this feature it will be a good boost in UX of my application.

I've one more query regarding Quality.!

Does this plugin automatically change video quality according to internet strength as normal youtube players do??

**Comment by sarbagyastha** [comment]
@shaheemMPM  Yes the quality of video changes wrt to network bandwidth and screen sizes. But there's no way to change the quality manually.

**Comment by shaheemMPM** [comment]
> @shaheemMPM  Yes the quality of video changes wrt to network bandwidth and screen sizes. But there's no way to change the quality manually. 

Ok, Thanks.

**Comment by shaheemMPM** [comment]
@sarbagyastha are you planning to add this feature in near future?

**Comment by sarbagyastha** [comment]
@shaheemMPM The feature is not supported by iFrame Player API.

**Comment by shaheemMPM** [comment]
@sarbagyastha that's unfortunate, I asked since you reopened the thread

**Comment by sarbagyastha** [comment]
Duplicate of #83
