### ISSUE TITLE
[BUG] pub get not working

### ISSUE THREAD

**Issue by Oklahomawhore** [sarbagyastha/youtube_player_flutter#229]
**Describe the bug**
```
[ulu_platform_demo] flutter pub get
Running "flutter pub get" in ulu_platform_demo...               
Because ulu_platform_demo depends on youtube_player_flutter ^6.1.1 which doesn't match any versions, version solving failed.
pub get failed (1; Because ulu_platform_demo depends on youtube_player_flutter ^6.1.1 which doesn't match any versions, version solving failed.)
exit code 1
```

strangely ^6.1.0 works fine.

**Comment by Oklahomawhore** [comment]
`[   +1 ms] SLVR:   fact: no versions of youtube_player_flutter match ^6.1.1
[   +4 ms] SLVR:   conflict: no versions of youtube_player_flutter match ^6.1.1
[   +1 ms] SLVR:   ! youtube_player_flutter ^6.1.1 is satisfied by youtube_player_flutter ^6.1.1
[        ] SLVR:   ! which is caused by "ulu_platform_demo depends on youtube_player_flutter ^6.1.1"
[        ] SLVR:   ! thus: version solving failed
[   +4 ms] SLVR: Version solving took 0:00:00.309970 seconds.
[        ]     | Tried 1 solutions.`

**Comment by sarbagyastha** [comment]
Please try with v7.0.0
