### ISSUE TITLE
Unlisted Videos not playing

### ISSUE THREAD

**Issue by lzzy12** [sarbagyastha/youtube_player_flutter#23]
It keeps on loading forever. Unlisted videos don't need login for playing it, IDK why it doesn't work even then

**Comment by sarbagyastha** [comment]
Can you provide me the videoId?

**Comment by lzzy12** [comment]
@sarbagyastha UrunjftboH4

**Comment by sarbagyastha** [comment]
@lzzy12 , it's working fine in my case with Version 2.0.0. Please do check with new version.

**Comment by lzzy12** [comment]
@sarbagyastha Right. It works. IDK why it wasn't working before.
