### ISSUE TITLE
When tapped the title of the video, the search page appeared and the video loaded indefinitely in iOS version.

### ISSUE THREAD

**Issue by therezacuet** [sarbagyastha/youtube_player_flutter#231]
When we tapped the title of the video, the search page appeared and the video loaded indefinitely.

![attachment-12961399740199184317Screenshot-0522-183339](https://user-images.githubusercontent.com/16717497/82753664-1a282200-9de9-11ea-8249-be2bf6d9ae01.png)

**Technical Details:**
 - Device: iPad, 
 - OS:iOS 13.4.1

**Comment by shaheemMPM** [comment]
> When we tapped the title of the video, the search page appeared and the video loaded indefinitely.
> 
> ![attachment-12961399740199184317Screenshot-0522-183339](https://user-images.githubusercontent.com/16717497/82753664-1a282200-9de9-11ea-8249-be2bf6d9ae01.png)
> 
> **Technical Details:**
> 
> * Device: iPad,
> * OS:iOS 13.4.1

I'm using this plugin on my android device, but I'm planning to build the app for iOS soon.
I'm concerned about the issue you mentioned, can you please provide the screenshot of the error.

**Comment by sarbagyastha** [comment]
Should fix with v7.0.0, feel free to re-open.
