### ISSUE TITLE
Video Player Hangs at UNKNOWN State

### ISSUE THREAD

**Issue by DakotaSamuel** [sarbagyastha/youtube_player_flutter#24]
originally thought this was related to issue [#17](https://github.com/sarbagyastha/youtube_player_flutter/issues/17), but I am using version 2.0.0 and am still having this problem.

It seems that videos will randomly fail to load. The video player will never reach the QUED state. It just stays at the UNKNOWN state. 

The screenshot below from the demo app modified to display the player state shows this.

![scrnshot1](https://user-images.githubusercontent.com/23041481/58999896-5a9c2380-87c5-11e9-9fb6-a739470a4fad.png)

When I tap on the video, it shows the controls but pressing play does nothing.

![scrnshot2](https://user-images.githubusercontent.com/23041481/58999891-56700600-87c5-11e9-89d9-ef1bc7551be6.png)

Devices I've tested with:
- Samsung Galaxy S9: occurs about 15% of the time
- Samsung Galaxy S6: occurs about 10% of the time
- Simulated Nexus 10: occurs about 10% of the time

**Comment by Y-ndm** [comment]
Same issue here.. after updating from 1.1.1+1 to 2.0.0 the player will be stuck when I change the videoId.
Let me be clearer:
_First I have a String = "videoLink".. the video works as it is intended to be, but when I change the videoLink with a click of a button the Clip's Thumbnail shows up but the clip won't and the old clip keeps playing.. this is happening in both a real device and emulator. It seems like this issue show up only on 1.2.0 and above. 
Thanks.

**Comment by DakotaSamuel** [comment]
I poked around a bit, and it seems there is a problem with the WebViewController not getting set for the YoutubePlayerController and also an issue with not waiting for the player to be ready before playing/queueing the video. 

I moved some things around in youtube_player.dart and it seems to be working now.

in _Player Build():
```Dart
       onPageFinished: (_) {
          if (widget.controller.value.isFullScreen) {
            widget.controller._currentWebController = _temp;
          } else {
            widget.controller.value.webViewController.complete(_temp);
            //ADDED THIS /////////////////
            widget.controller.value.webViewController.future.then( (controller) {
              widget.controller._currentWebController = controller;
            });
            //////////////////////////////////
          }
          if (widget.forceHideAnnotation)
            widget.controller.forceHideAnnotation();
          if (widget.mute) widget.controller.mute();
        },
```
Also in _Player Build(), move the load/cue into the 'Ready' callback:
```Dart
JavascriptChannel(
            name: 'Ready',
            onMessageReceived: (JavascriptMessage message) {
              widget.controller.value = widget.controller.value.copyWith(isReady: true);
              //ADDED THIS /////////////////
              widget.autoPlay
                  ? widget.controller.load()
                  : widget.controller.cue();
              //////////////////////////////////
            },
          ),
```

@Y-ndm I don't think this helps much with your problem. It seems to be similar (YoutubePlayerController not getting updated). By changing the things above and adding the following at the top of _Player Build() you can get the video to play. Still looks like there are some issues though...
```Dart
if (_temp != null && widget.controller._currentWebController == null) {
      widget.controller._currentWebController = _temp;
    }
```

**Comment by sarbagyastha** [comment]
Checkout beta [**v3.0.0-beta.4**](https://pub.dev/packages/youtube_player_flutter/versions/3.0.0-beta.4).

**Comment by DakotaSamuel** [comment]
Thanks! That fixes the webViewController problem, but there is still an issue if it gets to the loading/queueing portion of the code before the player is ready. If I move the following up into the 'Ready' JavascriptChannel it works fine.
```Dart
widget.autoPlay
    ? widget.controller.load()
    : widget.controller.cue();
```

**Comment by sarbagyastha** [comment]
@DakotaSamuel, will test by moving it to Ready.
