### ISSUE TITLE
[BUG]Not proper Fullscreen on 7.0.0+2 and orientation changes

### ISSUE THREAD

**Issue by vipinnegi90** [sarbagyastha/youtube_player_flutter#243]
Made an app to run on portrait mode using this code : 
`SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(MyApp());
  });`

When I fullscreen the player it looks something like this:
[Fullscreen shot bug](https://i.imgur.com/AVMBnqi.jpg)

When I try exiting fullscreen with back button, the app is now locked in landscape orientation and neither rotates back to portrait on tilting device. Auto-rotate is turned-on in system settings.

**Expected behavior**
FullScreen should be exclusive and shouldn't override the app's orientation to change.

**Comment by faslurrajah** [comment]
did you solve this?
