### ISSUE TITLE
Exposing Separate FullScreen() method [FEATURE REQUEST]

### ISSUE THREAD

**Issue by vipinnegi90** [sarbagyastha/youtube_player_flutter#245]
Currently, we have a Widget for Full Screen ie. FullScreenButton(). But the button is non-customizable. How about having a separate method for eg. `_controller.FullScreen()`, that can be called from any widget's onPressed() or onTap() etc.

for eg. 
```
FlatButton(
  onPressed: () {
    _controller.FullScreen();
  },
  child: Text("Go to FullScreen", style: kMyTextStyle),
)
```

**Comment by sarbagyastha** [comment]
There's one already [toggleFullScreenMode](https://pub.dev/documentation/youtube_player_flutter/latest/youtube_player_flutter/YoutubePlayerController/toggleFullScreenMode.html]

**Comment by vipinnegi90** [comment]
Nice, it works! I think you should mention all these exposed functions in the main description.
