### ISSUE TITLE
No implementation found for method evaluateJavascript on channel plugins.flutter.io/webview_6

### ISSUE THREAD

**Issue by Mishanya840** [sarbagyastha/youtube_player_flutter#25]
> E/flutter ( 4383): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel plugins.flutter.io/webview_6)
E/flutter ( 4383): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter ( 4383): <asynchronous suspension>
E/flutter ( 4383): #1      MethodChannelWebViewPlatform.evaluateJavascript (package:ytview/src/webview_method_channel.dart:90:21)
E/flutter ( 4383): #2      WebViewController.evaluateJavascript (package:ytview/ytview.dart:579:39)
E/flutter ( 4383): #3      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:608:30)
E/flutter ( 4383): #4      YoutubePlayerController.forceHideAnnotation (package:youtube_player_flutter/src/youtube_player.dart:612:33)
E/flutter ( 4383): #5      __PlayerState.build.<anonymous closure> (package:youtube_player_flutter/src/youtube_player.dart:486:31)
E/flutter ( 4383): #6      _PlatformCallbacksHandler.onPageFinished (package:ytview/ytview.dart:406:15)
E/flutter ( 4383): #7      MethodChannelWebViewPlatform._onMethodCall (package:ytview/src/webview_method_channel.dart:39:35)
E/flutter ( 4383): <asynchronous suspension>
E/flutter ( 4383): #8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:383:55)
E/flutter ( 4383): <asynchronous suspension>
E/flutter ( 4383): #9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:351:54)
E/flutter ( 4383): #10     BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:76:33)
E/flutter ( 4383): <asynchronous suspension>
E/flutter ( 4383): #11     _invoke3.<anonymous closure> (dart:ui/hooks.dart:263:15)
E/flutter ( 4383): #12     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 4383): #13     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 4383): #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 4383): #15     _invoke3 (dart:ui/hooks.dart:262:10)
E/flutter ( 4383): #16     _dispatchPlatformMessage (dart:ui/hooks.dart:136:5)
E/flutter ( 4383):

**Comment by sarbagyastha** [comment]
@Mishanya840 could you please provide more detail about the issue ?

**Comment by Mishanya840** [comment]
I made a mistake and gave the wrong context. Sorry

**Comment by sanyamjain65** [comment]
@Mishanya840 I am facing the same issue.....could you please elaborate how you solved this issue?

**Comment by jimmyff** [comment]
I have the same issue when hitting back on full screen I get:
```
flutter (27594): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel plugins.flutter.io/webview_3)
E/flutter (27594): #0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:154
E/flutter (27594): <asynchronous suspension>
E/flutter (27594): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:329
E/flutter (27594): #2      MethodChannelWebViewPlatform.evaluateJavascript 
package:webview_media/src/webview_method_channel.dart:113
E/flutter (27594): #3      WebViewController.evaluateJavascript 
package:webview_media/webview_flutter.dart:684
E/flutter (27594): #4      YoutubePlayerController._callMethod 
package:youtube_player_flutter/…/utils/youtube_player_controller.dart:178
E/flutter (27594): #5      YoutubePlayerController.play 
package:youtube_player_flutter/…/utils/youtube_player_controller.dart:189
E/flutter (27594): #6      YoutubePlayerController.seekTo 
package:youtube_player_flutter/…/utils/youtube_player_controller.dart:246
E/flutter (27594): #7      _YoutubePlayerState.listener 
package:youtube_player_flutter/…/player/youtube_player.dart:265
```

This is the coming from `value.webViewController?.evaluateJavascript(methodString);` in `_callMethod(...)`

**Comment by Codiyampa** [comment]
I am also facing this issue.

Did you already find a solution? @jimmyff @sanyamjain65

**Comment by Salman-Official** [comment]
Getting the same error. how to fix this?

**Comment by pranavkpr1** [comment]
@jimmyff I am also getting the same error on hitting exit full screen, have you found any solution to the problem. Exception is being caused in this code on exiting full screen. value.webViewController?.evaluateJavascript(source: methodString);
Any help would be appreciated :)
