### ISSUE TITLE
Documentation bug: is minSdkVersion 17 or 20?

### ISSUE THREAD

**Issue by jamesncl** [sarbagyastha/youtube_player_flutter#250]
In the [requirements section of the documentation](https://pub.dev/packages/youtube_player_flutter#requirements) it states:

> Android: minSdkVersion 17

But in the [limitation section of the documentation](https://pub.dev/packages/youtube_player_flutter#limitation) it states:

> Since the plugin is based on platform views. This plugin requires Android API level 20 or greater.

Which is correct?

Thanks :)

**Comment by sarbagyastha** [comment]
@jamesncl Setting **minSdkVersion = 17** is a hard requirement i.e. You won't be able to build your project without setting it to 17+. 

While requirement of API 20 is optional. Your project will build for any versions but the YoutubePlayer won't be functional on <20.

**Comment by jamesncl** [comment]
Thanks @sarbagyastha. If you could add your above answer to the documentation that would help others with the same question

**Comment by sarbagyastha** [comment]
Sure @jamesncl
