### ISSUE TITLE
flutter_inappwebview-Swift.h not found

### ISSUE THREAD

**Issue by MrMeeple** [sarbagyastha/youtube_player_flutter#255]
Plugin works fine in Android. iOS won't build due to 

'flutter_inappwebview/flutter_inappwebview-Swift.h' file not found

Im not very experienced with Xcode, but it is Xcode 11.3

I have tried deleting
pubspec.lock
Podfile.lock
/ios pod install
flutter clean

with no impact.

in the Changelog it makes mention of --ios-language swift, but i don't know what this really means or how I would verify this setting.

Thoughts?

#UPDATE
Attempting a build using use_frameworks! in gradle seems to have an impact but is not consistent.
So if I,
--Build with use_frameworks! - Build fails due to Facebook Login plugin
--Build without use_frameworks! - Build succeeds and video plays well
--Build again without use_frameworks! - Build fails with original error.

Process can be repeated. I don't really understand what use_frameworks! does or why attempting a build with it makes an impact.

**Comment by MrMeeple** [comment]
Issue has been resolved as of this moment.

I added use_frameworks! to my Podfile, which caused other packages to break (looking at you Facebook Login), after which I removed that line, reran my build for giggles and it now is working.

I'm not sure what difference that failing build made.

**Comment by MrMeeple** [comment]
Issue persists after second build. So if I,
--Build with use_frameworks! - Build fails due to Facebook Login plugin
--Build without use_frameworks! - Build succeeds and video plays well
--Build again without use_frameworks! - Build fails with original error.

**Comment by Abdelazeem777** [comment]
I am facing the same issue with flutter v1.22.6 and youtube_player_flutter v7.0.0+7.
