### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by alihimad** [sarbagyastha/youtube_player_flutter#264]
**Describe the bug**
----------------------------------------------------------------------------------------
I have added the plugin in flutter application and tried to run the example posted with plugin; this issue found in console of VS Code.
The player loaded but didn't play any video; i have tried this on physical device HUAWEI Y6 Pro.

**_java.lang.NullPointerException: Attempt to invoke virtual method 'int 
android.graphics.Bitmap.getWidth()' on a null object reference_**

**To Reproduce**
----------------------------------------------------------------------------------------
1- Add the latest plugin to flutter project 
youtube_player_flutter: 7.0.0+3

2- Copy and paste the example posted with plugin in new file

3- in the app-> build.gradle, set  
minSdkVersion 20
 targetSdkVersion 28

4- Run the project

**Technical Details:**
----------------------------------------------------------------------------------------
 - Device: Huawei Y6 Pro
 - OS: Android 5.1
- Plugin version: youtube_player_flutter: 7.0.0+3
 - Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (2 weeks ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Additional context**
Logs from console
----------------------------------------------------------------------------------------
I/BufferQueue( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:0,p:-1,c:-1) BufferQueue core=(5653:com.example.school_buzzer_mobile)
I/BufferQueueConsumer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:0,p:-1,c:5653) connect(C): consumer=(5653:com.example.school_buzzer_mobile) controlledByApp=true
I/BufferQueueConsumer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:0,p:-1,c:5653) setConsumerName: unnamed-5653-0
I/GLConsumer( 5653): [unnamed-5653-0] detachFromContext
I/BufferQueueConsumer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:0,p:-1,c:5653) setDefaultBufferSize: width=720 height=405
I/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) connect(P): api=1 producer=(251:/system/bin/surfaceflinger) producerControlledByApp=false
I/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) new GraphicBuffer needed
D/GraphicBuffer( 5653): register, handle(0x7f5a81fde0) (w:720 h:405 s:720 f:0x22 u:0x000900)
D/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) cancelBuffer: slot 0
D/libc-netbsd( 5653): [getaddrinfo]: hostname=i3.ytimg.com; servname=(null); cache_mode=(null), netid=0; mark=0
D/libc-netbsd( 5653): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
D/libc-netbsd( 5653): getaddrinfo: i3.ytimg.com get result from proxy >>
W/chromium( 5653): [WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
W/art     ( 5653): Attempt to remove local handle scope entry from IRT, ignoring
W/chromium( 5653): [WARNING:password_handler.cc(27)] create-->contents = 0x0000007f638d9400, delegate = 0x0000007f5b75ccc0
W/chromium( 5653): [WARNING:password_handler.cc(35)] attaching to web_contents
W/AwContents( 5653): onDetachedFromWindow called when already detached. Ignoring
W/art     ( 5653): Attempt to remove local handle scope entry from IRT, ignoring
W/art     ( 5653): Attempt to remove local handle scope entry from IRT, ignoring
W/WebView ( 5653): setLayerType()
D/ViewRootImpl( 5653): hardware acceleration is enabled, this = ViewRoot{3565bbf7 com.example.school_buzzer_mobile/com.example.school_buzzer_mobile.MainActivity,ident = 1}
I/chromium( 5653): [INFO:sys_info_android.cc(230)] [SysInfo::GetCurrentProcessName] [com.example.school_buzzer_mobile]
D/OpenGLRenderer( 5653): CanvasContext() 0x7f79e6be80 initialize 0x7f58779810
D/Surface ( 5653): Surface::connect(this=0x7f58779800,api=1)
D/mali_winsys( 5653): new_window_surface returns 0x3000
D/Surface ( 5653): Surface::allocateBuffers(this=0x7f58779800)
D/GraphicBuffer( 5653): register, handle(0x7f5fdba600) (w:720 h:405 s:720 f:0x1 u:0x000b00)
D/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) cancelBuffer: slot 0
E/MPlugin ( 5653): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: video/3gpp
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/3gpp
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: video/3gpp2
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: video/avi
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: video/mpeg
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/mpeg
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: video/x-m4v
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/aac
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/aac-adts
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/x-mpeg
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/flac
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/amr
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/amr-wb
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/quicktime
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/vorbis
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: video/quicktime
I/chromium( 5653): [INFO:mime_util.cc(703)] insert media type: audio/quicktime
I/GLConsumer( 5653): [unnamed-5653-0] attachToContext
W/chromium( 5653): [WARNING:simple_index_file.cc(337)] Could not map Simple Index file.
D/libc-netbsd( 5653): [getaddrinfo]: hostname=www.youtube.com; servname=(null); cache_mode=(null), netid=0; mark=0
D/libc-netbsd( 5653): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=2
D/libc-netbsd( 5653): getaddrinfo: www.youtube.com get result from proxy >>
I/chromium( 5653): [INFO:raster_worker_pool.cc(220)] [RasterWorkerCoordinator] enable=[0]
D/GraphicBuffer( 5653): register, handle(0x7f5b554f20) (w:720 h:405 s:720 f:0x1 u:0x000b00)
D/GraphicBuffer( 5653): register, handle(0x7f55153fc0) (w:720 h:405 s:720 f:0x1 u:0x000b00)
I/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) new GraphicBuffer needed
D/GraphicBuffer( 5653): register, handle(0x7f55154e20) (w:720 h:405 s:720 f:0x22 u:0x000900)
I/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) new GraphicBuffer needed
D/GraphicBuffer( 5653): register, handle(0x7f55154ec0) (w:720 h:405 s:720 f:0x22 u:0x000900)
I/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) queueBuffer: slot 2 is dropped, handle=0x7f55154ec0
D/OpenSSLLib( 5653): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
D/OpenSSLLib( 5653): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
D/libc-netbsd( 5653): [getaddrinfo]: hostname=s.ytimg.com; servname=(null); cache_mode=(null), netid=0; mark=0
D/libc-netbsd( 5653): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=2
D/libc-netbsd( 5653): getaddrinfo: s.ytimg.com get result from proxy >>
I/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) queueBuffer: fps=3.48 dur=1148.72 max=767.75 min=13.91
D/OpenSSLLib( 5653): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
D/OpenSSLLib( 5653): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
I/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) queueBuffer: slot 0 is dropped, handle=0x7f5a81fde0
I/BufferQueueProducer( 5653): [unnamed-5653-0](this:0x7f5b447000,id:0,api:1,p:251,c:5653) queueBuffer: fps=14.57 dur=1235.51 max=619.40 min=12.64
D/libc-netbsd( 5653): [getaddrinfo]: hostname=googleads.g.doubleclick.net; servname=(null); cache_mode=(null), netid=0; mark=0
D/libc-netbsd( 5653): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=2
D/libc-netbsd( 5653): getaddrinfo: googleads.g.doubleclick.net get result from proxy >>
D/libc-netbsd( 5653): [getaddrinfo]: hostname=static.doubleclick.net; servname=(null); cache_mode=(null), netid=0; mark=0
D/libc-netbsd( 5653): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=2
D/libc-netbsd( 5653): getaddrinfo: static.doubleclick.net get result from proxy >>
D/OpenSSLLib( 5653): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
D/OpenSSLLib( 5653): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
D/OpenSSLLib( 5653): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
D/OpenSSLLib( 5653): OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
D/libc-netbsd( 5653): [getaddrinfo]: hostname=yt3.ggpht.com; servname=(null); cache_mode=(null), netid=0; mark=0
D/libc-netbsd( 5653): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=2
D/libc-netbsd( 5653): [getaddrinfo]: hostname=i.ytimg.com; servname=(null); cache_mode=(null), netid=0; mark=0
D/libc-netbsd( 5653): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=2
W/ResourceType( 5653): No known package when getting value for resource number 0x03020008
W/chromium( 5653): [WARNING:aw_network_delegate.cc(92)] load url fail#-3#1
D/AndroidRuntime( 5653): Shutting down VM
E/AndroidRuntime( 5653): FATAL EXCEPTION: main
E/AndroidRuntime( 5653): Process: com.example.school_buzzer_mobile, PID: 5653
E/AndroidRuntime( 5653): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime( 5653): 	at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1140)
E/AndroidRuntime( 5653): 	at com.android.org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
E/AndroidRuntime( 5653): 	at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime( 5653): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime( 5653): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 5653): 	at android.app.ActivityThread.main(ActivityThread.java:5667)
E/AndroidRuntime( 5653): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5653): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5653): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
E/AndroidRuntime( 5653): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
D/libc-netbsd( 5653): getaddrinfo: yt3.ggpht.com get result from proxy >>
D/libc-netbsd( 5653): getaddrinfo: i.ytimg.com get result from proxy >>
I/Process ( 5653): Sending signal. PID: 5653 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by akhileshgehlot** [comment]
Facing the same issue... I even updated to the latest dependency 7.0.0+7.

**Comment by akhileshgehlot** [comment]
Any suggestion how to solve it??

**Comment by zjamshidi** [comment]
I'm facing the same crash on Huawei P8

**Comment by zhanghaigang666** [comment]
me too +1

**Comment by taido98** [comment]
me too.
Solution ??? Why closed? I want to solution

**Comment by zjamshidi** [comment]
It's only happening on Android 5. I just increased the minSDK to 23 as a workaround.
