### ISSUE TITLE
Compiler issues with versions 7.0.0+2 to 7.0.0+5[BUG]

### ISSUE THREAD

**Issue by ssbaval** [sarbagyastha/youtube_player_flutter#267]
**Describe the bug**
Cannot compile the plugin on Android when using Plugin version 7.0.0+2 through to latest version

I get the following error:
```

Compiler message:
../../../.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-7.0.0+5/lib/src/player/youtube_player.dart:427:11: Error: No named parameter with the name 'errorBuilder'.
          errorBuilder: (context, _, __) => Container(),
```

I do not get the error with version **7.0.0+1**

**To Reproduce**

Just use the plugin and ensure the version is 7.0.0+2 or higher

**Expected behavior**

Would be great if latest version of the plugin compiles in Android
 

**Technical Details:**
 - Device: Android Simulator Nexus 5X API 28
 - OS: Android
 - Version Build gradle has minimum SDK at 21

**Comment by sarbagyastha** [comment]
@ssbaval What's your flutter version? Seems like you're using older version of flutter.

**Comment by ssbaval** [comment]
Flutter 1.12.13+hotfix 5

**Comment by alexda12** [comment]
I'm hitting this error also - I cannot upgrade to the latest version , my error is : 

```

Compiler message:


../../../.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-7.0.0+6/lib/src/player/youtube_player.dart:429:11: Error: No named parameter with the name 'errorBuilder'.
          errorBuilder: (context, _, __) => Container(),
          ^^^^^^^^^^^^


../../sdk/flutter/packages/flutter/lib/src/widgets/image.dart:332:3: Context: Found this candidate, but the arguments don't match.
  Image.network(
```

**Comment by sallypeters** [comment]
See #272

**Comment by sarbagyastha** [comment]
Please update your flutter version to 1.17.x ... `errorBuilder` for Image class weren't there in 1.12.x

**Comment by MsXam** [comment]
@sallypeters @ssbaval @alexda12 
This is an issue within your version of Flutter. @sarbagyastha references Image.network(..) which has the **errorBuilder** parameter. If you cant directly upgrade Flutter from your initial version (because of issues  you may have) - then consider upgrading Dart.

Latest Version (shown below) contains the **errorBuilder** which is the issue you are having 
```

Image.network(
    String src, {
    Key key,
    double scale = 1.0,
    this.frameBuilder,
    this.loadingBuilder,
    this.errorBuilder,
    this.semanticLabel,
    this.excludeFromSemantics = false,
    this.width,
    this.height,
    this.color,
    this.colorBlendMode,
    this.fit,
    this.alignment = Alignment.center,
    this.repeat = ImageRepeat.noRepeat,
    this.centerSlice,
    this.matchTextDirection = false,
    this.gaplessPlayback = false,
    this.filterQuality = FilterQuality.low,
    this.isAntiAlias = false,
    Map<String, String> headers,
    int cacheWidth,
    int cacheHeight,
  }) : image = ResizeImage.resizeIfNeeded(cacheWidth, cacheHeight, NetworkImage(src, scale: scale, headers: headers)),
       assert(alignment != null),
       assert(repeat != null),
       assert(matchTextDirection != null),
       assert(cacheWidth == null || cacheWidth > 0),
       assert(cacheHeight == null || cacheHeight > 0),
       assert(isAntiAlias != null),
       super(key: key);
```
