### ISSUE TITLE
Endless loading on devices with less than 5 inch screen size

### ISSUE THREAD

**Issue by itssidhere** [sarbagyastha/youtube_player_flutter#269]
I can't play the video in nexus 4 and several other devices with similar screen sizes,I don't know if it's my widget tree specific but widget tree looks like this. 

Stack
 - CHILD
 - Safe Area
  --  Column
     --- YoutubePlayer
     --- Expanded
     --- And so on

**Comment by sarbagyastha** [comment]
@itssidhere Is Android API >= 20 for those devices ?

**Comment by itssidhere** [comment]
@sarbagyastha Yes

**Comment by itssidhere** [comment]
This is happening after 6.1.1

**Comment by sarbagyastha** [comment]
Please try with https://pub.dev/packages/youtube_player_iframe
