### ISSUE TITLE
Support for hiding the thumbnail and changing the video quality

### ISSUE THREAD

**Issue by KerianFiter** [sarbagyastha/youtube_player_flutter#27]
Hi,
I'm using the version 3.0.0-beta.4 I'd like to know if it was possible to prevent the plugin from loading the thumbnail and to change the video quality on the fly.
Thank you !

**Comment by sarbagyastha** [comment]
@KerianFiter, There is currently no way to change video quality in Iframe API.

**Comment by KerianFiter** [comment]
@sarbagyastha, isn't it possible to change it with player.setPlaybackQuality as mentionned [here](https://developers.google.com/youtube/iframe_api_reference#setPlaybackQuality)?

**Comment by sarbagyastha** [comment]
No it's not possible. It's broken since 2011 AD.

**Comment by KerianFiter** [comment]
Okay thanks for the answer. And for the thumbnail I managed to modify a bit the code at the 266th line of youtube_player.dart to get it working.

**Comment by adrianvintu** [comment]
> Okay thanks for the answer. And for the thumbnail I managed to modify a bit the code at the 266th line of youtube_player.dart to get it working.

@KerianFiter Can you publish the changes? Will they be in the new version?

**Comment by KerianFiter** [comment]
@adrianvintu What I can do is paste the code here so you can use it. But because the code is not clean I don't think it will be in the next version unless @sarbagyastha implements this new functionnality.

Here is the code, in youtube_player.dart, in _buildPlayer:
```dart
          if (!controller.value.hasPlayed)
            // ! Modified to prevent the thumbnail from loading
/*             Image.network(
              widget.thumbnailUrl ??
                  YoutubePlayer.getThumbnail(videoId: controller.initialSource),
              fit: BoxFit.cover,
            ), */
            // Shows a black Container instead of the thumbnail
            Container(
              color: Colors.black,
            ),
```
