### ISSUE TITLE
[BUG] ASN1OutOfBufferError when attempting to play any video

### ISSUE THREAD

**Issue by jasonpaluck** [sarbagyastha/youtube_player_flutter#270]
Every attempt to include the player in an existing flutter project, using code either from this project's documentation pages or directly from the example app, generates an exception `ASN1OutOfBufferError` in file `ans1_decoder.dart`, and then `FormatException (FormatException: Bad UTF-8 encoding 0x97 (at offset 0))` from the flutter_inappwebview-3.4.0+1 package. There are no build warnings or errors, only an exception thrown as the video begins to load and the loading indicator perpetually spins against the initial video frame using any iOS simulator.

I'm using youtube_player_flutter: ^7.0.0+6 and flutter 1.17.4.

** UPDATE: If I F5 to continue through the errors several times the video ultimately plays. 

Anyone else have such an issue?

Thanks!

**Comment by sarbagyastha** [comment]
@jasonpaluck Have you followed thes note ?https://pub.dev/packages/flutter_inappwebview#important-note-for-ios

**Comment by jasonpaluck** [comment]
I did, yes. Had I not, I would have received a build error which I do not. The only way it works is if I run without debugging in VS Code. If I allow it to debug, I'll get a dozen or so errors I need to step through before the video will play.

**Comment by jasonpaluck** [comment]
Looks like I was missing one line from the Podfile:

`config.build_settings['SWIFT_VERSION'] = '5.0'`

Interestingly enough, there were no build warnings or errors as the documentation said there would be, so the solution wasn't obvious. Thanks for your time, hope this can help someone in the future.
