### ISSUE TITLE
[BUG] _TypeError was thrown building YoutubePlayerBuilder 

### ISSUE THREAD

**Issue by lalbuquerque** [sarbagyastha/youtube_player_flutter#271]
**Describe the bug**

I'm trying to use the full screen video feature like that:

```dart
      YoutubePlayerBuilder(
        player: YoutubePlayer(
          controller: _getController(slides[0].uri),
          showVideoProgressIndicator: true,
          progressIndicatorColor: Colors.amber,
          progressColors: ProgressBarColors(
            playedColor: Colors.amber,
            handleColor: Colors.amberAccent,
          ),
        ),
        builder: (context, player) {
          return Scaffold(
            appBar: CustomAppBar(title: "my title"),
            body: RefreshIndicator(
              onRefresh: () {
                bloc.add(
                  Refresh(),
                );
                return _refreshCompleter.future;
              },
              child: _buildWidgetList(slides, player),
            ),
          );
        },
      )
```

And I'm receiving this error: 
```
The following _TypeError was thrown building YoutubePlayerBuilder(dirty, state: _YoutubePlayerBuilderState#445a8)
type 'Container' is not a subtype of type 'YoutubePlayer'
```

with the trace `_YoutubePlayerBuilderState.build(package:youtube_player_flutter/src/widgets/youtube_player_builder.dart:81:33)`

Which leads to the following part of `YoutubePlayerBuilder`:
```dart
    final _player = Container(
      key: playerKey,
      child: WillPopScope(
        onWillPop: () async {
          final controller = widget.player.controller;
          if (controller.value.isFullScreen) {
            widget.player.controller.toggleFullScreenMode();
            return false;
          }
          return true;
        },
        child: widget.player,
      ),
    );
    final child = widget.builder(context, _player);
```

**To Reproduce**
Wrap your `Scaffold` with `YoutubePlayerBuilder`

**Expected behavior**
Show up the layout without crashing

**Technical Details:**
 - Device: Pixel 2
 - OS: API 29
 - Version: the error occurs in both ^7.0.0+3 and ^7.0.0+6 versions

**Comment by sarbagyastha** [comment]
Whats the type for second argument in your `_buildWidgetList` ?

**Comment by lalbuquerque** [comment]
> Whats the type for second argument in your `_buildWidgetList` ?

@sarbagyastha it's `YoutubePlayer`

**Comment by sarbagyastha** [comment]
It should be `Widget`.

**Comment by lalbuquerque** [comment]
@sarbagyastha so the builder doesn't deliver a `YoutubePlayer` at all or I just have to do a explicit cast on `player`?

**Comment by sarbagyastha** [comment]
Yes the builder delivers widget instead. https://pub.dev/documentation/youtube_player_flutter/latest/youtube_player_flutter/YoutubePlayerBuilder/builder.html

**Comment by lalbuquerque** [comment]
Ok @sarbagyastha I get it. 

I just think the builder parameter `player` having the same name as the argument that receives a `YoutubePlayer` instance may be a little bit confusing. Maybe if its name was `playerWidget` it would be a little better.
