### ISSUE TITLE
Block seek ahead

### ISSUE THREAD

**Issue by jasonpaluck** [sarbagyastha/youtube_player_flutter#273]
Is there any way to block the ability to seek forward/ahead with the progress bar? Ideally what I'd like to do is display the progress bar in the bottomActions but only allow seek backwards. If that isn't possible, is there any way to just show the progressBar widget as read only (no ability to seek in either direction)?

Thanks!

**Comment by sarbagyastha** [comment]
@jasonpaluck You'll have to create custom controls for that.
