### ISSUE TITLE
How to keep play video while changing fullscreen or portrait

### ISSUE THREAD

**Issue by nrbn** [sarbagyastha/youtube_player_flutter#275]
When i press fullscreen while video is playing, video is paused. Any eventlistener for when fullscreenbutton pressed? How to keep play video while changing fullscreen or portrait?

**Comment by nrbn** [comment]
![image](https://user-images.githubusercontent.com/10879727/85876158-9a211d80-b7d5-11ea-9275-2ba6f92d3426.png)

I have tried this, onenterfullscreen, but it does not work.

**Comment by dwikyhardi** [comment]
@sarbagyastha any advice for this problem??

**Comment by sarbagyastha** [comment]
Duplicate of #50
