### ISSUE TITLE
FlutterWebView.m:412:1: error: control may reach end of non-void function [-Werror,-Wreturn-type] when running on iOS

### ISSUE THREAD

**Issue by lucasagazzani** [sarbagyastha/youtube_player_flutter#276]
I tried to run my flutter app on my iPad or the simulator and I get this error related with the webview_media package. anyone has an idea how to fix this?
this is the error I got while running
![Screenshot 2020-06-24 at 13 49 41](https://user-images.githubusercontent.com/44684831/85927191-64933780-b89c-11ea-995c-2fb50918f751.png)

**Comment by sarbagyastha** [comment]
Please update to latest version of the plugin.

**Comment by lucasagazzani** [comment]
It is updated but still having the same error

**Comment by lucasagazzani** [comment]
Here is another screenshot of the error on Xcode that might help.

![Screenshot 2020-07-14 at 19 01 15](https://user-images.githubusercontent.com/44684831/87460568-f91fc880-c604-11ea-8cc2-6293a3d5dffa.png)
