### ISSUE TITLE
v7 - back to exit fullscreen

### ISSUE THREAD

**Issue by jimmyff** [sarbagyastha/youtube_player_flutter#277]
In version 7 you're no longer pushing to the navigator so when a user hits back in fullscreen mode expecting it to close full screen mode, it does not close fullscreen, it actually goes navigates back in the app behind the fullscreen video. If they are on the app route then it closes the app!

Is this expected behavior? If so this is the very bad design. Every main video service & app have consistent behavior for fullscreen video: back = close fullscreen.

Hopefully I'm mistaken but I'm forced to stick with version 6 until this is resolved.

**Comment by sarbagyastha** [comment]
Could you please try the example app ?

**Comment by jimmyff** [comment]
If anyone finds this issue the future and has the same issue, look at the iframe_youtube_player package by the same author, it solves my problem
