### ISSUE TITLE
How can I close the advertisement on Youtube Player?

### ISSUE THREAD

**Issue by hannibal1296** [sarbagyastha/youtube_player_flutter#279]
Hi, I'm developing an app playing youtube video clip.
I want to close the advertisement but I can't because the playback button shows up. Is there anyway that I can do?

Thank you in advance!

**Comment by sarbagyastha** [comment]
You should be using [youtube_player_iframe](https://pub.dev/packages/youtube_player_iframe) on that case.

**Comment by hannibal1296** [comment]
> You should be using [youtube_player_iframe](https://pub.dev/packages/youtube_player_iframe) on that case.

Thank you for the reply!
