### ISSUE TITLE
Failed to build error with webview_media and FlutterWebView[BUG]

### ISSUE THREAD

**Issue by lucasagazzani** [sarbagyastha/youtube_player_flutter#282]
I tried to run my app in iOS and this is the error I get. 

Developer/flutter/.pub-cache/hosted/pub.dartlang.org/webview_media-0.1.2/ios/Classes/FlutterWebView.m:412:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
    }

Please help me!

**Comment by lucasagazzani** [comment]
Here is the error from Xcode

![Screenshot 2020-07-07 at 13 51 39](https://user-images.githubusercontent.com/44684831/86784371-55a94380-c059-11ea-8e55-aceb39a2878a.png)

**Comment by sarbagyastha** [comment]
Seems like you're using older version of the plugin. Please update.

**Comment by lucasagazzani** [comment]
The plugin is updated and this and still have the error but this is what it says now

![Screenshot 2020-07-14 at 19 01 15](https://user-images.githubusercontent.com/44684831/87460754-400dbe00-c605-11ea-847c-48a43ae99249.png)

**Comment by lucasagazzani** [comment]
Is there any news @sarbagyastha , I have checked for updates but the problem is still there?

**Comment by sarbagyastha** [comment]
This plugin doesn't depend upon `webview_media` anymore. So you must have been using older version of the plugin.
