### ISSUE TITLE
does not work with flutter_inappwebview: ^4.0.0+4

### ISSUE THREAD

**Issue by av153k** [sarbagyastha/youtube_player_flutter#284]
**Describe the bug**
Hi, there, I made an app using this plugin and the app also used flutter_inappwebview. Today I tried to deploy that app for web, so I had to upgrade flutter_inappwebview to version `^4.0.0+4`. But this plugin requires flutter_inappwebview `>= 3.4.0 <3.5.0`. And So I couldn't upgrade the pub and neither could compile my app to the web. Can you look into it, please? Thanks 

**To Reproduce**
try adding these packages in pubspec.yaml
`youtube_player_flutter: ^7.0.0+6`
`flutter_inappwebview: ^4.0.0+4`

after that:
`flutter pub get`
  

**Expected behavior**
You will get this error:
`Because youtube_player_flutter 7.0.0+6 depends on flutter_inappwebview >=3.4.0 <3.5.0 and no versions of youtube_player_flutter match >7.0.0+6 <8.0.0, youtube_player_flutter ^7.0.0+6 requires flutter_inappwebview >=3.4.0 <3.5.0.

So, because apod_app depends on both youtube_player_flutter ^7.0.0+6 and flutter_inappwebview ^4.0.0+4, version solving failed.
pub get failed (1; So, because apod_app depends on both youtube_player_flutter ^7.0.0+6 and flutter_inappwebview ^4.0.0+4, version solving failed.)
exit code 1`

**Technical Details:**
 - Device: chrome(web-javascript)
 - OS: windows 10
 - Version `^7.0.0+6`

**Comment by sarbagyastha** [comment]
Updated the version constraint. And it should work now.
