### ISSUE TITLE
No Youtube Ads coming 

### ISSUE THREAD

**Issue by aamirzaidi** [sarbagyastha/youtube_player_flutter#285]
No ads come from youtube ever when we run it in android. Am i missing some way to enable them. I am worried if no ads come from youtube, app might be considered illegal or the owner of video may not like it and report it.
Please help.

**Comment by ZdenekKrcal** [comment]
> No ads come from youtube ever when we run it in android. Am i missing some way to enable them. I am worried if no ads come from youtube, app might be considered illegal or the owner of video may not like it and report it.
> Please help.

For me no ads is great solution. :-)

**Comment by sarbagyastha** [comment]
Duplicate of #117
