### ISSUE TITLE
How to play video with the specific start and end time?

### ISSUE THREAD

**Issue by tuanbs** [sarbagyastha/youtube_player_flutter#288]
How to play video with the specific start and end time?

My temporary solution is to use the listener to check if the currentTime reaches the specific endTime. But I think using the listener is not good for the app's performance. My improvement is to add and remove listener when playing and pausing the video. But this approach leads to some duplicated add/ remove listener codes. It's better if we can have sth like `youtubePlayerController.playSpecificTime(startTime: <specific_startTime>, endTime: <specific_endTime>)`.  Thanks.

**Comment by sarbagyastha** [comment]
You can use [load](https://pub.dev/documentation/youtube_player_flutter/latest/youtube_player_flutter/YoutubePlayerController/load.html)
