### ISSUE TITLE
Fullscreen on Orientation Change to Landscape

### ISSUE THREAD

**Issue by SandyAra** [sarbagyastha/youtube_player_flutter#3]

**Comment by secretwpn** [comment]
Not sure what is meant by this issue but the one I have could be related - fullscreen button changes orientation to landscape, and then no video is visible (though there is sound) and controls don't work - so there is no easy way to exit the fullscreen mode

**Comment by sarbagyastha** [comment]
Checkout beta [**v3.0.0-beta.3**](https://pub.dev/packages/youtube_player_flutter/versions/3.0.0-beta.3).
