### ISSUE TITLE
Not working in released[BUG]

### ISSUE THREAD

**Issue by Amanullahgit** [sarbagyastha/youtube_player_flutter#310]
**Describe the bug**
videos are not shown after app released

android version

**Comment by sarbagyastha** [comment]
Make sure you've added internet permissions for release manifest.

**Comment by Amanullahgit** [comment]
I have added internet permission, also i rechecked the whole code multiple times. But still no video is shown

**Comment by Amanullahgit** [comment]
is it fixed ?

**Comment by fakabbir** [comment]
strange, I only see grey, square boxes o the first page (about 5 X 3, and the 6th row not scroll-able and only 10% visible).
I don't see that working, Could only suggest to see, if only adding one video works (wth a url hardcoded) and you have added the controller correctly.

**Comment by Elnyoto** [comment]
Exact same problem here :-(

**Comment by diogolm1** [comment]
I faced this problem.
In debug mode, worked fine, in release mode a grey box appear.

But I found the error. In debug mode, i look in debug console and i found a exception "Incorrect use of ParentDataWidget.".

After some adjusts in my expanded widgets to make the exception in debug console disappear I look in release mode and the player worked fine.

**Comment by Amanullahgit** [comment]
Fixed Now
