### ISSUE TITLE
Playing -> fullscreen > small screen -> Pause 

### ISSUE THREAD

**Issue by adrianvintu** [sarbagyastha/youtube_player_flutter#32]
I have this scenario, even using your example (only tested on Android):

1. Play video in small/usual size
2. Press fullscreen icon
3. Video now plays in fullscreen
4. Press back button to go to small/usual screen
5. On small/usual screen the status says: BUFFERING and then PAUSED.

Expected behavior:
5. On small/usual screen the status says: BUFFERING and then **_PLAYING_**.

In other words, resume playing after fullscreen, do not pause when coming back from fullscreen.

**Comment by sarbagyastha** [comment]
Checkout version **3.0.0**. It should fix the issue.
