### ISSUE TITLE
Version 3 unusable

### ISSUE THREAD

**Issue by adrianvintu** [sarbagyastha/youtube_player_flutter#33]
Hi there,

I was so happy to find out there is a new version.

I updated my app and everything exploded.

I tried the example on git and it is the same behavior - see this recording https://www.dropbox.com/s/ju6mu21gqocl8o5/20190623_161111.mp4?dl=0

From video:
1. fullscreen square button does not work
2. changing to landscape does not make the video fullscreen
3. returning to non fullscreen mode somehow destroys the playing.

I have to revert to version 2, this new version is just not working.

I hope you can fix it soon,

Wish you good luck.

Device is Samsung Galaxy S8

**Comment by sarbagyastha** [comment]
Could you check if **v3.0.0+1** fixes it ?

**Comment by adrianvintu** [comment]
You are welcome.

- the fullscreen buuton does not work - first part of video
- first time on rotataion fullscreen does not work
- second time on rotataion fullscreen does work
- in fullscreen, pressing back will exit the app instead or returning to normal mode.

https://www.dropbox.com/s/lkomstrwzob3625/20190623_184825.mp4?dl=0

**Comment by sarbagyastha** [comment]
* If device's orientation is portrait (and auto orientation is enabled) then it won't switch to fullscreen as the external button doesn't forces orientation. It's just there for demo purpose. Have you checked with the fullscreen button inside the video itself?
* Make sure you take account the state of rotation lock too while testing. 
* Will work on implementing returning to portrait mode on back press tonight.
Thank you for reporting an issue. Are there any other issues you've been facing in v3 ?

**Comment by Igalsr** [comment]
>   Thank you for reporting an issue. Are there any other issues you've been facing in v3 ?

Hi, first of all, thank you very much for the great work. 

On V3 the player doesn't work on iPhone, it tries to play and then throws an exception- 

webview_flutter: unknown setting key: debuggingEnabled
flutter: player status: PlayerState.UNKNOWN

VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'pause()'
Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:ytview/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:ytview/ytview.dart:579:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:580:30)
#5      YoutubePlayerController.pause (package:youtube_player_flutter/src/youtube_player.dart:590:19)

Thanks for the help

**Comment by sarbagyastha** [comment]
@Igalsr could you check with Version 4, if it's working ?
