### ISSUE TITLE
Is it possible to disable "swipe" to forward/back?

### ISSUE THREAD

**Issue by Naografix** [sarbagyastha/youtube_player_flutter#357]
Hello,

I'm working on a little app to display videos in carousel, but currently, when I want to swipe to change my carouselPage, YoutubePlayer try to go forward/back when I swipe.

![image](https://user-images.githubusercontent.com/6979203/93097840-6227c900-f6a6-11ea-9fe7-f344ef1c67bb.png)

Is it possible to disable this feature?

Thanks

**Comment by Naografix** [comment]
```
flags: YoutubePlayerFlags(
   autoPlay: false,
   mute: true,
   disableDragSeek: true // Add this line
),
```

**Comment by minhlenhat-itr** [comment]
disableDragSeek also disable backdrop shadow, when press on the view, no grey shadow appear. Is there any way to disable swipe feature but still keep the backdrop shadow???

**Comment by openxcellMJ** [comment]
disableDragSeek: true not working in youtube_player_flutter 9.1.1  this version. please suggest solution for that how to resolve it
