### ISSUE TITLE
How hide disable fullscreen button

### ISSUE THREAD

**Issue by matamune94** [sarbagyastha/youtube_player_flutter#364]
There is a function to hide the full screen button ?

**Comment by zeeshanhussain** [comment]
@matamune94 Add bottom actions and remove full screen button from there, Here is the code.

```dart
YoutubePlayer(
controller: _controller,
bottomActions: [
  const SizedBox(width: 14.0),
  CurrentPosition(),
  const SizedBox(width: 8.0),
  ProgressBar(),
  RemainingDuration(),
  const PlaybackSpeedButton(),
  FullScreenButton(),
]
),
```

**Comment by matamune94** [comment]
Thanks so much, I have one more problem, when I use _controller.load (id) to load another video, the thumbnail of the previous video will appear again, then the next video will load. how can fix?

**Comment by zeeshanhussain** [comment]
@matamune94 I have no idea about that, I only load one video at a time. you can open a new issue for that.

**Comment by matamune94** [comment]
> @matamune94 I have no idea about that, I only load one video at a time. you can open a new issue for that.
thanks, i will.

**Comment by rrifafauzikomara** [comment]
> @matamune94 Add bottom actions and remove full screen button from there, Here is the code.
> 
> ```dart
> YoutubePlayer(
> controller: _controller,
> bottomActions: [
>   const SizedBox(width: 14.0),
>   CurrentPosition(),
>   const SizedBox(width: 8.0),
>   ProgressBar(),
>   RemainingDuration(),
>   const PlaybackSpeedButton(),
> ]
> ),
> ```

I think you need add `isExpanded: true` inside `ProgressBar` widget.

**Comment by developer-macrew** [comment]
I just need to disable the full screen button. nothing else

**Comment by developer-macrew** [comment]
> I just need to disable the full screen button. nothing else. please help. how I disable the only that button

I got it.  don't use the button action before the controller. just put the button action code after set controller

controller: _controller,
bottomActions: [
  const SizedBox(width: 14.0),
  CurrentPosition(),
  const SizedBox(width: 8.0),
  ProgressBar(),
  RemainingDuration(),
  const PlaybackSpeedButton(),
]

**Comment by Neeraj11061987** [comment]
Hide  full screen button Please Help

**Comment by Neeraj11061987** [comment]
Hide full-screen button Please Help
FullScreenButton() Not Working.

**Comment by RamniwasBrosis** [comment]
![Image](https://github.com/user-attachments/assets/dd77040d-a0a1-4ba9-ab41-133ff9092b9f)
how can I remove 'more videos' tag showing

**Comment by RamniwasBrosis** [comment]
![Image](https://github.com/user-attachments/assets/3e7343ea-5595-4e34-b420-d077dc1cd9ee)


how can I remove 'more videos' tag showing
