### ISSUE TITLE
How to start the videos at a specific time?

### ISSUE THREAD

**Issue by emersonsiega** [sarbagyastha/youtube_player_flutter#37]
Hello, this is more a doubt of how to use than a real issue...

I'm trying to start the videos at a specific time, but I couldn't do that before the video start.
If I let the video start automatically and then call `controller.seekTo( ... )`  when press a button, for instance, the video goes correctly to the specific time.

Can you help me with that?
Thanks!

**Comment by malder08** [comment]
I would also like to know this as well as how to stop a video at a specific time. Thanks!

**Comment by sarbagyastha** [comment]
Extremely sorry for the late respond, was quite busy since last time I updated the plugin. Will look like into the problem.

**Comment by sarbagyastha** [comment]
@malder08 in version 4, there's `startAt` property. You may use it to start video at specific time.
