### ISSUE TITLE
[BUG] Conflict with audioplayers package

### ISSUE THREAD

**Issue by daniwaxman** [sarbagyastha/youtube_player_flutter#379]
**Describe the bug**
Starting at version 7.0.1+1 there is a conflict with the Flutter audioplayers package (using version 0.16.1. When trying to run this you will get an error "SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable."

**To Reproduce**
Use both the following packages in your your pubspec.yaml file
youtube_player_flutter: ^7.0.0+1
audioplayers: ^0.16.1

**Expected behavior**
I shoudl be able to build and run my application with no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/10358119/96839078-5a9bd280-1451-11eb-804b-e816aa920513.png)

**Technical Details:**
- Flutter Stable 1.20.2

Prior to version 7.0.1+1 I was able to run correctly.

**Comment by sarbagyastha** [comment]
Refer Here: https://docs.gradle.org/current/userguide/dependency_resolution.html#:~:text=Dependency%20resolution%20is%20a%20process,be%20added%20to%20the%20graph.
