### ISSUE TITLE
YoutubeScaffold cannot have more than one YoutubePlayer as its descendants

### ISSUE THREAD

**Issue by Xoshbin** [sarbagyastha/youtube_player_flutter#38]
From version 3 as you mentioned "YoutubeScaffold cannot have more than one YoutubePlayer as its descendants" which it was one of the best features of this package. so the question is, is there any way to use version 3 and have multiple player in a list? in anyway any hack?

**Comment by sarbagyastha** [comment]
Extremely sorry for the late respond, was quite busy since last time I updated the plugin. Will be working on it by this weekend. Thank you !

**Comment by Xoshbin** [comment]
Thank you so much for responding and trying to make it work again 👍
