### ISSUE TITLE
[BUG] Youtube videos not playing on iOS Sim

### ISSUE THREAD

**Issue by RyanVDW** [sarbagyastha/youtube_player_flutter#380]
**Describe the bug**
I have followed the implementation for iOS and Android. Managed to get the videos playing on Android with no issue. Tested with iOS but the video displays but when I tap play I get an error back _"An error occurred. Please try again later"_

**To Reproduce**
Download example app youtube_player_iframe and run on iPhone iOS 14.1. Tap play on the home screen.

**Expected behavior**
It to play videos on iOS

**Screenshots**
![Screenshot 2020-10-23 at 16 57 02](https://user-images.githubusercontent.com/64264560/97019646-d92b6980-1550-11eb-938f-4ba9cecbdb44.png)

**Technical Details:**
 - iPhone 12 Pro Max
 - iOS 14.1

**Comment by RyanVDW** [comment]
NOTE:
I am unable to test iOS on a physical device.

**Comment by cccarle** [comment]
any news on this ? I have faced the same issue. Worked for me yesterday.

**Comment by RyanVDW** [comment]
It worked fine on a physical device but then it also started working on the emulator so i dont know haha
