### ISSUE TITLE
[BUG] Is my camera open when i use this pkg?

### ISSUE THREAD

**Issue by khalifa007** [sarbagyastha/youtube_player_flutter#382]
**Describe the bug**
what is this error ? 

" Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.adaptivebrightnessgo API Level 1 "

**Comment by sarbagyastha** [comment]
No.

**Comment by yacineblr** [comment]
Why "no" response ? I have same issue.

**Comment by niicolasalves** [comment]
I have the same problem. After starting the player, it is constantly sending this event in the log:

`I/CameraManagerGlobal(15942): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.adaptivebrightnessgo API Level 2
`

Did anyone manage to solve it?
