### ISSUE TITLE
[BUG] Setting HideThumbNail = false shows a play icon inside a white box before playing the video in Android

### ISSUE THREAD

**Issue by dreampowder** [sarbagyastha/youtube_player_flutter#383]
**Describe the bug**

A white play icon inside a white container shown when live video is loading in Android devices when hideThumbnail flag is set to true. We have an empty black screen in the ios side as expected.

**To Reproduce**

Open any video with "hideThumbnail = true" flag in the sample app. 

**Expected behavior**

nothing should be shown 

**Screenshots**
![Screen Shot 2020-10-26 at 21 43 40](https://user-images.githubusercontent.com/623593/97215516-9a5a1580-17d5-11eb-8c4b-2832ef197f5d.png)

**Technical Details:**
 - Device: Android Emulator Pixel Api and One Plus
 - OS: Android 
 - Version 29 

**Additional context**

**Comment by sarbagyastha** [comment]
It's from the iFrame Player API, so I guess nothing can be done for now.
