### ISSUE TITLE
Error loading youtube vidoe 

### ISSUE THREAD

**Issue by DennisPeqas** [sarbagyastha/youtube_player_flutter#39]
Im getting this Error 
 "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://sarbagyadhaubanjar.github.io').", source: https://s.ytimg.com/yts/jsbin/www-widgetapi-vflPBjLfx/www-widgetapi.js (106)

Does anyone how to solve ?

**Comment by nymul-islam** [comment]
same here

**Comment by sarbagyastha** [comment]
Could you check if the issue persist on Version 4 ?
