### ISSUE TITLE
[BUG] YouTube Terms of service violation

### ISSUE THREAD

**Issue by zjamshidi** [sarbagyastha/youtube_player_flutter#392]
**Describe the bug**
My recent app's update got rejected because of YouTube Terms of service violation:
> Your app currently contains YouTube videos, but watermark is not linked to YouTube while a YouTube video is playing. 

**Expected behavior**
https://developers.google.com/youtube/terms/branding-guidelines
> Any YouTube logo used within an application must link back to YouTube content or to a YouTube component of that application

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3742220/99515338-d20e4480-29b2-11eb-8ab8-07969ddd9b73.png)

**Comment by adeolaex** [comment]
Was your application rejected over at the App Store or Google Play Store ?

**Comment by zjamshidi** [comment]
Google Play Store

**Comment by sarbagyastha** [comment]
Which package are you using?

**Comment by zjamshidi** [comment]
youtube_player_flutter: ^7.0.0+7

**Comment by sarbagyastha** [comment]
If you're using your custom controls then consider hiding the logo with some overlay on **Paused** state and you can place your own implementation of YouTube button in the overlay that redirects to YouTube.

**Comment by zjamshidi** [comment]
So there is no parameter to control the visibility of the logo or what it should do when the logo is tapped.

**Comment by sarbagyastha** [comment]
No. But the Youtube logo goes away if you use web controls, which is default for youtube_player_iframe.

**Comment by adeolaex** [comment]
Okay, so a solution would be to download the Youtube logo from [here](https://developers.google.com/youtube/terms/branding-guidelines) . 

Then use a package like `url_launcher` to open the Youtube application or website whilst passing the id for that particular video ?

**Comment by zjamshidi** [comment]
OK. I placed a container with 1/4 width and 1/4 height on the bottom right corner. When it's tapped, the app will open our YouTube Channel. I will update here if Google Play's reviewers reject the app again.

**Comment by adeolaex** [comment]
@zjamshidi Any update ?

**Comment by zjamshidi** [comment]
I submitted a new app update, and they approved it.

**Comment by asheshstha** [comment]
> placed a container with 1/4 width and 1/4 height on the bottom right corner

I have few questions regarding it:
1. Do I need to show title and Icon all the time or only when the overlay is shown?
1. On tapping YouTube icon, should the link direct to the video on YouTube or can I direct just to the channel? YouTube branding guidelines mentions that the logo must link back to `YouTube content or to a YouTube component of that application`.

**Comment by Ok-Panda4332** [comment]
@zjamshidi 
> placed a container with 1/4 width and 1/4 height on the bottom right corner

I have few questions regarding it:
1. Do I need to show Icon all the time or only when the overlay is shown?
1. Do I need to show title at all? Or only when the overlay is shown?
1. On tapping YouTube icon, should the link direct to the video on YouTube or can I direct just to the channel? YouTube branding guidelines mentions that the logo must link back to `YouTube content or to a YouTube component of that application`. 
1. Also [Overlays and frames](https://developers.google.com/youtube/terms/required-minimum-functionality#overlays-and-frames) mentions that **You must not display overlays, frames, or other visual elements in front of any part of a YouTube embedded player, including player controls. Similarly, you must not use overlays, frames or other visual elements to obscure any part of an embedded player, including player controls.** Does this mean that you can't have your own custom controller?

**Comment by zjamshidi** [comment]
> 1. Do I need to show Icon all the time or only when the overlay is shown?
> 2. Do I need to show title at all? Or only when the overlay is shown?

The logo and the title are shown by the library. The problem is the logo is shown but it's not linked to Youtube


> 3. On tapping YouTube icon, should the link direct to the video on YouTube or can I direct just to the channel? YouTube branding guidelines mentions that the logo must link back to YouTube content or to a YouTube component of that application.

I linked the logo to our youtube channel as our application's Youtube component

>4. Also [Overlays and frames](https://developers.google.com/youtube/terms/required-minimum-functionality#overlays-and-frames) mentions that You must not display overlays, frames, or other visual elements in front of any part of a YouTube embedded player, including player controls. Similarly, you must not use overlays, frames or other visual elements to obscure any part of an embedded player, including player controls. Does this mean that you can't have your own custom controller?

I added an **invisible** clickable frame over the video player to make the logo tappable.
