### ISSUE TITLE
How Can we change the quality of the video

### ISSUE THREAD

**Issue by beauty-queen** [sarbagyastha/youtube_player_flutter#393]
How Can we change the quality of the video.
while playing the video we need to change the quality to 360 ,480 ,720 like that, please add that feature

**Comment by sarbagyastha** [comment]
@beauty-queen YouTube's iFrame API doesn't support changing playback quality. So this is not doable for now.

**Comment by sarbagyastha** [comment]
Closing as duplicate of #83
