### ISSUE TITLE
transformClassesWithMultidexlistForDebug

### ISSUE THREAD

**Issue by ljfreelancer88** [sarbagyastha/youtube_player_flutter#4]
Hi I've got the following error
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.```

Is there something something to do with Upgrading to AndroidX?

**Comment by sarbagyastha** [comment]
Seems you reached 64k method reference limit. You might need to enable multidex.
The plugin is perfectly compatible with androidX

**Comment by ljfreelancer88** [comment]
I already enabled since I'm using `youtube_player`

**Comment by sarbagyastha** [comment]
Oh! I think I forgot to migrate to AndroidX, could you verify whether migrating to AndroidX fixes the problem ?

**Comment by sarbagyastha** [comment]
Migrated to AndroidX in new version [1.1.0](https://pub.dartlang.org/packages/youtube_player_flutter#110), this might solve the issue.
