### ISSUE TITLE
Sugguestion: go to portrait mode when click "fullscreen button" in fullscreen mode

### ISSUE THREAD

**Issue by nthungdev1** [sarbagyastha/youtube_player_flutter#40]
### Prerequisite
```
YoutubeScaffold(
      fullScreenOnOrientationChange: true
```
The device auto rotation turned ON
the device is holding horizontally
Android device

### Expectation (suggestion)
When I tap on the fullscreen button of the default control, it should exit the fullscreen mode and bring me back to my normal layout.

### Reality
The screen stays at fullscreen.

**Comment by sarbagyastha** [comment]
Extremely sorry for the late respond, was quite busy since last time I updated the plugin. Thank you for your suggestion will be trying to resolve it by this weekend.

**Comment by nthungdev1** [comment]
> Extremely sorry for the late respond, was quite busy since last time I updated the plugin. Thank you for your suggestion will be trying to resolve it by this weekend.

That’s not a problem. Thank you for looking into the issue!

**Comment by sarbagyastha** [comment]
@nthungdev1 The whole mechanism for fullscreen is changed in Version 4. You may check it and give your feedback.
