### ISSUE TITLE
black screen when video playing on ios only sound is ok[BUG]

### ISSUE THREAD

**Issue by modyflutter** [sarbagyastha/youtube_player_flutter#410]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Technical Details:**

**Additional context**

**Comment by RohithKilaparthi** [comment]
@modyflutter did you find a solution to this? If not can you help sharing the logs.

**Comment by RonakPustack** [comment]
How is this still open in 2023?
Please update if this issue has been fixed by now.
