### ISSUE TITLE
[BUG] Can't hit Full Screen Button on IOS 14+

### ISSUE THREAD

**Issue by joaoarmando** [sarbagyastha/youtube_player_flutter#413]
**Describe the bug**
The full-screen button is hidden behind the title of the video.

**To Reproduce**
Run the app on iPhone and add YoutubePlayerIFrame()

**Expected behavior**
Be able to click the full screen button.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-12-31 at 16 12 35](https://user-images.githubusercontent.com/28633653/103423166-eb92d680-4b83-11eb-9350-485b8cdb7c4a.png)

**Technical Details:**
 - Device: Iphone 11
 - OS: 14.3
 - Version:  youtube_player_iframe: ^1.1.0

**Comment by jonatadashi** [comment]
You need to add hidetopmenu as stated here: https://github.com/sarbagyastha/youtube_player_flutter/issues/289#issuecomment-677587538

**Comment by joaoarmando** [comment]
@jonatadashi it works! Thanks. But as the doc says "it may violate YouTube TOS". Do you know any method that allows me to set full screen programmatically?

**Comment by jonatadashi** [comment]
> @jonatadashi it works! Thanks. But as the doc says "it may violate YouTube TOS". Do you know any method that allows me to set full screen programmatically?

My app didn't get rejected,, but its really up to you.

You can try `playsInline` and set it to `false`.
I recommend you take a look and playing around with the [parameters](https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_iframe#youtube-player-parameters) a bit.

**Comment by joaoarmando** [comment]
@jonatadashi Thanks! I was missing that. I'll close this now.
