### ISSUE TITLE
[BUG] Autoplay/unmute not working on Web

### ISSUE THREAD

**Issue by garyrutland** [sarbagyastha/youtube_player_flutter#421]
**Describe the bug**
Autoplay does not work on Web (for Chrome, at least) which I appreciate is potentially down to YoutTube now allowing it.
However, trying to make it so that you unmute a playing video doesn't seem to work as expected either.
If I try and unmute the video it stops the video.

**To Reproduce**

I've tried a number of variations but this is currently what I'm trying:

```dart
@override
Widget build(BuildContext context) {
  _controller = YoutubePlayerController(
    initialVideoId: videoId, // passed in to the widget constructor
    params: YoutubePlayerParams(
      showControls: false,
      autoPlay: true,
      mute: true,
    ),
  );

  return Container(
    child: YoutubePlayerControllerProvider(
      controller: _controller,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          YoutubePlayerIFrame(
            aspectRatio: 16 / 9,
          ),
          YoutubeValueBuilder(
            builder: (context, value) => ElevatedButton(
              child: const Text('Unmute'),
              onPressed: () => context.ytController.unMute(),
            ),
          ),
        ],
      ),
    ),
  );
}
```

**Expected behavior**
It should unmute the video and carry on playing.

**Technical Details:**
 - Device: Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
 - OS: macOS Big Sur 11.1
 - Version: Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB) - youtube_player_iframe: ^1.2.0+2

**Comment by Br4x** [comment]
same :/

**Comment by khangahs** [comment]
Autoplay is not working for some reason, please fix the params.

**Comment by khangahs** [comment]
After some tweaks, I found out that I just better implement the a custom iframe widgets to make things more flexible with the autoplay.
