### ISSUE TITLE
[BUG] when starting the player, it opens a in app browser on iOS 14

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [sarbagyastha/youtube_player_flutter#424]
**Describe the bug**
This bug happens only on iOS 14, it opens an in app browser that shows you the video but on Android it works

**To Reproduce**
1. Create a flutter app
2. Add youtube_player_iframe package version 1.2.0+2
3. Run app with a screen that has the player in it
4. It will launch in an in app browser not a player in the app.

**Expected behavior**
A player launches inside the app, not in a browser

**Technical Details:**
 - Device: iPhone X
 - OS: iOS 14.2
 - Version 1.2.0+2

**Comment by jonatadashi** [comment]
Duplicate #408
