### ISSUE TITLE
Publication to AppStore (Request of rights to the video)

### ISSUE THREAD

**Issue by Mishanya840** [sarbagyastha/youtube_player_flutter#429]
Hello, did anyone publich application witch this player?
AppStore requested me " please attach documentary evidence evidencing that you have all necessary rights or permissions to the third-party audio or video streaming, catalogs, and discovery services in your app."

**Comment by david4ahmed** [comment]
Try, putting the license and the link to the GitHub page in the app.

**Comment by cmd-dev** [comment]
> Hello, did anyone publich application witch this player?
> AppStore requested me " please attach documentary evidence evidencing that you have all necessary rights or permissions to the third-party audio or video streaming, catalogs, and discovery services in your app."

You have to initiate an audit with YouTube from their form and send this audit document to Apple.

**Comment by Mishanya840** [comment]
I resolved this. Just texted  them what i use youtube for video)) And they approved build
