### ISSUE TITLE
gradle error when i add your plugin to dependencies

### ISSUE THREAD

**Issue by hobrt-programming** [sarbagyastha/youtube_player_flutter#43]
hello
when i just add your plugin to dependencies i got this error with gradle without even import or use this plugin in any page or dart code 

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Finished with error: Gradle task assembleDebug failed with exit code 1

`

thank you

**Comment by sarbagyastha** [comment]
You might have other plugins as well due to which total class limit in android might have exceed. You'll need to enable multidex for it.

**Comment by ejdrian313** [comment]
I Have a lot of  plugins and enabled multidex in gradle file 
`shared_preferences: ^0.5.3+4
  cupertino_icons: ^0.1.2
  retrofit_generator: ^1.0.1
  build_runner: ^1.7.1
  json_serializable: ^3.2.2
  http: ^0.12.0+2
  fluttertoast: ^3.1.3
  url_launcher: ^5.1.0
  chewie: ^0.9.8+1
  video_player: ^0.10.2+5
  cached_network_image: ^2.0.0
  intl: ^0.16.0
  firebase_messaging: ^5.1.6
  firebase_dynamic_links: ^0.5.0+6
  flutter_html: ^0.10.4
  cloud_firestore: ^0.12.10+2
  firebase_analytics: ^5.0.6
  flutter_launcher_icons: ^0.7.3
  flutter_share: ^1.0.2+1
  webview_flutter: ^0.3.19+5
  flutter_spinkit: ^4.1.1
  youtube_player_flutter: ^6.0.3+2
  package_info: ^0.4.0+13
  firebase_crashlytics: ^0.1.3
  flutter_widgets: ^0.1.11
  icons_helper:
    git: git://github.com/sjmcdowall/icons_helper
  audioplayers: 0.13.2
  permission_handler:
    git:
      url: https://github.com/Baseflow/flutter-permission-handler
      ref: develop
  screen: ^0.0.5`
but importing youtube_player_flutter still causes error: Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
