### ISSUE TITLE
Giving time callback from every frame of video.

### ISSUE THREAD

**Issue by hiashutoshsingh** [sarbagyastha/youtube_player_flutter#431]
This plugin should have a callback mechanism or in listener may be which will constantly tell how much time has been passed in the video in seconds(preferred)..this will help the users to perform an action on a particular time frame.

**Comment by hiashutoshsingh** [comment]
`_controller.value.position`

This will do the trick.
Found after some getting hands dirty.

**Comment by jtkeyva** [comment]
is _controller.value.position still supported? i'm not seeing it in v3

**Comment by sarbagyastha** [comment]
Added `getCurrentPositionStream()` with v3.0.4
