### ISSUE TITLE
Youtube ads problem! [BUG]

### ISSUE THREAD

**Issue by Pluralist** [sarbagyastha/youtube_player_flutter#440]
**Describe the bug**
Can't get the youtube ads on Android or IOS, no matter "desktopMode" is true or not...

**To Reproduce**
Same as the example code...

**Expected behavior**
To get the youtube adds!

**Screenshots**

**Technical Details:**

**Additional context**

**Comment by Pluralist** [comment]
Or does it work only on a certified app and can't be tested during development?

**Comment by novas1r1** [comment]
@Pluralist what was the solution for this? Was it because it only works when the app is signed and live?
