### ISSUE TITLE
[BUG] Full screen not working on lastest flutter version

### ISSUE THREAD

**Issue by jpiabrantes** [sarbagyastha/youtube_player_flutter#441]
**Describe the bug**
When on the Android simulator, if I press the full-screen button the screen will rotate and the youtube player will get smaller:
![image](https://user-images.githubusercontent.com/2369107/108995816-8a741480-7695-11eb-9234-746309baac40.png)

On an iOs physical device when I press the full screen button nothing happens.

**Note:** This was working before I updated Flutter to version 1.22.6.

**To Reproduce**
```dart
YoutubePlayerBuilder(
   player: YoutubePlayer(controller: _youtubeController),
   builder: (_, Widget player) {
      return Scaffold(
         body: player
      );
   }
)
```

**Comment by binish784** [comment]
same problem here, have you found out a way to fix this, or may be disable the full screen button ?

**Comment by jigarfumakiya** [comment]
Any update on this issue?

**Comment by Skquark** [comment]
Also frustrated with issue since update and going null safety.  No errors, just doesn't do anything, makes it non-functional.  I double checked everything in my code but looks like it's this bug.  Hoping for update fix soon...
