### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by leszekkrol** [sarbagyastha/youtube_player_flutter#444]
pub get failed (1; So, because depends on both youtube_player_iframe ^1.2.0+2 and url_launcher ^6.0.2, version solving failed.). Because youtube_player_iframe 1.2.0+2 depends on url_launcher ^5.7.10 and no versions of youtube_player_iframe match >1.2.0+2 <2.0.0, youtube_player_iframe ^1.2.0+2 requires url_launcher ^5.7.10.

Please update libs

**Comment by jimmyff** [comment]
Another package also needs updating: https://github.com/sarbagyastha/youtube_player_flutter/issues/460
