### ISSUE TITLE
Does not play the video on iOS

### ISSUE THREAD

**Issue by besserwisser** [sarbagyastha/youtube_player_flutter#45]
Sadly, i cannot get it to work on iOS. In Android it works fine. In iOS it just does not play the video and sometimes I experienced freezes. 

I tested it with two iOS devices (iPad 2017 with iOS 12 and iPad Air with iOS 10). There is no error message in the Debug Console, it just loads forever.
 
I used your example project with the most up to date plugin version (but also tried 1.0.0 with the same result). And also tried it with my real world project.

I added this to Info.plist:
`	
   <key>io.flutter.embedded_views_preview</key> 
   <true/>
`

Have you tried the plugin on iOS devices? Any suggestions?

**Comment by docaohuynh** [comment]
I have a same issue

**Comment by japalacioo** [comment]
En mi caso sucede igual, aunque funcionó algunas veces pero cuando desplegué la aplicación y la probé no me funcionaba el reproductor

**Comment by gangireddi** [comment]
Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'loadById("iLnmTe5Q2Qw", 0)'

**Comment by sarbagyastha** [comment]
Hey folks, can you check with Version 4 and report with full log if it's not working on iOS?

**Comment by docaohuynh** [comment]
Still error
Test on Ipad mini2
```
2019-08-12 13:12:04.455268+0700 Runner[12961:4293299] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:601:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:518:30)
#5      YoutubePlayerController.play (package:youtube_player_flutter/src/youtube_player.dart:530:18)
#6      _PlayPauseButtonState.build.<anonymous closure> (package:youtube_player_flutter/src/controls.dart:86:64)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#20     _rootRunUnary (dart:async/zone.dart:1136:13)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _invoke1 (dart:ui/hooks.dart:250:10)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)

```

**Comment by sarbagyastha** [comment]
Which version are you currently on ?

**Comment by Igalsr** [comment]
Hi, I'm on 4.0.0+2 

Getting this: 


`flutter: player status: PlayerState.UNKNOWN
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:601:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:518:30)
#5      YoutubePlayerController.play (package:youtube_player_flutter/src/youtube_player.dart:530:18)
#6      _PlayPauseButtonState.build.<anonymous closure> (package:youtube_player_flutter/src/controls.dart:86:64)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:710:32)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#20     _rootRunUnary (dart:async/zone.dart:1136:13)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _invoke1 (dart:ui/hooks.dart:252:10)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:161:5)
`

**Comment by sarbagyastha** [comment]
@Igalsr @docaohuynh can you mind helping by inspecting the app using Safari Web Inspector and reporting the console's output?

**Comment by docaohuynh** [comment]
I have used 4.0.0+2
When I inspect there is no console log on Safari Web Inspector just have log on Xcode
```
2019-08-12 17:23:53.930619+0700 Runner[13181:4304875] flutter: PlaybackQualityChange medium
2019-08-12 17:23:54.153331+0700 Runner[13181:4304744] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2019-08-12 17:23:54.414316+0700 Runner[13181:4304744] Received memory pressure event 2 vm pressure 0

Received memory pressure event 2 vm pressure 0
2019-08-12 17:23:55.316434+0700 Runner[13181:4304744] Received memory pressure event 4 vm pressure 1

Received memory pressure event 4 vm pressure 1
2019-08-12 17:23:57.724045+0700 Runner[13181:4311289] [ProcessSuspension]  0x2879cba80 - ProcessAssertion() Unable to acquire assertion for process with PID 0
2019-08-12 17:24:16.570957+0700 Runner[13181:4304744] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
2019-08-12 17:24:25.438485+0700 Runner[13181:4304744] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2019-08-12 17:24:27.721993+0700 Runner[13181:4304744] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

**Comment by Igalsr** [comment]
@sarbagyastha I'm unable to get it inspected once I click on it it's just empty

**Comment by chethanprabhakar** [comment]
Hi

I am facing similar issue of videos not playing in IOS. On my android device it mostly works, although a couple of times i've not been able to play videos

i get this error for IOS
```

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=58, WKJavaScriptExceptionMessage=TypeError: player.playVideo is not a function. (In 'player.playVideo()', 'player.playVideo' is undefined), WKJavaScriptExceptionColumnNumber=21, WKJavaScriptExceptionSourceURL=https://sarbagyadhaubanjar.github.io/youtube_player/ios/player.js, NSLocalizedDescription=A JavaScript exception occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter<…>
```

Thanks,
Chethan

**Comment by sarbagyastha** [comment]
Could you check if  [**Version 4.1.0**](https://pub.dev/packages/youtube_player_flutter#410) fixes it.

**Comment by Igalsr** [comment]
Hi, @sarbagyastha. unfortunately, it didn't help.

`flutter: player status: PlayerState.UNKNOWN
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:601:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:553:30)
#5      YoutubePlayerController.play (package:youtube_player_flutter/src/youtube_player.dart:565:18)
#6      _PlayPauseButtonState.build.<anonymous closure> (package:youtube_player_flutter/src/controls.dart:86:64)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:710:32)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#20     _rootRunUnary (dart:async/zone.dart:1136:13)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _invoke1 (dart:ui/hooks.dart:252:10)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:161:5)
`

**Comment by docaohuynh** [comment]
With version 4.1.0 It make my app crash

**Comment by thivankasarathchandra** [comment]
Hi , I'm also using the 4.1.0 and i used my mobile to debug,
Still get the following error code,


`flutter: YoutubePlayerValue(isReady: false, isEvaluationReady: false, isLoaded: false, duration: 0:00:00.000000, position: 0:00:00.000000, buffered: 0.0, isPlaying: false, volume: 100, playerState: PlayerState.UNKNOWN, playbackRate: PlaybackRate.NORMAL, errorCode: 0)
flutter: YoutubePlayerValue(isReady: false, isEvaluationReady: false, isLoaded: false, duration: 0:00:00.000000, position: 0:00:00.000000, buffered: 0.0, isPlaying: false, volume: 100, playerState: PlayerState.UNKNOWN, playbackRate: PlaybackRate.NORMAL, errorCode: 0)
flutter: YoutubePlayerValue(isReady: true, isEvaluationReady: false, isLoaded: false, duration: 0:00:00.000000, position: 0:00:00.000000, buffered: 0.0, isPlaying: false, volume: 100, playerState: PlayerState.UNKNOWN, playbackRate: PlaybackRate.NORMAL, errorCode: 0)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:601:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:553:30)
#5      YoutubePlayerController.play (package:youtube_player_flutter/src/youtube_player.dart:565:18)
#6      _PlayPauseButtonState.build.<anonymous closure> (package:youtube_player_flutter/src/controls.dart:86:64)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:710:32)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#18     _rootRunUnary (dart:async/zone.dart:1136:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _invoke1 (dart:ui/hooks.dart:252:10)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:161:5)`

**Comment by michealchow** [comment]
i am facing the same issue, with version 4.1.0. It works fine on android device, but not responding anything on IOS device

**Comment by Igalsr** [comment]
@sarbagyastha do you need any other help? I'm waiting for a working youtube library for iOS to release for production, maybe you know another library or you need some help in order to get it working?

**Comment by vinodlee** [comment]
Video not playing

VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:626:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:553:30)
#5      YoutubePlayerController.play (package:youtube_player_flutter/src/youtube_player.dart:565:18)
#6      _PlayPauseButtonState.build.<anonymous closure> (package:youtube_player_flutter/src/controls.dart:86:64)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#18     _rootRunUnary (dart:async/zone.dart:1136:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _invoke1 (dart:ui/hooks.dart:250:10)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)

**Comment by vinodlee** [comment]
Same problem for me


VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'play()'
Error Domain=WKErrorDomain Code=1 "An unknown error occurred" UserInfo={NSLocalizedDescription=An unknown error occurred})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:90:21)
#3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:626:39)
#4      YoutubePlayerController._evaluateJS (package:youtube_player_flutter/src/youtube_player.dart:553:30)
#5      YoutubePlayerController.play (package:youtube_player_flutter/src/youtube_player.dart:565:18)
#6      _PlayPauseButtonState.build.<anonymous closure> (package:youtube_player_flutter/src/controls.dart:86:64)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#18     _rootRunUnary (dart:async/zone.dart:1136:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _invoke1 (dart:ui/hooks.dart:250:10)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)

**Comment by docaohuynh** [comment]
> @sarbagyastha do you need any other help? I'm waiting for a working youtube library for iOS to release for production, maybe you know another library or you need some help in order to get it working?

I have used this package https://github.com/hoanglm4/flutter_youtube_view. it work for both android and Ios

**Comment by fxsalazar** [comment]
Same here and log is flooded with
```
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
```

**Comment by py-zoid** [comment]
Did anyone find a fix or workaround for this issue?

**Comment by RuneAlexanderLarsen** [comment]
> Did anyone find a fix or workaround for this issue?

I ended up using another package called flutube:
https://pub.dev/packages/flutube
Worked for both android and iOS.
Only downside is copyrighted videos

**Comment by siloebb** [comment]
I having this problem, I can fix it puting the Youtube in a Container, like this:
(remember that official youtube need more than 200px in both sides.)

```
Widget getPlayerYoutube() {
    return Container(
      height: 300,
      width: 300,
      child: YoutubePlayer(
        context: context,
        videoId: getVideoId(),
      ),
    );
  }
```

**Comment by sarbagyastha** [comment]
Check #79
