### ISSUE TITLE
[BUG] youtube always open in-app browser on iOS

### ISSUE THREAD

**Issue by pansitwattana** [sarbagyastha/youtube_player_flutter#462]
**To Reproduce**
- Run Example code in iOS
- when app run, app open browser link of youtube

on youtube_player_mobile.dart function shouldOverrideUrlLoading it run url_launcher.launch
![Screen Shot 2564-03-17 at 13 18 28](https://user-images.githubusercontent.com/12652753/111423878-82067b00-8723-11eb-979c-d8b5458de323.png)

**Comment by hokenn99** [comment]
I have the same issue .... have you found a solution ?

**Comment by pansitwattana** [comment]
I forked this repository and fix the bugs

![Screen Shot 2564-03-29 at 13 54 41](https://user-images.githubusercontent.com/12652753/112798169-bcaed280-9096-11eb-92de-fe65fde82467.png)

you can see my git repository: https://github.com/pansitwattana/youtube_player_flutter/blob/014c7745280af8941b578574557b910bf140f950/packages/youtube_player_iframe/lib/src/players/youtube_player_mobile.dart#L138

**Comment by bounty1342** [comment]
Pleas make a PR :)

**Comment by temzints** [comment]
when is this gonna merge with the master branch?

**Comment by pansitwattana** [comment]
Someone is opening PR here https://github.com/sarbagyastha/youtube_player_flutter/pull/420

**Comment by kkweon** [comment]
any update on this?

**Comment by stillie** [comment]
Im using `youtube_player_iframe` Is this fixed there?

**Comment by ArneSaknussemm89** [comment]
Still seeing this on 2.1.0 - Have a listing of Youtube videos, and when the screen builds it automatically opens *every* video in a browser window.

iOS 14.5
Flutter 2.2.3

**Comment by sarbagyastha** [comment]
Fixed with v2.2.2
