### ISSUE TITLE
No play next song when Screen off

### ISSUE THREAD

**Issue by dtdevpro** [sarbagyastha/youtube_player_flutter#47]
No play next song when Screen off (Screen on is normal), because setState not run when screen off,  after screen on then setState run and next song play.
Code:
void listener() {
    if (_youtubePlayerController.value.playerState == PlayerState.ENDED) {
      setState(() {
        if (_repeat == 0) {
          if (_shuffle) {
            int random;
            if(global_posts.length>1){
              do {
                random = Random().nextInt(global_posts.length);
              } while (global_post_index == random);
              global_post_index = random;
            }
          } else {
            if (global_post_index >= global_posts.length - 1) {
              _showDialogEndedPlaylist();
            } else {
              global_post_index++;
            }
          }
        } else if (_repeat == 1) {
          if (_shuffle) {
            int random;
            if(global_posts.length>1){
              do {
                random = Random().nextInt(global_posts.length);
              } while (global_post_index == random);
              global_post_index = random;
            }
            else{
            }
          } else {
            if (global_post_index >= global_posts.length - 1) {
              global_post_index = 0;
            } else {
              global_post_index++;
            }
          }
        } else {
        }
      });
    }
--------------------------------------------------------------------
YoutubePlayer(
                              context: context,
                              width: 50,
                              videoId:
                                  global_posts[global_post_index].youtube_link,
                              flags: YoutubePlayerFlags(
                                  autoPlay: true,
                                  showVideoProgressIndicator: false,
                                  hideFullScreenButton: true,
                                  hideControls: true),
                              onPlayerInitialized: (controller) {
                                _youtubePlayerController = controller;
                                _youtubePlayerController.addListener(listener);
                              },
                            )

**Comment by sarbagyastha** [comment]
The player is not intended to play in background. If you anyway want such functionality, you may opt for execute code in background using packages available in pub.
