### ISSUE TITLE
Support to hide playback rate change button from controls

### ISSUE THREAD

**Issue by hs-sundeep** [sarbagyastha/youtube_player_flutter#52]
Add a flag to `YoutubePlayerFlags` to hide playback rate change button from controls.

**Comment by tafelito** [comment]
And also seems like the playback is not viewable and even when you tap on any option doesn't do anything

![image](https://user-images.githubusercontent.com/5973652/64914552-75662880-d722-11e9-95af-79930fbab8d7.png)

**Comment by Scofielddd** [comment]
> And also seems like the playback is not viewable and even when you tap on any option doesn't do anything
> 
> ![image](https://user-images.githubusercontent.com/5973652/64914552-75662880-d722-11e9-95af-79930fbab8d7.png)

same bug

**Comment by sarbagyastha** [comment]
Fixed with Version 5.
