### ISSUE TITLE
plz add video quality options like 360,720 etc

### ISSUE THREAD

**Issue by shailendra-rajpoot** [sarbagyastha/youtube_player_flutter#520]
this is a great dependency but one feature is needed as high priority that is video quality options. dear sir plz ad it feature as soon as possible.

**Comment by reshuashish** [comment]
do you know any good alternative to your package. Having same issue

**Comment by PcolBP** [comment]
Youtube player itself choose quality on screen resolution, even if you will force it out, even then Youtube will low it down if its needed.

**Comment by sarbagyastha** [comment]
You can enable `desktopMode` param, if you need quality settings. But currently there is no way to change it programmatically.

One can extract Youtube media links and play using video players, but that violates YouTube's TOS.
