### ISSUE TITLE
[BUG] In ios always redirect to youtube-nocookie

### ISSUE THREAD

**Issue by hifiaz** [sarbagyastha/youtube_player_flutter#521]
i use basic example provided in this package and test in ios emulator but when play video always redirect to youtube-nocookie

in log theres message
`ReferenceError: Can't find variable: pause`
<img width="358" alt="Screen Shot 2021-07-24 at 13 50 30" src="https://user-images.githubusercontent.com/20653803/126860270-7c41e2ce-23cb-4161-bdce-d953875ae772.png">

**Comment by sarbagyastha** [comment]
Fixed with v2.2.2
