### ISSUE TITLE
[BUG] [youtube_player_iframe 2.2.1]  video does not load, fields from the scroll

### ISSUE THREAD

**Issue by snoopdoggy322** [sarbagyastha/youtube_player_flutter#525]
**Describe the bug**
The video does not load, you can see the fields from the scroll, I will display everything in the attached video

**To Reproduce**
Just launch any video

**Attachments**

> https://user-images.githubusercontent.com/38835822/127503831-6de3d136-8c5f-45db-a8c7-93ba725b1625.mov

**Technical Details:**
 - Device: iPhone 8 
 - OS: 14.5
 - Version 2.2.1

**Code**
                  YoutubePlayerControllerProvider(
                        controller: _controller,
                        child: YoutubePlayerIFrame(
                          aspectRatio: 16 / 9,
                        ),
                      ),

**Comment by kaiquegazola** [comment]
It seems related to "useShouldOverrideUrlLoading". 

I did the following test and it worked fine on my iOS case (Simulator Iphone 12 Pro & real Iphone 6s):

```dart
initialOptions: InAppWebViewGroupOptions(
        crossPlatform: InAppWebViewOptions(
          /* ... */
          useShouldOverrideUrlLoading: false, //I switched this to false, looks always get in this callback only in iOS (Android/Web is fine).
        ),
        ios: IOSInAppWebViewOptions(
          /* ... */
        ),
        android: AndroidInAppWebViewOptions(
          /* ... */
        ),
      ),
```

**Comment by PcolBP** [comment]
I can confirm, that player will play after sets useShouldOverrideUrlLoading to false, but then whole function with shouldOverrideUrlLoading won't be trrigered. I have seen similar problem on inappwebview issues [here](https://github.com/pichillilorenzo/flutter_inappwebview/issues/863)
My configuration:
Phone: Physical Iphone 10
IOS: 14.7.1
Flutter ver.: 2.2.3 stable
youtube_player_iframe ver.: 2.2.1

**Comment by sarbagyastha** [comment]
Could you please verify if **v2.2.2** fixes the issue ?

**Comment by PcolBP** [comment]
I can confirm, that it works again on both platforms. Thank you very much.
