### ISSUE TITLE
[BUG] type 'Null' is not a subtype of type 'List<int>' in type cast

### ISSUE THREAD

**Issue by xarmatura** [sarbagyastha/youtube_player_flutter#577]
The following _CastError was thrown resolving an image codec:
type 'Null' is not a subtype of type 'List<int>' in type cast

When the exception was thrown, this was the stack: 
#1      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:99:24)
<asynchronous suspension>
(elided one frame from dart:async)
Image provider: NetworkImage("https://i3.ytimg.com/vi_webp/mrMmoQFCUmI/sddefault.webp", scale: 1.0)
Image key: NetworkImage("https://i3.ytimg.com/vi_webp/mrMmoQFCUmI/sddefault.webp", scale: 1.0)

It happened when a video is loaded.

**Comment by xarmatura** [comment]
Please, how to fix it?

**Comment by manishtalreja0510** [comment]
this error occurs when you are providing the wrong URL to the network image. Make sure you are providing the right URL(that ends with a format extension that is supported by the network image).

**Comment by xarmatura** [comment]
@manishtalreja0510 URL is correct.

**Comment by manishtalreja0510** [comment]
@xarmatura copy the link in google chrome and check if the image is loading in chrome or not

**Comment by xarmatura** [comment]
@manishtalreja0510 It's the URL to the video. I'm using a YouTube player to show videos from YouTube.

**Comment by xarmatura** [comment]
Do not recommend using this plugin.

**Comment by SakshamKarnawat** [comment]
How did you resolve the issue @xarmatura ? Please tell.

**Comment by xarmatura** [comment]
> How did you resolve the issue @xarmatura ? Please tell.

I haven't solved it, I just don't use it anymore. Sorry, can't help.
