### ISSUE TITLE
[BUG] the video loads but doesn't play

### ISSUE THREAD

**Issue by mohadel92** [sarbagyastha/youtube_player_flutter#586]
**Describe the bug**
after using of Youtube package and loading it to the view
the video used to play fine, but now it doesn't play

**To Reproduce**
1-implement player
2- run app under android

**Expected behavior**
video to play

**Technical Details:**
 - Device: Redmi note 5  - poco x3 pro 
 - OS: (android 9) ---(andorid 11)

**Additional context**
`28917): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (light greylist, reflection)
W/nsquare.(28917): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (light greylist, reflection)
(28917): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
(28917): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
W/nsquare.mapsou(28917): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
W/nsquare.mapsou(28917): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
W/nsquare.mapsou(28917): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
W/nsquare.mapsou(28917): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (light greylist, reflection)
W/cr_media(28917): Requires BLUETOOTH permission
W/nsquare.mapsou(28917): Accessing hidden method Landroid/media/ImageReader;->newInstance(IIIIJ)Landroid/media/ImageReader; (dark greylist, linking)
W/ContentCatcher(28917): Failed to notify a WebView
`

**Comment by yelkamel** [comment]
same for me

**Comment by rahulserver** [comment]
same here(on redmi)

**Comment by FernandoUFS** [comment]
The video doesn't play here either. I can't play any Live video and there is nothing in Log.

**Comment by saulmestanza** [comment]
Was someone able to solve it ? its happening to me also

**Comment by bawantha** [comment]
I think this plugin is not working.
