### ISSUE TITLE
I want the old behaviour for full screen

### ISSUE THREAD

**Issue by Jay-Jeong1988** [sarbagyastha/youtube_player_flutter#59]
Hi @sarbagyastha , I just noticed that the behaviour when the player becomes full screen has been changed sine the recent update. However I actually had better experience with the old behaviour. I want the player go landscape and also I don't want it to navigate to new widget by creating one because it removes all my UI until it pops back again. I wonder if you made a way to keep using the player as old version? (but I only want it for full screen, I like newer version for everything else)
Thanks !!

**Comment by sarbagyastha** [comment]
@Jay-Jeong1988 Sorry for late response. Version 5 might address this.
