### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by pdwitharana** [sarbagyastha/youtube_player_flutter#595]
**Describe the bug**
Hi there,
The package is great. However, when I used it in my project, the memory usage exceeded 500 MB while the video was playing. Could you please advice if this is a known issue. I was running it on iOS and monitoring memory on Xcode.

Kind regards

**To Reproduce**

**Expected behavior**

**Screenshots**

**Technical Details:**

**Additional context**

**Comment by sarbagyastha** [comment]
The memory usage is directly related to `PlatformView`. So can do nothing.
