### ISSUE TITLE
[BUG] - iOS app is crashing when using this package

### ISSUE THREAD

**Issue by Akshay-Dhondge** [sarbagyastha/youtube_player_flutter#599]
**Describe the bug**
2022-01-19 11:31:44.329603+0530 *******[13140:81168] -[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x7fff8a349fb0
2022-01-19 11:31:44.391824+0530 ******[13140:81168] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull _fastCStringContents:]: unrecognized selector sent to instance 0x7fff8a349fb0'

**To Reproduce**
Simply navigating on the screen where using >> (Even tried with real device still not working)
Container(
                height: 100,
                child: YoutubePlayerBuilder(
                    player: YoutubePlayer(controller: _controller),
                    builder: (context, player) {
                      return Column(
                        children: [
                          player,
                        ],
                      );
                    }),
              ),

**Expected behavior**
A simple youtube video should be played.

**Technical Details:**
 - Device: iPhone 13 Mini
 - OS: iOS 15
 - Xcode: 13.

**Additional context**
**Working on android just crashing on iOS**

**Comment by SameerCHS** [comment]
facing same issue

**Comment by ermand-hoxha** [comment]
I have the same problem with version ^2.2.0. On android works fine, but not in IOS

**Comment by Akshay-Dhondge** [comment]
@ermand-hoxha There is an issue in flutter_inappwebview, just goto **Options.swift** file and comment line number 20. Its work for me. refer following path to goto goto Options.swift file
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-4.0.0+4/ios/Classes/Options.swift
