### ISSUE TITLE
Video height not Fit with Player

### ISSUE THREAD

**Issue by SandyAra** [sarbagyastha/youtube_player_flutter#6]
![WhatsApp Image 2019-04-22 at 12 42 34 PM](https://user-images.githubusercontent.com/45088009/56488502-29f57880-64fc-11e9-9052-3e3273d3519b.jpeg)

**Comment by sarbagyastha** [comment]
@SandyAra , you'll need to adjust the aspect ratio.

**Comment by SandyAra** [comment]
@sarbagyastha   i changed aspect ratio but still white space on top

**Comment by sarbagyastha** [comment]
Can you share screenshot with white space on top. And also the video id.

**Comment by SandyAra** [comment]
Video Id = 42ApWolGIt0

**Thumbnail View**
![WhatsApp Image 2019-04-23 at 12 38 13 PM](https://user-images.githubusercontent.com/45088009/56561438-c2573000-65c4-11e9-9f52-97f906a8dc2e.jpeg)

**Video** 
![WhatsApp Image 2019-04-23 at 12 38 01 PM](https://user-images.githubusercontent.com/45088009/56561458-cedb8880-65c4-11e9-91a1-05d412627bae.jpeg)

**Comment by sarbagyastha** [comment]
That seems to be an appbar, try hiding appbar.

**Comment by SandyAra** [comment]
No app bar used. You refer the Thumbnail View.

**Comment by SandyAra** [comment]
I guess problem in Screen Size.. Its looks perfect in Emulator or other device.
My Screen 19.9 Full Screen Display

**Comment by sarbagyastha** [comment]
Sorry I missed the reply. Can you share the code snippet.
