### ISSUE TITLE
Play doesn't always work

### ISSUE THREAD

**Issue by chrisrohitbrendan** [sarbagyastha/youtube_player_flutter#60]
[INFO:CONSOLE(1)] "Uncaught ReferenceError: play is not defined", source: https://sarbagyadhaubanjar.github.io/youtube_player/android/ (1)

After multiple clicks on the play button, it eventually works. Makes it very unreliable.

**Comment by Nidakhan786** [comment]
I got the same issue.
did you find any solution?
@chrisrohitbrendan

**Comment by sarbagyastha** [comment]
Can you check with version 5 ?

**Comment by Nidakhan786** [comment]
[INFO:CONSOLE(69)] "Uncaught TypeError: Cannot read property 'playVideo' of undefined", source: https://sarbagyadhaubanjar.github.io/youtube_player/android/player.js 

@sarbagyastha  still getting this error .

**Comment by Nidakhan786** [comment]
@sarbagyastha its working fine on emulator but not working fine if i connect my device.

**Comment by sarbagyastha** [comment]
@Nidakhan786 you're using older version. Please try with version 5.0.0+1

**Comment by Cheas** [comment]
Hello everyone, I've already spent three days on this problem. I have a random rejection with such a message 
( **I/chromium( 5099): [INFO:CONSOLE(1)] "Uncaught ReferenceError: play is not defined", source:  (1)**)
with a probability of 15-20%. 
I am using version ^ 6.1.1 (check Android emulator & device), checked newer ones - similarly. 
Also tried the plugin flutter_youtube_iframe - everything is stable, but no padding controller.value (position).

I am at an impasse for now and hope for help.
