### ISSUE TITLE
[QUESTION] Is it possible to hide video and show controller only

### ISSUE THREAD

**Issue by ljfreelancer88** [sarbagyastha/youtube_player_flutter#601]
Hi, there's an instance that I want the audio only from YouTube not the video. Is it possible to hide the video or Iframe in the background and show selected Controller only like play, pause, seekTo, playback speed? Think of it like Audio Player.

Thanks in advance.

**Comment by thomasp7983** [comment]
Looking for the same... Please help

**Comment by sarbagyastha** [comment]
It's not possible with this library, but it should be possible by running the youtube embed url in headless mode.
