### ISSUE TITLE
Does Apple or Google reject the application if using this Library?

### ISSUE THREAD

**Issue by thomasp7983** [sarbagyastha/youtube_player_flutter#604]
Built an Application to play our church videos from Our Application. 

Really worried to know if there would be any issues in getting the approvals from Apple and Google.

**Comment by xenSlayer** [comment]
Well I have an [app](https://play.google.com/store/apps/details?id=com.kiran.flick) successfully posted on Google Play Store that uses this library for playing youtube videos. There are couple Google community guidelines that you need to consider when using this or any other package that plays youtube videos that are owned by other people. But one most important is

- If your app contains ad's then you should never show those ad's when you have youtube videos playing on the same screen.
