### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jeeldev9** [sarbagyastha/youtube_player_flutter#606]
android {                                                                                     
   defaultConfig {                                                                             
     minSdkVersion 19                                                                          
   }                                                                                           
}                                                                                             
                                                                                               
 Note that your app won't be available to users running Android SDKs below 19.    
solve this issue on flutter newer version.

**Comment by AshutoshPatole** [comment]
Just update the minSdkVersion to 24 or above.
