### ISSUE TITLE
App crash after pop

### ISSUE THREAD

**Issue by shinewanna** [sarbagyastha/youtube_player_flutter#607]
App crash after pop from the youtube screen.

It is working before upgrade to flutter latest version 2.10.0, it crash after upgrade.

**Technical Details:**
 - Device: Poco X2
 - Flutter Version: 2.10.0

Error Logs
`[SurfaceTexture-0-20334-3] attachToContext: SurfaceTexture is already attached to a context
E[/flutter]() (20334): [ERROR:flutter[/fml/platform/android/jni_util.cc]()(211)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E[/flutter]() (20334): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:295)
E[/flutter]() (20334): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.attachToGLContext(SurfaceTextureWrapper.java:57)
E[/flutter]() (20334): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E[/flutter]() (20334): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E[/flutter]() (20334): 	at android.os.Looper.loop(Looper.java:193)
E[/flutter]() (20334): 	at android.app.ActivityThread.main(ActivityThread.java:7904)
E[/flutter]() (20334): 	at java.lang.reflect.Method.invoke(Native Method)
E[/flutter]() (20334): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E[/flutter]() (20334): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E[/flutter]() (20334):
F[/flutter]() (20334): [FATAL:flutter[/shell/platform/android/platform_view_android_jni_impl.cc]()(1301)] Check failed: fml::jni::CheckException(env).
F[/crashpad]()(20761): dlopen: dlopen failed: library "libandroidicu.so" not found: needed by [/system/lib64/libharfbuzz_ng.so]() in namespace (default)
F[/libc]()    (20334): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 20334 (tube_downloader), pid 20334 (tube_downloader)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'POCO[/phoenixin/phoenixin:11]()[/RKQ1.200826.002/V12.5.6.0.RGHINXM]():user[/release-keys]()'Revision: '0'
ABI: 'arm64'
Timestamp: 2022-02-08 15:33:19+0630
pid: 20334, tid: 20334, name: tube_downloader  >>> com.swn.tube_downloader <<<
uid: 10964
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter[/shell/platform/android/platform_view_android_jni_impl.cc]()(1301)] Check failed: fml::jni::CheckException(env).
'
    x0  0000000000000000  x1  0000000000004f6e  x2  0000000000000006  x3  0000007fe07706d0
    x4  0000007e11563000  x5  0000007e11563000  x6  0000007e11563000  x7  00000000040c04d8
    x8  00000000000000f0  x9  a0b43571608b28c9  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 000000000000007e  x14 002e470f69b5c013  x15 00003257c6d502da
    x16 0000007e0c37f948  x17 0000007e0c35e390  x18 0000007e10cac000  x19 0000000000004f6e
    x20 0000000000004f6e  x21 00000000ffffffff  x22 b400007be1547498  x23 b400007bceba46c8
    x24 b400007d79ac2280  x25 0000000000000000  x26 0000000000000001  x27 0000000000000001
    x28 000000000000004a  x29 0000007fe0770750
    lr  0000007e0c311aa0  sp  0000007fe07706b0  pc  0000007e0c311acc  pst 0000000000000000
backtrace:
      #00 pc 0000000000089acc  [/apex/com.android.runtime/lib64/bionic/libc.so]() (abort+164) (BuildId: a790cdbd8e44ea8a90802da343cb82ce)
      #01 pc 000000000150a740  [/data/app/]()~~o6JCErhtGvTj8p4PQhY4VA==[/com.swn.tube_downloader-ksb_HEcuQ1Yb5Vldw5VcxA]()==[/base.apk]()!libflutter.so (offset 0x3352000) (BuildId: c42c6209986a10065da91c022954abcc47cb6c46)`

**Comment by d3xt3r2909** [comment]
same issue

**Comment by d3xt3r2909** [comment]
Seems like this is issue with new version of flutter and platform views https://github.com/flutter/flutter/issues/98155

**Comment by d3xt3r2909** [comment]
Ok based on discussion with the flutter community I come to this answer https://github.com/flutter/flutter/issues/98155#issuecomment-1034886730 . 

For me resolved an issue by disabling hybrid composition @shinewanna could you also try. 

I believe that this solution is also decreasing performances of webview (which I already point out to flutter ppl) but it's a solution for now.
