### ISSUE TITLE
 Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-full-version-list'.[BUG]

### ISSUE THREAD

**Issue by harunme3** [sarbagyastha/youtube_player_flutter#608]
**Describe the bug**

**To Reproduce**

**Expected behavior**
E/libEGL  (16679): Invalid file path for libcolorx-loader.so
I/chatty  (16679): uid=11950(com.vs.ncertclass1to12th) RenderThread identical 1 line
3
E/libEGL  (16679): Invalid file path for libcolorx-loader.so
[log] Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-full-version-list'.

**Screenshots**
If applicable, add screenshots t
![Screenshot (7)](https://user-images.githubusercontent.com/38163453/153339955-19024de0-e864-4627-9bd1-a397d37c320d.png)
o help explain your [problem.](url)

[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.64.1)        
[√] Connected device (4 available)  
[√] HTTP Host Availability
**Additional context**

**Comment by sarbagyastha** [comment]
The log can be ignored.
