### ISSUE TITLE
Library deprecated?

### ISSUE THREAD

**Issue by d3xt3r2909** [sarbagyastha/youtube_player_flutter#609]
Is this library discontinued as I don't see any activities on resolving issues and merging PR for a long time?

**Comment by thiagocarvalhodev** [comment]
I'm with the same doubt.

**Comment by sarbagyastha** [comment]
I've been occupied lately so could not maintain the package. But will work on issues starting March.

**Comment by thiagocarvalhodev** [comment]
Thanks for answering us!

**Comment by LostInDarkMath** [comment]
@sarbagyastha Any news about your big comeback? ;)
