### ISSUE TITLE
[BUG] youtube_flutter_iframe [2.2.2],  playVideoAt, load these functions not working.

### ISSUE THREAD

**Issue by mjarpitanand** [sarbagyastha/youtube_player_flutter#612]
These functions are not working clearly, Any major problem?
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/14835964/155014820-74d8f03a-5038-477c-9224-57f2991c3f20.png">

**Comment by sunilguptasg** [comment]
_youTubeController!.load(YoutubePlayerController.convertUrlToId(videoFileUrl)!) - this works well for me. Can you send details to reproduce the issue?
