### ISSUE TITLE
[BUG] Looping one single video does not work

### ISSUE THREAD

**Issue by kaciula** [sarbagyastha/youtube_player_flutter#615]
I want to play a single youtube video in a loop. I've tried setting the loop field in YoutubePlayerParams to true. I've also tried to call setLoop() method on the controller. But with no success.

**To Reproduce**
Just use a YoutubePlayerIframe with a controller that has loop set to true.

**Expected behavior**
The video should start from the beginning when reaching the end.

**Technical Details:**
 - Device: Android, Web
 - OS: Android 11, Google Chrome
 - Version: 2.2.2

**Comment by sarbagyastha** [comment]
Fixed with v3.

**Comment by terence-codigo** [comment]
hi @sarbagyastha this will be in 3.1.0? I'm experiencing this for 3.0.4.
