### ISSUE TITLE
[BUG] Does not support Youtube Short Link

### ISSUE THREAD

**Issue by satrio1256** [sarbagyastha/youtube_player_flutter#616]
**Describe the bug**

**To Reproduce**
1. Open Web Demo
2. Paste this youtube short link to playlist ID `https://youtube.com/shorts/ouPedYhrKss?feature=share`
3. Click load
4. Youtube Short will show as not found

**Expected behavior**
Youtube Short Play as Expected `OR` Youtube Short will play as regular video

**Screenshots**

**Technical Details:**
 - Device: All Dvices
 - OS: All OS
 - Version: All Version

**Additional context**
It seems that youtube is using following format for YouTube Shorts: `https://youtube.com/shorts/{video_id}?feature=share`. Improvement in convertToId method may be required 🤔

**Comment by jmw1493** [comment]
The URL will work if you replace "/shorts/" with "/watch?v="

**Comment by sarbagyastha** [comment]
The support has been added with v3.
