### ISSUE TITLE
YouTube Music

### ISSUE THREAD

**Issue by sunilguptasg** [sarbagyastha/youtube_player_flutter#623]
**Is your feature request related to a problem? Please describe.**
I need a way to just play the music. The https://pub.dev/packages/youtube_explode_dart does not work on the web. 

**Describe the solution you'd like**
A way to select the music quality from the available chennels and play only the music via any available music player

**Describe alternatives you've considered**
Other than https://pub.dev/packages/youtube_explode_dart, none. It also appears that https://pub.dev/packages/youtube_explode_dart might be using unofficial API access.

**Additional context**
none

**Comment by sarbagyastha** [comment]
There are no official APIs for YouTube music yet.
