### ISSUE TITLE
[BUG] example project doesnt compile on android

### ISSUE THREAD

**Issue by syonip** [sarbagyastha/youtube_player_flutter#626]
**Describe the bug**
Can't run example project on android.

**To Reproduce**
Run example project on android.

**Expected behavior**
Project runs.

**Screenshots**

**Technical Details:**
 - Device: Any android
 - OS: Windows 11
 - Flutter version: 2.10.3

**Additional context**
Getting compilation error:

```
Build failed due to use of deprecated Android v1 embedding.
```

**Comment by ps6067966** [comment]
is it possible to prefetch this youtube video before using it?

**Comment by sarbagyastha** [comment]
`youtube_player_flutter: ^8.1.0` & `youtube_player_iframe: ^2.3.0` are available now.
