### ISSUE TITLE
Load new Video without auto playing

### ISSUE THREAD

**Issue by singh-karan-7** [sarbagyastha/youtube_player_flutter#630]
Is there a way to load a new video without automatically playing it?
We can use `controller.load()` to load a new video, but, it also starts playing the video. I don’t want. I can use `controller.pause()` after loading it, but the issue with that is then player doesn’t show the latest thumbnail. Also, it takes a while to load a new video. Is tgere a way to show the loder on to the player itself until it loads new video?
Thanks!!!

**Comment by JDNew** [comment]
Same problem.

**Comment by sarbagyastha** [comment]
You can use the `cue` method.
