### ISSUE TITLE
[BUG] Youtube player accepts tap inputs even when the YouTube video is covered by another widget

### ISSUE THREAD

**Issue by mark8044** [sarbagyastha/youtube_player_flutter#631]
I have a YouTube video sitting in a container widget in the middle of the screen, but I have a series of overlays that can be presented on screen, for example to login or enter a comment.  These overlays are presented on screen with various methods, for example I like to use Modal Bottom Sheet https://pub.dev/packages/modal_bottom_sheet

As mentioned these overlays will cover the YouTube video, to the point they are no longer seen

However if you click on the overlay or new modal screen in the area where the YouTube video sits, the video will receive those clicks and start playing, or open the settings screen etc...

**Comment by sunilguptasg** [comment]
Hi, this is NOT a bug. Any iframe component has this behaviour - connected to web security. See https://stackoverflow.com/questions/62451268/how-to-prevent-flutter-web-htmlelementview-from-catching-touches-from-objects-ab/71487978#71487978 - where I have also proposed a solution which I am using (DropzoneView)

**Comment by sarbagyastha** [comment]
You can try using this library: https://pub.dev/packages/pointer_interceptor

**Comment by carman247** [comment]
> You can try using this library: https://pub.dev/packages/pointer_interceptor

Doesn't work ...

Would be fantastic to have this functionality though

**Comment by sunilguptasg** [comment]
I place an empty div with the same size before the flutter widget renders (use a 100ms delay). Let me know if you need the code & technique - works for me in all situations on the web
