### ISSUE TITLE
Support parsing URLs instead of hard requirement of video ID

### ISSUE THREAD

**Issue by UNIcodeX** [sarbagyastha/youtube_player_flutter#632]
**Is your feature request related to a problem? Please describe.**
It would be convenient to be able to pass in a Channel URL and youtube_player_flutter automatically parse the playlist and add the videos to the app-side playlist.

**Describe the solution you'd like**
supply a channel and / or playlist URL and videos play from that channel or playlist.

**Describe alternatives you've considered**
I've tried parsing the data using the flutter exploded and metadata packages. I am currently unaware of how to parse the first video ID for a youtube playlist and / or channel.

**Comment by sarbagyastha** [comment]
The new `loadPlalist` method can be used, added in v3.
