### ISSUE TITLE
[BUG] Do not want to play the initial loaded video

### ISSUE THREAD

**Issue by sunilguptasg** [sarbagyastha/youtube_player_flutter#633]
**Describe the bug**
(on web)

I initialize YouTubePlayerController with an initialVideoId in initState, so that I have a YoutubePlayerControllerProvider at the top of my widget tree - but I do not display the YoutubePlayerIFrame, till such time as the user pastes a youtube video link, which i set with 'load' and then display the YoutubePlayerIFrame. The initialVideoId plays. If I paste the link again and "load" only then the new video plays. I do not want the initialVideoId to play, ever.

**To Reproduce**
@override
  void initState() {
    super.initState();

    youTubeController = YoutubePlayerController(
      initialVideoId: YoutubePlayerController.convertUrlToId('https://youtu.be/r_DN7Ky_CUg')!, << some real url
      params: const YoutubePlayerParams(
        showFullscreenButton: true,
        enableCaption: false,
        privacyEnhanced: true,
        strictRelatedVideos: true,
      ),
    );
  }

  @override
  void dispose() {
    youTubeController.close();
    super.dispose();
  }

@override
  Widget build(BuildContext context) {
    return YoutubePlayerControllerProvider(
      controller: youTubeController,
      child: <... here there is a condition that inserts YoutubePlayerIFrame from the following method>

method code:

isYouTube = RegExp(Constants.youTubeRegex).hasMatch(videoFileUrl) && YoutubePlayerController.convertUrlToId(videoFileUrl) != null;
      if (isYouTube) {
        youTubeController.load(YoutubePlayerController.convertUrlToId(videoFileUrl)!);
        return const YoutubePlayerIFrame();
      } else {
        <returns iFrame that plays the browsers interval video player >
     }

**Expected behavior**
The loaded file should play - not the initialVideoId

**Screenshots**

**Technical Details:**
 - Device: web (Chrome, Edge)
 - OS: Win 10

**Additional context**

**Comment by sarbagyastha** [comment]
Fixed by v3.
