### ISSUE TITLE
[BUG] Change needed in regex 

### ISSUE THREAD

**Issue by sunilguptasg** [sarbagyastha/youtube_player_flutter#634]
**Describe the bug**
New URL's like https://www.youtube.com/shorts/K7kO0zUeVUk do not work

**To Reproduce**
Check the convertUrlToId method with that url

**Expected behavior**
Suggest use the regex at https://regex101.com/r/7CxmJP/8 with a mod to add 'shorts/' (this page as >60 url formats that are identified)

**Additional context**
String? checkReturnYouTubeId(String url) {
  final exp = RegExp(
    r'(?:http:|https:)*?\/\/(?:www\.|)(?:youtube\.com|m\.youtube\.com|youtu\.|youtube-nocookie\.com).*(?:v=|v%3D|v\/|(?:a|p)\/(?:a|u)\/\d.*\/|watch\?|shorts\/|vi(?:=|\/)|\/embed\/|oembed\?|be\/|e\/)([^&?%#\/\n]*)',
    multiLine: true,
    caseSensitive: false,
  );

  final Match? match = exp.firstMatch(url);
  if (match != null && match.groupCount >= 1) return match.group(1);
  return null;
}

I use the above to check if a user pasted link is a youtube link as well as return the Id.

**Comment by sarbagyastha** [comment]
This has been added in v3.
