### ISSUE TITLE
[BUG] Fullscreen immediately exits in example

### ISSUE THREAD

**Issue by derekantrican** [sarbagyastha/youtube_player_flutter#637]
**Describe the bug**
Fullscreen immediately exits in example

**To Reproduce**
Clone the code, run the example, play the video, click fullscreen button

**Expected behavior**
Fullscreen should not immediately exit

**Screenshots**
Screen recording: https://user-images.githubusercontent.com/1558019/165871698-06a0be65-ec1d-4375-bb98-04d26b468387.mp4

**Technical Details:**
 - Device: Pixel 3
 - OS: Android 11

**Comment by praveenb** [comment]
me too same issue. Please let us know, Any solution for it.

Thanks

**Comment by davey06** [comment]
add this line under `YoutubePlayerBuilder`
```dart
     onEnterFullScreen: () {
        SystemChrome.setPreferredOrientations([
          DeviceOrientation.landscapeLeft,
          DeviceOrientation.landscapeRight,
        ]);
      },
```
