### ISSUE TITLE
Lots of warnings after latest Flutter upgrade

### ISSUE THREAD

**Issue by brent777** [sarbagyastha/youtube_player_flutter#644]
Hi,

I just upgraded flutter and when building my app now, your library produces a lot of warnings:

../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-8.0.0/lib/src/widgets/youtube_player_builder.dart:40:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
                   ^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-8.0.0/lib/src/widgets/youtube_player_builder.dart:45:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(this);
                   ^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-8.0.0/lib/src/widgets/youtube_player_builder.dart:51:43: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    final physicalSize = SchedulerBinding.instance?.window.physicalSize;
                                          ^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-8.0.0/lib/src/player/raw_youtube_player.dart:43:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
                   ^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-8.0.0/lib/src/player/raw_youtube_player.dart:48:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(this);

**Comment by mark8044** [comment]
Looks like this package may no longer be supported :(

**Comment by brent777** [comment]
> Looks like this package may no longer be supported :(

Oh dear, guess I will have to make my own fork then and update it, unless you know of a currently maintained fork that someone else has already made?

**Comment by brent777** [comment]
Thanks so much, will test it shortly.
