### ISSUE TITLE
please release new update of this package

### ISSUE THREAD

**Issue by faisalmushtaq007** [sarbagyastha/youtube_player_flutter#646]

**Comment by JoshRice1** [comment]
@sarbagyastha Are you going to maintain this package or can it be forked and a different package be built from it?

**Comment by sarbagyastha** [comment]
`youtube_player_flutter: ^8.1.0` & `youtube_player_iframe: ^2.3.0` are available now. 

@JoshRice1 I'll be maintaining the package.

**Comment by JoshRice1** [comment]
@sarbagyastha Thanks just wanted to make sure as there was a long gap between updates and quite a few outstanding pull requests.

Thanks
