### ISSUE TITLE
[BUG] takeScreenshot returns black image on IOS real device

### ISSUE THREAD

**Issue by fLySpin** [sarbagyastha/youtube_player_flutter#651]
Hello, guys!

takeScreenshot method works good on ios simulator  (background - youtube_player_flutter, top left corner - screenshot)
but on real ios device  it returns black screen
`
late YoutubePlayerController _controller;
 ...
var data = await _controller.value.webViewController?.takeScreenshot();
`

IOS Simulator
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-05-13 at 00 53 13](https://user-images.githubusercontent.com/66147358/169523295-b6f0759e-b095-40fc-aef8-18171bd92ccd.png)
Real ipad mini
![IMG_0141](https://user-images.githubusercontent.com/66147358/169523307-b5aaf725-a58c-4fa9-a5f8-a1b8fb097fd5.PNG)

To Reproduce:
`import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }
  runApp(MaterialApp(home: Screen_YoutubePlayer()));
}

class Screen_YoutubePlayer extends StatefulWidget {
  Screen_YoutubePlayer({Key? key}) : super(key: key);

  @override
  State<Screen_YoutubePlayer> createState() => _Screen_YoutubePlayerState();
}

class _Screen_YoutubePlayerState extends State<Screen_YoutubePlayer> {
  late YoutubePlayerController _controller;
  bool _isPlayerReady = false;
  Timer? _timer;
  late YoutubePlayer _palyer;
  Widget _screenshot = Container(
    width: 400,
    height: 400,
    color: Colors.amber,
  );

  @override
  void initState() {
    super.initState();
    _controller = YoutubePlayerController(
      initialVideoId: '8g18jFHCLXk',
      flags: YoutubePlayerFlags(
          autoPlay: true, mute: true, hideControls: false, enableCaption: false, loop: true),
    );
  }

  _attachScreenshotMaker() {
    if (_isPlayerReady) return;

    int fps = 1;
    var conf = ScreenshotConfiguration(compressFormat: CompressFormat.PNG);
    _timer = Timer.periodic(Duration(milliseconds: (1000 / fps).toInt()), (Timer t) {
      var tick = t.tick;
      Future.delayed(Duration.zero, () async {
        var data = await _controller.value.webViewController?.takeScreenshot();

        if (data != null) {
          setState(() {
            _screenshot = Container(width: 400, height: 400, child: Image.memory(data));
          });
        }
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    _palyer = YoutubePlayer(
      aspectRatio: 16 / 9,
      controller: _controller,
      liveUIColor: Colors.amber,
      onReady: () {
        Future.delayed(Duration(seconds: 4), () {
          _attachScreenshotMaker();
          _isPlayerReady = true;
        });
      },
    );

    return Stack(
      children: [_palyer, _screenshot],
    );
  }

  @override
  void dispose() {
    _timer?.cancel();
    _controller.dispose();
  }
}`

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-BY)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

Device: ipad mini MYL92RK/A
OS: ios 15.4.1

youtube_player_flutter 8.0.0

**Comment by sarbagyastha** [comment]
SInce the webview implementation, takeScreenshot function is no longer supported.
