### ISSUE TITLE
[BUG] MaterialPageRoute of Flutter 3 with --enable-software-rendering

### ISSUE THREAD

**Issue by LeandroMoura3** [sarbagyastha/youtube_player_flutter#652]
Hello,

I changed the Flutter to version 3 and I use --enable-software-rendering for no one good reason. When I push a new page in a page that have a Iframe youtube vídeo, this vídeo stay in screen, but only the visual. When I not use the flag, then this bug don't happens.

So I just will not use the flag, but I hope helped with this report.

**Comment by sarbagyastha** [comment]
Thanks for the report, the webview implementation had been changed, so it should fix the issue.
