### ISSUE TITLE
[BUG] Video stops playing on iOS when it leaves the field of view (lack of consistency with Android)

### ISSUE THREAD

**Issue by mark8044** [sarbagyastha/youtube_player_flutter#653]
I have placed the YouTube widget inside a scrollable `Column` and it plays inline with text very well.

On android, if you play the video and scroll the content and the video scrolls off the screen, it will continue to play with the audio in the background, even though the video can't be seen (as it was scrolled off screen).  

On iOS, the behavior is different, the moment it is no longer visible on the screen, the video will stop.  If the video is scrolled back into the screen, it is paused at the time when the widget was scrolled off the screen, so I don't think its an issue of the widget rebuilding, but some difference in the framework between iOS and Android implementations

**Comment by sarbagyastha** [comment]
Seems like the issue is related to how platform view are created in Flutter. Can do nothing.

**Comment by A7mdFathi** [comment]
Hi, I had the same issue and try many solutions but not work.
Does anyone solve this issue? @sarbagyastha  @mark8044
