### ISSUE TITLE
[BUG] [iFrame package] how to start the player in Fullscreen mode instead of invoking it using a user gesture

### ISSUE THREAD

**Issue by jaskiratAtNexG** [sarbagyastha/youtube_player_flutter#656]
hi,
I found a way to invoke fullscreen mode programatically on a user gesture which is by using invokeJavasript callback ike this:
_controller.invokeJavascript('document.body.requestFullscreen()');

but this works only for user provided gestures. if use the above code in initstate to toggle to fullscreen i get below typerror:
Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
[log] Uncaught (in promise) TypeError: fullscreen error.

So is there any solution for this?

**Comment by sarbagyastha** [comment]
`controller.enterFullScreen()` method has been added.
