### ISSUE TITLE
[BUG] Flutter Web - Autoplay Not Working

### ISSUE THREAD

**Issue by sknew93** [sarbagyastha/youtube_player_flutter#664]
**Describe the bug**

The player displays perfectly and all the button works.
But the autoplay does not work.
Tried controller.play & controller.load.
No Luck,

**To Reproduce**

**Expected behavior**
The video should play as soon as the dialog opens and the player is visible.

**Code Snippet**
`YoutubePlayerController controller = YoutubePlayerController(
                                                    initialVideoId: youtubeId,
                                                    params: YoutubePlayerParams(
                                                        playlist: playlistLinkList, // Defining custom playlist
                                                        showControls: true,
                                                        enableCaption: false,
                                                        showVideoAnnotations: false,
                                                        loop: true,
                                                        showFullscreenButton: false,
                                                        enableJavaScript: true),
                                                  );
                                                  showDialog(
                                                      context: context,
                                                      builder: (context) => Dialog(
                                                            insetPadding: EdgeInsets.symmetric(
                                                              vertical: MediaQuery.of(context).size.height * 0.15,
                                                            ),
                                                            clipBehavior: Clip.hardEdge,
                                                            child: MouseRegion(
                                                              onEnter: (event) {
                                                                if (mounted && !controller.value.hasPlayed) {
                                                                  print('here');
                                                                  setState(() {
                                                                    controller.load(controller.initialVideoId);
                                                                  });
                                                                }
                                                              },
                                                              child: YoutubePlayerControllerProvider(
                                                                // Provides controller to all the widget below it.
                                                                controller: controller,
                                                                child: YoutubePlayerIFrame(
                                                                  aspectRatio: 16 / 9,
                                                                ),
                                                              ),
                                                            ),
                                                          ));
                                                },`

**Technical Details:**
 - Chrome and Edge Browsers

**Additional context**

**Comment by orange-day** [comment]
player_fragments.dart

replace 
```
return '<iframe id="player" type="text/html"'
' style="position:absolute; top:0px; left:0px; bottom:0px; right:10px;'
' width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;"'
' src="$sourceUri" frameborder="0" allowfullscreen></iframe>';
```

with
`return '<div id="player"></div>';`
