### ISSUE TITLE
[FEATURE REQUEST] Please allow to add "modestbranding" parameter

### ISSUE THREAD

**Issue by tuvia** [sarbagyastha/youtube_player_flutter#668]
I'd like to ask for the possibility to add the modestbranding parameter to the JavaScript Youtube player. This would allow to hide the Youtube link on the player.

It's quite simple to implement: in the files 
[youtube_player_mobile.dart](https://github.com/sarbagyastha/youtube_player_flutter/blob/master/packages/youtube_player_iframe/lib/src/players/youtube_player_mobile.dart)
and
[youtube_player_mobile.dart](https://github.com/sarbagyastha/youtube_player_flutter/blob/master/packages/youtube_player_iframe/lib/src/players/youtube_player_mobile.dart)

Both on the [youtube_player_iframe](https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_iframe) library (for this to work on iOS)

This code is the original,
```
function onYouTubeIframeAPIReady() {
                player = new YT.Player('player', {
                    events: {
                        onReady: function(event) { window.flutter_inappwebview.callHandler('Ready'); },
                        onStateChange: function(event) { sendPlayerStateChange(event.data); },
                        onPlaybackQualityChange: function(event) { window.flutter_inappwebview.callHandler('PlaybackQualityChange', event.data); },
                        onPlaybackRateChange: function(event) { window.flutter_inappwebview.callHandler('PlaybackRateChange', event.data); },
                        onError: function(error) { window.flutter_inappwebview.callHandler('Errors', error.data); }
                    },
                });
            }

```

I propose the following code:

```
function onYouTubeIframeAPIReady() {
                player = new YT.Player('player', {
                    
modestbranding: 1,
                    
events: {
                        onReady: function(event) { window.flutter_inappwebview.callHandler('Ready'); },
                        onStateChange: function(event) { sendPlayerStateChange(event.data); },
                        onPlaybackQualityChange: function(event) { window.flutter_inappwebview.callHandler('PlaybackQualityChange', event.data); },
                        onPlaybackRateChange: function(event) { window.flutter_inappwebview.callHandler('PlaybackRateChange', event.data); },
                        onError: function(error) { window.flutter_inappwebview.callHandler('Errors', error.data); }
                    },
                });
            }

```

Or at least a chance to set it as wished by the user, just as other parameters.
Thank you!

**Comment by sarbagyastha** [comment]
modestbranding is set to true by default. But I don't think the param is respected anymore by Youtube Iframe Player API these days.

**Comment by adrianofreires** [comment]
I would also like to implement it in my app, I notice that when people click on the "YouTube" symbol it ends up opening a YouTube window on top and the user can no longer leave the app.

If it's not implemented by default, how could I just do it in my code? Thanks!

**Comment by tuvia** [comment]
I ended up forking a different plugin and modifying it. It works perfectly. Doesn't show the YouTube brand...

https://pub.dev/packages/flutter_youtube_view_plus

Enjoy!

**Comment by adrianofreires** [comment]
Thank you so much!
