### ISSUE TITLE
[BUG] inconsistent fullscreen and ad display

### ISSUE THREAD

**Issue by BarryCarlyon** [sarbagyastha/youtube_player_flutter#673]
**Describe the bug**

I suspect this is a change by google/youtube and the library needs to be updated/tweaked to match

Using code that _did_ work fine.
I will have updated other libraries and flutter itself.
But at time of writing I am facing the current issues

- iOS cannot full screen, says "This browser doesn't support full screen"
- iOS yellow ad blocks don't appear on the timeline, ads do not appear
- Android yellow ad blocks do appear on the timeline, ads do not appear
- iOS the controls overlay doesn't stay visible for very long, you tap on the video, controls appear and the instantly disappear
- Being log Spammed with #654 

**To Reproduce**

My current controller is

```
YoutubePlayerController(
      initialVideoId: widget.videoId,
      params: const YoutubePlayerParams(
        autoPlay: false,
        color: 'red',

        showControls: true,
        enableKeyboard: false,
        enableJavaScript: false,
        showFullscreenButton: true,
        showVideoAnnotations: false,
        loop: false,

        strictRelatedVideos: true,
        playsInline: false,

        desktopMode: true,
        useHybridComposition: false,

        privacyEnhanced: false,
      )
    );
    _controller.onEnterFullscreen = () {
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.landscapeLeft,
        DeviceOrientation.landscapeRight,
      ]);
    };
```

I've tried a few various on the flags between hybrid, desktop and privacyEnhanced to no avail

and later in `build`

```
            const player = YoutubePlayerIFrame();

            return YoutubePlayerControllerProvider(
              controller: _controller,
              child: Padding(
                padding: const EdgeInsets.fromLTRB(10.0, 50.0, 10.0, 10.0),
                child: Column(
                  children: [
                    player,

~SNIP~
```

**Expected behavior**

- FullScreen to consistently work on android and iOS
- Ads to consistenty work on android and iOS

**Technical Details:**
 - Device: Various
 - OS: Android 10+ / iOS 15+
 - Version tried 2.2.2, 2.3.0 and the current 3 beta

**Comment by sarbagyastha** [comment]
Fullscreen issue has been fixed with v3.
