### ISSUE TITLE
[3.0.2] Full screen button on iOS no longer working

### ISSUE THREAD

**Issue by mark8044** [sarbagyastha/youtube_player_flutter#676]
Tapping on the bottom right full screen button previously worked on iOS, but now pressing on it brings up an options menu (Account, loop, copy video url, copy video url at current time, copy embed code)

**Comment by sarbagyastha** [comment]
Thanks for reporting. Will look into the issue.

**Comment by mark8044** [comment]
As an update, it also doesn't work at all on Android (nothing happens when you tap)

**Comment by sarbagyastha** [comment]
Can you please try [v3.0.3](https://pub.dev/packages/youtube_player_iframe/changelog#303)?

**Comment by mark8044** [comment]
> Can you please try with [v3.0.3](https://pub.dev/packages/youtube_player_iframe/changelog#303)?

Unfortunately this now creates a new error where videos won't load at all (both iOS and Android).

"An error occurred.  Please try again later ..."

**Comment by sarbagyastha** [comment]
Can you please provide the videoId ?

**Comment by mark8044** [comment]
> Can you please provide the videoId ?
> You can try it here too: https://sarbagyastha.com.np/youtube_player_flutter/#/

Hi, any video has the error, but it works fine (except for full screen) with 3.0.2.  No other change was made

**Comment by sarbagyastha** [comment]
Can you try with example app ?

**Comment by mark8044** [comment]
> Can you try with example app ?

Ok I just looked at the app and I see this `YoutubePlayerScaffold` which goes above the Scaffold.  Maybe this is a source of the problem?

I cannot do such an implementation because My scaffold actually has a listview, with multiple videos that are listed in the listview, so each scaffold has multiple concurrent videos within it.  

Furthermore the Scaffold is setup and the listview contents (including videos) is pulled via REST API from a remote source  after the Scaffold and page is displayed.  So I moved the `YoutubePlayerScaffold` into my StatefulWidget

Not that Im sure this has to do with the `YoutubePlayerScaffold` or not.   I can say with my current implementation, when I click on the standard error it will take me to YouTube.com (within an iFrame I presume) and from there I can actually play any random video just fine.

My current implementation:

```
class _U2bWidgetState extends State<_U2bWidget> {

  YoutubePlayerController controller = YoutubePlayerController(
    params: const YoutubePlayerParams(
        showControls: true,
        showFullscreenButton: true,
        enableJavaScript: false
    ),
  );

  @override
  initState()
  {
    super.initState();
    controller.cueVideoById(videoId: widget.videoId);
  }

  @override
  dispose()
  {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return YoutubePlayerScaffold(
      controller: controller,
      aspectRatio: 16 / 9,
      builder: (context, player) {
        return player;
      },
    );

  }
}
```

**Comment by mark8044** [comment]
Still not working with 3.0.4, either on iOS or Android, either with playback ID that has a dash or no dash

**Comment by mark8044** [comment]
Ok I have updated my code like this and it now works, however, the full screen button on iOS will not launch into full screen, it will rather rotate the device into landscape mode but not display full screen.  Maybe it is because of the Scaffold?

```

    _controller = YoutubePlayerController(
      params: const YoutubePlayerParams(
        showControls: true,
        //mute: false,
        showFullscreenButton: true,
        //loop: false,
        enableJavaScript: false,
      ),
    )
      ..onInit = () {
      _controller.cueVideoById(videoId:  widget.videoId);
        // _controller.loadPlaylist(
        //   list: [
        //     'tcodrIK2P_I',
        //     'nPt8bK2gbaU',
        //     'K18cpp_-gP8',
        //     'iLnmTe5Q2Qw',
        //     '_WoCV4c6XOE',
        //     'KmzdUe0RSJo',
        //     '6jZDSSZZxjQ',
        //     'p2lYr3vM_1w',
        //     '7QUtEmBT_-w',
        //     '34_PXCzGw1M',
        //   ],
        //   listType: ListType.playlist,
        //   startSeconds: 136,
        // );
      }
      ..onFullscreenChange = (isFullScreen) {
        debugPrint('${isFullScreen ? 'Entered' : 'Exited'} Fullscreen.');
      };
```

**Comment by sarbagyastha** [comment]
I've added a video list page to demonstrate how the player can be used without scaffold. You can take a look at the example app's code.
