### ISSUE TITLE
isReady is missing from YoutubePlayerController and YoutubePlayerValue [FEATURE REQUEST]

### ISSUE THREAD

**Issue by inc16sec** [sarbagyastha/youtube_player_flutter#679]
Looks like isReady is missing from `YoutubePlayerController` and `YoutubePlayerValue` and there's no way to access it from the `YoutubeValueBuilder`. So far it only exists in `YoutubePlayerEventHandler`.

Was this intentional or just a minor mistake?

**Comment by sarbagyastha** [comment]
It was intentional. The ready status is checked internally by all the API, so it should not be needed.

**Comment by inc16sec** [comment]
LGTM.
