### ISSUE TITLE
[BUG] Get current position in youtube_player_iframe

### ISSUE THREAD

**Issue by olegsvs** [sarbagyastha/youtube_player_flutter#683]
**Describe the bug**
Can you provide method for get current position? Used 3.0.3 version.
Also loop flag not working for one video.

**Comment by jtkeyva** [comment]
same, not able to get position using

_controller.value.position

or

 _controller.distinct().listen((event) {
      position = event.position;
    });

**Comment by sarbagyastha** [comment]
Added `getCurrentPositionStream()` with v3.0.4
