### ISSUE TITLE
HTMLVideoElement.webkitExitFullscreen() is deprecated

### ISSUE THREAD

**Issue by pedromassango** [sarbagyastha/youtube_player_flutter#69]
I'm receiving this log when the video ends:

`
[INFO:CONSOLE(1197)] "'HTMLVideoElement.webkitExitFullscreen()' is deprecated. Please use 'Document.exitFullscreen()' instead.", source: https://www.youtube.com/yts/jsbin/player_ias-vflBmg71L/en_US/base.js (1197)
`

**Comment by sarbagyastha** [comment]
I think it is Youtube Iframe Player's issue. Can do nothing i guess.
