### ISSUE TITLE
[BUG]: Related videos not working in v3 

### ISSUE THREAD

**Issue by rohansohonee** [sarbagyastha/youtube_player_flutter#690]
**Describe the bug**
Using the param `strictRelatedVideos`: true in v3 does not show the same video from channel after the initial video has finished. It is showing videos from other channels.

**Expected behavior**
Videos should be from same video channel when using `strictRelatedVideos`: true.

**Additional context**
Tested on Android and web.

In v2 it is working correctly.

**Comment by peacemaker123456** [comment]
same issue here...

**Comment by ChisatoMatsuzaki** [comment]
Hi, 

**This could be the reason:**
‘ ! ’ was removed when migrating from v2 to v3.

v2 : `'rel': _boolean(!controller.params.strictRelatedVideos),`
[https://github.com/sarbagyastha/youtube_player_flutter/blob/fd7bf74bbe0b4f7bf2c977[…]ges/youtube_player_iframe/lib/src/helpers/player_fragments.dart](https://github.com/sarbagyastha/youtube_player_flutter/blob/fd7bf74bbe0b4f7bf2c977328f5a222a8865a6cf/packages/youtube_player_iframe/lib/src/helpers/player_fragments.dart#L12)

v3 : `'rel': _boolean(strictRelatedVideos),`
[https://github.com/sarbagyastha/youtube_player_flutter/blob/a3b99268b53e239c521465[…]8b233/packages/youtube_player_iframe/lib/src/player_params.dart](https://github.com/sarbagyastha/youtube_player_flutter/blob/a3b99268b53e239c52146501251565871c28b233/packages/youtube_player_iframe/lib/src/player_params.dart#L167)

**Comment by sarbagyastha** [comment]
Thanks to @ChisatoMatsuzaki , the fix has been merged.
