### ISSUE TITLE
[BUG] _controller.listen don't trigger when update to v3

### ISSUE THREAD

**Issue by bigzhu** [sarbagyastha/youtube_player_flutter#699]
**Describe the bug**
Need kown _controller.currentTime when playing video.
The v2 can use _controller.listen function to trigger update play to which seconds,
But update to V3 just play or pause will trigger _controller.listen once,

I can't get play seconds immediately when playing video

**Comment by sarbagyastha** [comment]
You can use the stream.
https://pub.dev/documentation/youtube_player_iframe/latest/youtube_player_iframe/YoutubePlayerController/getCurrentPositionStream.html
