### ISSUE TITLE
Support for setlooping

### ISSUE THREAD

**Issue by JamalBelilet** [sarbagyastha/youtube_player_flutter#7]
Is there any way to implement setlooping(true) with this plugin, if not detecting VideoEnd event may allow that by replaying it.

**Comment by sarbagyastha** [comment]
@JamalBelilet , With next update I am planning to add setloop and playlist related features. Currently, you can listen to video end and seek to start to achieve the similar.

**Comment by JamalBelilet** [comment]
Thank you @sarbagyastha, I implement it like this:
`listener = () {
      if (this.mounted) {
        setState(() {});
        if (_controller.value.playerState == youtube_player.PlayerState.ENDED) {
          _controller.play();
        }
      }
    };`

I already implement that playlist feature using Youtube data api, but I'll be waiting for your way.

**Comment by sarbagyastha** [comment]
The feature is added with version 5.
