### ISSUE TITLE
Controller /Listener not working in Fullscreen mode?

### ISSUE THREAD

**Issue by ElixirMike** [sarbagyastha/youtube_player_flutter#70]
I'm using the controller /listener to control when a video ends based on timing. In the listener, it checks the duration and if exceeds specified time, pauses video. This works fine in normal mode. However, when I click to fullscreen, the controller/listener no longer work .

Is there a way to continue to listen/react in listener when video is in fullscreen mode?

**Comment by sarbagyastha** [comment]
Thank you for reporting issue. Will look into the issue soon.

**Comment by sarbagyastha** [comment]
Fixed with version 5.1.0
