### ISSUE TITLE
[BUG] Fullscreen mode ends up causing an overflowed pixels error

### ISSUE THREAD

**Issue by adrianofreires** [sarbagyastha/youtube_player_flutter#702]
**Describe the bug**
When I press the fullscreen button the video doesn't fit on the screen, I noticed that this happens both with the youtube_player_iframe: ^3.0.4 package and with the youtube_player_flutter: ^8.1.0 package. Am I doing something wrong? I followed the way it is in the documentation. In the gif below I'm using the youtube_player_iframe: ^3.0.4, here's the code:

**To Reproduce**

` 
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';

import '../blocs/blocs.dart';
import '../config/config.dart';
import '../models/models.dart';
import '../services/services.dart';
import '../widgets/widgets.dart';

class VideoArticleDetails extends StatefulWidget {
  final Article article;
  const VideoArticleDetails({Key? key, required this.article}) : super(key: key);

  @override
  _VideoArticleDetailsState createState() => _VideoArticleDetailsState();
}

class _VideoArticleDetailsState extends State<VideoArticleDetails> {
  double _rightPaddingValue = 100;
  var scaffoldKey = GlobalKey<ScaffoldState>();

  Future _handleShare() async {
    Share.share(widget.article.link!);
  }

  @override
  void initState() {
    super.initState();
    Future.delayed(const Duration(milliseconds: 0)).then((value) => context.read<AdsBloc>().showLoadedAds());
    Future.delayed(const Duration(milliseconds: 100)).then((value) => setState(() {
          _rightPaddingValue = 10;
        }));
  }

  @override
  Widget build(BuildContext context) {
    final bookmarkedList = Hive.box(Constants.bookmarkTag);
    return Scaffold(
      backgroundColor: Theme.of(context).backgroundColor,
      key: scaffoldKey,
      appBar: _appBar(),
      body: SafeArea(
        bottom: true,
        child: Column(
          children: [
            YoutubePlayerWidget(youtubeVideoUrl: widget.article.videoID!),
            Expanded(
              flex: 1,
              child: SingleChildScrollView(
                child: Column(
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Padding(
                          padding: const EdgeInsets.fromLTRB(20, 20, 20, 0),
                          child: Column(
                            children: [
                              Row(
                                children: <Widget>[
                                  Container(
                                    alignment: Alignment.center,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(5),
                                      color: Theme.of(context).colorScheme.onBackground,
                                    ),
                                    child: AnimatedPadding(
                                      duration: const Duration(milliseconds: 500),
                                      padding: EdgeInsets.only(left: _rightPaddingValue, right: _rightPaddingValue, top: 5, bottom: 5),
                                      child: Text(
                                        widget.article.category!,
                                        style: TextStyle(fontSize: 15, color: Theme.of(context).colorScheme.primary, fontWeight: FontWeight.w600),
                                      ),
                                    ),
                                  ),
                                  const Spacer(),
                                  BookmarkIcon(
                                    bookmarkedList: bookmarkedList,
                                    article: widget.article,
                                    iconSize: 22,
                                    scaffoldKey: scaffoldKey,
                                    iconColor: Colors.blueGrey,
                                    normalIconColor: Colors.grey,
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(
                          height: 15,
                        ),
                        Padding(
                          padding: const EdgeInsets.only(left: 20, bottom: 12),
                          child: Row(
                            children: <Widget>[
                              const SizedBox(
                                width: 5,
                              ),
                              Text(
                                widget.article.timeAgo!,
                                style: TextStyle(
                                  fontSize: 14,
                                  color: Theme.of(context).colorScheme.secondary,
                                ),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(
                          width: 15,
                        ),
                        const SizedBox(
                          width: 10,
                        ),
                        Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: Text(
                            AppService.getNormalText(widget.article.title!),
                            style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, letterSpacing: -0.6, wordSpacing: 1),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: Divider(
                            color: Theme.of(context).primaryColor,
                            endIndent: 280,
                            thickness: 2,
                          ),
                        ),
                        const SizedBox(
                          height: 5,
                        ),
                        HtmlBody(content: widget.article.content!, isVideoEnabled: false, isImageEnabled: true, isIframeVideoEnabled: true),
                        const SizedBox(
                          height: 20,
                        ),
                      ],
                    ),
                    RelatedArticles(postId: widget.article.id, catId: widget.article.catId, scaffoldKey: scaffoldKey),
                    const SizedBox(
                      height: 50,
                    ),
                  ],
                ),
              ),
            ),
            AdsConfig.isAdsEnabled == true ? const BannerAdsWidget() : Container(),
          ],
        ),
      ),
    );
  }

  AppBar _appBar() {
    return AppBar(
      automaticallyImplyLeading: false,
      toolbarHeight: 45,
      leading: IconButton(
        onPressed: () => Navigator.pop(context),
        icon: const Icon(
          Icons.arrow_back_ios_sharp,
          size: 20,
        ),
      ),
      actions: [
        Padding(
          padding: const EdgeInsets.only(right: 6.0),
          child: IconButton(
            onPressed: () => _handleShare(),
            icon: const Icon(
              Icons.share,
              size: 20,
            ),
          ),
        ),
      ],
    );
  }
} 
`

` 
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:youtube_player_iframe/youtube_player_iframe.dart';

class YoutubePlayerWidget extends StatefulWidget {
  final String youtubeVideoUrl;
  const YoutubePlayerWidget({Key? key, required this.youtubeVideoUrl}) : super(key: key);

  @override
  State<YoutubePlayerWidget> createState() => _YoutubePlayerWidgetState();
}

class _YoutubePlayerWidgetState extends State<YoutubePlayerWidget> {
  late YoutubePlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = YoutubePlayerController.fromVideoId(
        videoId: widget.youtubeVideoUrl,
        params: const YoutubePlayerParams(
          mute: true,
          showVideoAnnotations: true,
          showFullscreenButton: true,
          strictRelatedVideos: true,
          color: 'black'
        ));
  }

  @override
  void dispose() {
    _controller.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return
        YoutubePlayerScaffold(
      controller: _controller,
      aspectRatio: 16 / 9,
      builder: ((_, player) => player),
    );
  }
} 
`

**Expected behavior**
When you click the fullscreen button, the full screen should appear

**Screenshots**
__
![fullscreen_issue](https://user-images.githubusercontent.com/38692077/189779258-7e13de6b-aac3-4636-864f-fb909d909016.gif)

**Technical Details:**

Emulador Pixel 4 API 32
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by sarbagyastha** [comment]
You're placing `YoutubePlayerScaffold` inside a  Column. It should be a top-most widget.

**Comment by adrianofreires** [comment]
Thanks man! You're right!
