### ISSUE TITLE
 webview implementation for TargetPlatform.fuchsia but there isn't a default one

### ISSUE THREAD

**Issue by a3on** [sarbagyastha/youtube_player_flutter#71]
Hi,

Thanks again for all the hard work regarding the plugin.

I have successfully added the plugin to my app. But i keep getting the below error and I am unable to play any play the video.

**Unsupported operation: Trying to use the default webview implementation for TargetPlatform.fuchsia but there isn't a default one**

Has anyone seen this before?

**Comment by sarbagyastha** [comment]
Can you mention the platform ? Are you trying to use on Flutter Web ?

**Comment by sarbagyastha** [comment]
Please reopen the issue if the problem still persists

**Comment by j796160836** [comment]
Hi, I faced this issue.
The project have Flutter Desktop included.
I extract into a new project (only iOS & Android) works fine. 
It that cause bug?

**Comment by shrideh** [comment]
the same

**Comment by shrideh** [comment]
who to fix it !

**Comment by rbanonuevo** [comment]
Does anybody fixed this issue?
