### ISSUE TITLE
[BUG] IFrame player does not show up

### ISSUE THREAD

**Issue by keithcwk** [sarbagyastha/youtube_player_flutter#718]
**Describe the bug**
When trying to play a video, the IFrame does not show up, the console shows a syntax error `"Uncaught SyntaxError: Unexpected identifier", source: https://www.youtube.com/ (47)`. This issue seems to be present on the example app as well

**To Reproduce**
Run the example app

**Expected behavior**
Youtube IFrame should show up

**Screenshots**
https://user-images.githubusercontent.com/65481917/194044982-29974fc8-5ec3-4d3c-9b35-0eed3e0b1bf5.mov

**Technical Details:**
 - Device: [Android Emulator SDK 30]
 - OS: [Android 11]

**Comment by sarbagyastha** [comment]
Please make sure that you've made changes locally to the package.
