### ISSUE TITLE
[BUG] Flutter_inappwebview error when compiling

### ISSUE THREAD

**Issue by boszedave** [sarbagyastha/youtube_player_flutter#725]
I'm working on a Flutter module to add a new feature to an existing native Android app. I used this package to display videos and it worked perfectly up until now. It just does not want to compile, always crashes with the following error:

![Képernyőfotó 2022-10-19 - 16 36 05](https://user-images.githubusercontent.com/34679750/196721981-8d2cebd5-7b17-4c15-8dc0-14c511efaa11.png)

Removing this package the Flutter module compiles perfectly. I tried to invalidate caches, pub cache repair etc. none of these worked. I'm using youtube_player_flutter version 8.1.1.

**Comment by iosDevJd** [comment]
I also have the sae issue

**Comment by lahcenaham2020** [comment]
the some problem
The plugin flutter_inappwebview requires Android SDK version 33

**Comment by iosDevJd** [comment]
It is not working even in ios 

> the some problem The plugin flutter_inappwebview requires Android SDK version 33

**Comment by boszedave** [comment]
Updating to the latest Flutter version (3.3.5) the package is working.

**Comment by boszedave** [comment]
The error comes from the flutter_inappwebview package. There is a closed issue which says updating it to the 5.5.0+4 version should fix this error. 
Check out this link: https://github.com/pichillilorenzo/flutter_inappwebview/issues/1380
