### ISSUE TITLE
[BUG] About banned youtube in some countries such as Turkey

### ISSUE THREAD

**Issue by islamoktay** [sarbagyastha/youtube_player_flutter#737]
I am living in Turkey. Sometimes my government ban YouTube at all. Or some videos.
When this happens I cannot catch the Exception.
Please help me with that.

**To Reproduce**
To reproduce it you need to be banned.

**Expected behavior**
I want to catch the error.

**Comment by sarbagyastha** [comment]
Added `onWebResourceError` to controller. Fixed by #754
