### ISSUE TITLE
[BUG]Build failed in iOs

### ISSUE THREAD

**Issue by rmotafacundo** [sarbagyastha/youtube_player_flutter#739]
Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/mult/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1+1/ios/Classes/MyCookieManager.swift:259:43

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/mult/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.1+1/ios/Classes/MyCookieManager.swift:293:43

**Comment by sarbagyastha** [comment]
Duplicate of #731
