### ISSUE TITLE
Anyone had luck getting videos to play on IOS??

### ISSUE THREAD

**Issue by jShampagne1** [sarbagyastha/youtube_player_flutter#74]
I was wondering if anyone has had lucking getting this plugin to work on IOS??

I know it will not work on the simulator, but I still can't get videos to play when I test on a device. This has been a significant pain as the videos will load and look ready to play but won't play.

Any help would be much appreciated!

**Comment by hunglv21** [comment]
The same for me, still not work on IOS?

**Comment by marceloagustini** [comment]
I can't see from IOS device too.

**Comment by sarbagyastha** [comment]
#79
