### ISSUE TITLE
[FEATURE REQUEST] I want to downgrade the quality of the videos

### ISSUE THREAD

**Issue by islamoktay** [sarbagyastha/youtube_player_flutter#759]
I need to downgrade the quality of the videos. I want this because of the network issues. For example, I am showing videos in very short time. But when user have poor network, user waits a lot. I want to show videos asap even if quality of the videos is low.

**Comment by sarbagyastha** [comment]
Sadly, YouTube iFrame API doesn't support changing video quality. But you can play around with `userAgent` param to achieve that.

**Comment by islamoktay** [comment]
thank you for your return

**Comment by Topiya** [comment]
Can you please let me know how to use `userAgent` param to handle quality?
