### ISSUE TITLE
how can i disable only video speed button ?

### ISSUE THREAD

**Issue by Scofielddd** [sarbagyastha/youtube_player_flutter#76]
![image](https://user-images.githubusercontent.com/26333526/66188265-88b84400-e68f-11e9-8fe1-dde242ecfb62.png)

**Comment by sarbagyastha** [comment]
@Scofielddd I'll soon update the plugin which would be more modular. For now you can use the `revamped` branch to achieve the similar.

**Comment by sarbagyastha** [comment]
Fixed with Version 5.
