### ISSUE TITLE
[BUG] startAt is missing

### ISSUE THREAD

**Issue by guyluz11** [sarbagyastha/youtube_player_flutter#802]
**Describe the bug**
It is written in the log that `Deprecated startAt & endAt from YoutubePlayerParams.`

```
3.1.0

Sep 15, 2022

    Fixed issues with example app
    Fixed strictRelatedVideos flag working incorrectly. Thanks to [@ChisatoMatsuzaki](https://github.com/ChisatoMatsuzaki).
    Deprecated startAt & endAt from YoutubePlayerParams.
    Removed volume from YoutubePlayerValue as it's no longer used.
```

So now I just can't start my video at a specific time?, or has this value just moved to another place?.

I think that this is an important and very useful feature that we need to support.

And in case stuff moved or changed names the new name should be mentioned in the changelog and not just the deprecation part.

**Comment by sarbagyastha** [comment]
You can set those duration at load or cue.

https://pub.dev/documentation/youtube_player_iframe/latest/youtube_player_iframe/YoutubePlayerController/loadVideoById.html

**Comment by guyluz11** [comment]
Thanks
