### ISSUE TITLE
For everybody who wants to play inline video on IOS

### ISSUE THREAD

**Issue by romawizard** [sarbagyastha/youtube_player_flutter#81]
I faced with problem when try to play inline video. On IOS native WebView always launch video in full screen. I spend a lot of time to fix this. All you need is to add this line 
  **configuration.allowsInlineMediaPlayback = YES;** in **FlutterWebView.m file.** 
![Снимок экрана 2019-10-09 в 10 34 37 ДП](https://user-images.githubusercontent.com/31043679/66460863-7b7cca00-ea80-11e9-9f9a-dedcd25527f1.png)

**Comment by sarbagyastha** [comment]
Similar to #79 .
