### ISSUE TITLE
[BUG] bottom actions dissapears after exit full screen mode

### ISSUE THREAD

**Issue by anyx** [sarbagyastha/youtube_player_flutter#820]
**Describe the bug**
Looks like this bug https://github.com/sarbagyastha/youtube_player_flutter/issues/135 appears again on android devices in version 8.1.2

**To Reproduce**
Open video in full screen mode and return back. 

**Expected behavior**
Bottom actions are visible after exit from full screen mode.

**Comment by anyx** [comment]
Looks like there is a problem with opacity and state, maybe:  inside _TouchShutterState `_toggleControls` are calling, but `YoutubePlayer` does not rerenders after update _controller. 

So, in fullscreen mode controls  never disappears, after exit in fullscreen mode controls never appears.

Also there is a similar problem with preview image: if before play video open it in fullscreen mode, video will be playing with preview image instead of actual video

**Comment by anyx** [comment]
it was my mistake: `YoutubePlayerController` was initialized inside build method every time.

Sorry, closing it

**Comment by TijnvandenEijnde** [comment]
This post actually helped me, I made the same error, thanks!
