### ISSUE TITLE
[BUG] 'youtube_player_flutter' causes app crash after upgrading to Flutter 3.10.

### ISSUE THREAD

**Issue by Y-ndm** [sarbagyastha/youtube_player_flutter#824]
After upgrading Flutter to 3.10 the app started to crash when navigating to a new page or when exiting a page.

Once the app crashes it throws the error below, which indicates that `webview_flutter` might be what's causing the issue.. After taking off the `youtube_player_flutter` widget the app seems to have no issue.

```dart
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010e591348 Flutter`flutter::IOSExternalViewEmbedder::CompositeEmbeddedView(long long) + 1828
Flutter`flutter::IOSExternalViewEmbedder::CompositeEmbeddedView:
->  0x10e591348 <+1828>: ldr    x8, [x0]
    0x10e59134c <+1832>: ldr    x8, [x8, #0x30]
    0x10e591350 <+1836>: blr    x8
    0x10e591354 <+1840>: cbz    x0, 0x10e591538           ; <+2324>
Target 0: (Runner) stopped.
Lost connection to device.
Exited
```

**Comment by Zubii12** [comment]
Any news?

**Comment by Y-ndm** [comment]
> Any news?

This seems to be a crash caused by BackdropFilter when used with a NativePlatfomView on iOS. You can find more about the issue [here](https://github.com/flutter/flutter/issues/127095).

**Comment by Y-ndm** [comment]
Fixed in the later `stable - 3.10.3` release of Flutter.

**Comment by aytunch** [comment]
@Y-ndm Hi, I see the same abrupt crash with 3.10.5 letest Flutter. Can you confirm and re-open the issue please? It is a blocker

**Comment by Y-ndm** [comment]
> @Y-ndm Hi, I see the same abrupt crash with 3.10.5 latest Flutter. Can you confirm and re-open the issue please? It is a blocker

Yes.. I also started getting the crash.. Also. Are you using `BackdropFilter` widget? It is the one causing the crash when implemented with a WebView.

**Comment by aytunch** [comment]
@Y-ndm yes we use it somewhere in the widget tree. Is there a workaround for now?

**Comment by Y-ndm** [comment]
> @Y-ndm yes we use it somewhere in the widget tree. Is there a workaround for now? Or a Flutter issue to track?

Yes. Keep an eye on this [issue](https://github.com/flutter/flutter/issues/127095).
