### ISSUE TITLE
Please help me edit code of plugin for still buffering video in background mode!

### ISSUE THREAD

**Issue by dtdevpro** [sarbagyastha/youtube_player_flutter#84]
Please guide me edit code of plugin for still buffering video in background mode!
Because I can fix the play video in background and present have issues not buffering video if screen off (only buffering for about 5 minutes).
Sorry my english is bad!

**Comment by SayaGames** [comment]
How to play video in background? (only sound?)

**Comment by dtdevpro** [comment]
Yes, only sound

**Comment by sarbagyastha** [comment]
#65

**Comment by SayaGames** [comment]
I understand. Thank you very much.
