### ISSUE TITLE
[BUG] package:flutter/src/painting/image_stream.dart - ImageStreamCompleter.reportError

### ISSUE THREAD

**Issue by AdelDaniel** [sarbagyastha/youtube_player_flutter#872]
**Describe the bug**

- [Crashlytics]
- bug is: ```package:flutter/src/painting/image_stream.dart - ImageStreamCompleter.reportError```
- keys from Crashlytics: 
```
flutter_error_exception:  
HttpException: Connection closed before full header was received, uri = https://i3.ytimg.com/vi_webp/KdJgiZnYNeg/sddefault.webp

flutter_error_reason:
 thrown HttpException: Connection closed before full header was received, uri = https://i3.ytimg.com/vi_webp/KdJgiZnYNeg/sddefault.webp. Error thrown resolving an image codec.
```
- Logs:
```
Instance of 'DiagnosticsProperty<ImageProvider<Object>>'
Instance of 'DiagnosticsProperty<NetworkImage>'
```
--- 
**To Reproduce**
- navigate between pages that contain Video 

--- 
**Technical Details:**
 - Device: iPhone 12 Pro Max
 - OS:  iosiOS 16.6.1
 - package version: ```youtube_player_flutter: ^8.1.2```

**Comment by mirabo-vuong-nt** [comment]
anyone here?
I got the same error

**Comment by mirabo-vuong-nt** [comment]
But i think it is not bug from package [youtube_player_flutter](https://github.com/sarbagyastha/youtube_player_flutter)
as i see there are something wrong from ImageStreamCompleter. It's come from Flutter framework

**Comment by AdelDaniel** [comment]
Solved it by changing the https://pub.dev/packages/youtube_player_flutter to https://pub.dev/packages/youtube_player_iframe

The issue does not occur in this new package:
- https://pub.dev/packages/youtube_player_iframe
