### ISSUE TITLE
I am not able to launch in IOS , only

### ISSUE THREAD

**Issue by singhBijendraIOS** [sarbagyastha/youtube_player_flutter#88]
I am facing an issue, after adding this dependency in pubspec.yaml,

[VERBOSE-3:FlutterPlatformViews.mm(154)] Check failed: factories_.count(idString) == 0.

And app is crashed in IOS

@Team! can you please help me asap

**Comment by sarbagyastha** [comment]
@singhBijendraIOS Can you please include a full log.

**Comment by sarbagyastha** [comment]
Reopen if the issue persists.

**Comment by keyur158** [comment]
i have same issue @singhBijendraIOS can you please share solution.
