### ISSUE TITLE
Video keeps playing while buffering in fullscreen

### ISSUE THREAD

**Issue by BugsBunnyBR** [sarbagyastha/youtube_player_flutter#89]
Hello there,
When the video is playing and the user moves to full screen, the video keeps playing in background while buffering in the full screen player.
Wouldn't it be a better experience to stop the player in the "non full screen" instance and just start the full screen player in the right position after the buffering is done?

Thanks.

**Comment by sarbagyastha** [comment]
@BugsBunnyBR Can you attach some code snippet so that i can recreate the issue. Is this behaviour present in example too ?
