### ISSUE TITLE
[BUG] Cannot use version 5 of package

### ISSUE THREAD

**Issue by Nirajn2311** [sarbagyastha/youtube_player_flutter#907]
**Describe the bug**
I cannot install v5 of `youtube_player_iframe` package as the minimum flutter version required for that version is 3.18 which is a beta version of flutter and not the latest stable release ie. 3.16 . Is that the intended behaviour?

**Error log**
```
Resolving dependencies... 
The current Flutter SDK version is 3.13.7.

Because <app_name> depends on youtube_player_iframe >=5.0.0 which requires Flutter SDK version >=3.18.0-0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on youtube_player_iframe: flutter pub add youtube_player_iframe:^4.0.4
```

**Comment by mishatron** [comment]
You should upgrade flutter to use the latest version. Currently, we have 3.19 in bets

**Comment by Nirajn2311** [comment]
My understanding regarding new non-beta releases for packages is that they should support the latest stable version instead of beta version. Not every developer is likely to use the beta version as they may tend to break things.

**Comment by sarbagya-acme** [comment]
You can keep using v4 unless you need a wasm support.

**Comment by MarceloRab** [comment]
Waiting for an update Flutter 3.2
