### ISSUE TITLE
Not able to play few youtube videos

### ISSUE THREAD

**Issue by RohithKilaparthi** [sarbagyastha/youtube_player_flutter#91]
Hi

First of all, I really appreciate the effort the team has put in to build the plug in. It has good number of useful features in the recent release. 

But, I have identified an issue with the plugin. It is able to play few videos while it is giving Error Code 150 for few of them. Can you please check and fix this issue?

Video being played : iLnmTe5Q2Qw
Video with error code 150: YFfEFbC9_XQ

**Comment by sarbagyastha** [comment]
Thank you for the appreciation, but i'm a single person, not a team 😉. 

The error code resolves to `The owner of the requested video does not allow it to be played in embedded players.` So, it can't be fixed. 

More info about errors: https://developers.google.com/youtube/iframe_api_reference#onError

**Comment by sarbagyastha** [comment]
Reopen if you have further queries.
