### ISSUE TITLE
Request:  Change "pluginClass" value in  ytView to remove webview clash

### ISSUE THREAD

**Issue by alevinetx** [sarbagyastha/youtube_player_flutter#92]
This follows up from:  https://github.com/sarbagyastha/youtube_player_flutter/issues/11

In your ptview plugin, I believe if you change the value for "pluginClass" from "WebViewFlutterPlugin" to something unique, then we should be able to use your package, and its forked webview, in parallel with the most up-to-date version of WebViewFlutterPlugin itself.

That should save you having to worry about keeping your fork up to date beyond what you need it for.

see:  https://github.com/sarbagyastha/ytview/blob/master/pubspec.yaml
  Line 25

**Comment by sarbagyastha** [comment]
@alevinetx I'm planning to re-swap to webview_flutter. Currently, you may use ytview as it's almost upto date.

**Comment by sarbagyastha** [comment]
Switched to webview_flutter with v5.1.0
