### ISSUE TITLE
Video does not play on an iOS real device [BUG]

### ISSUE THREAD

**Issue by PhanithNoch** [sarbagyastha/youtube_player_flutter#928]
**Describe the bug**
It's working fine on Android Emulator and iOS Simulator, but I face a problem when I run on a real device. IOS version 17.3.1 video is always loading. 

**Screenshots**
[photo_2024-03-27_11-43-27](https://github.com/sarbagyastha/youtube_player_flutter/assets/51220767/aa05033f-a878-41b2-b7a5-2af4254a4824)

**Technical Details:**
 - Device: [e.g. iPhone12 pro Max]
 - OS: [e.g. iOS17.3.1]

**Comment by PhanithNoch** [comment]
The problem is solved by adding flutter_inappwebview.

**Comment by Painwraith** [comment]
I have installed flutter_inappwebview: ^6.0.0. Video not playing (audio is working) on real IOS device.

**Comment by PhanithNoch** [comment]
Any error or warning on console? you can share us

**Comment by Painwraith** [comment]
I have deleted my comment because I spoke too soon. Apologies.

**Comment by stdCMS** [comment]
Infinite Loading Issue with YouTube in iOS WebView

Hello,

I am experiencing an infinite loading issue when trying to load YouTube in an iOS WebView. Below are the logs from my application:

[IOSInAppWebViewWidget] (iOS) IOSInAppWebViewWidget ID 0 calling "onWebViewCreated" using []
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onUpdateVisitedHistory" using {isReload: null, url: https://www.youtube.com/}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "shouldOverrideUrlLoading" using {isForMainFrame: true, hasGesture: null, isRedirect: null, request: {allowsConstrainedNetworkAccess: true, url: https://www.youtube.com/, httpShouldUsePipelining: false, networkServiceType: 0, mainDocumentURL: https://www.youtube.com/, httpShouldHandleCookies: true, allowsExpensiveNetworkAccess: true, timeoutInterval: 2147483647.0, assumesHTTP3Capable: false, allowsCellularAccess: true, body: null, method: GET, attribution: 0, cachePolicy: 0, headers: {User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148, Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8}}, shouldPerformDownload: false, sourceFrame: {isMainFrame: true, securityOrigin: {protocol: , host: , port: 0}, request: {httpShouldUsePipelining: true, method: GET, mainDocumentURL: null, httpShouldHandleCookies: true, networkServiceType: 0, timeoutInterval: 2147483647.0, attribution: ...}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onProgressChanged" using {progress: 0}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onZoomScaleChanged" using {oldScale: 1.0, newScale: 0.43877550959587097}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {newContentSize: {width: 430.0, height: 241.66666666666666}, oldContentSize: {height: 0.0, width: 0.0}}
[IOSInAppWebViewController] (iOS) WebView ID 0 calling "onContentSizeChanged" using {newContentSize: {width: 430.0, height: 241.66666666666666}, oldContentSize: {height: 551.0, width: 980.0}}
Any help or guidance on resolving this issue would be greatly appreciated!

Thank you.

If there's anything else you need to know, please let me know.
