### ISSUE TITLE
Adapts to quality as per the bandwidth

### ISSUE THREAD

**Issue by SayaGames** [sarbagyastha/youtube_player_flutter#94]
Hi, 

Videos do not flow/stream smoothly. Is there anybody have the same problem with me? or any issue with my implementation?
So you expressed " no way to set custom video quality" but I need lower video quality to stream, or else solution

Best regards

**Comment by SayaGames** [comment]
Both real device (debug) and emulator the same result

**Comment by sarbagyastha** [comment]
@SayaGames It's working smoothly for me. Could you describe more about the issue ?

**Comment by sarbagyastha** [comment]
Reopen if the issue persists with Version 5.1.0
