### ISSUE TITLE
Youtube played only sound when videoId changed

### ISSUE THREAD

**Issue by up2code** [sarbagyastha/youtube_player_flutter#99]
Hi, I had try to create video playlist but now it have problem that when videoId had changed and next video is played only sound. I had tested and found this problem happened on version 5.0.0+1 and 5.1.0 but worked fine on version 4.1.0

I would like to try using YoutubePlayerController and use load by video id but from [doc](https://pub.dev/documentation/youtube_player_flutter/latest/youtube_player_flutter/YoutubePlayerController/load.html) and source code it not provided video id parameter.

Test on Android 9 (Physical device)

**Comment by sarbagyastha** [comment]
@up2code will publish a fix today.

**Comment by sarbagyastha** [comment]
Fixed with Version 5.2.0
