### ISSUE TITLE
[BUG] Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'

### ISSUE THREAD

**Issue by RichardRaue** [sarbagyastha/youtube_player_flutter#991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package

youtube_player_flutter

### What happened?

Hi,

you use the /pub.dev/flutter_inappwebview package in your youtube_player_flutter project. 

It seems that there is an issue with iOS 18 and flutter_inappwebview (see here: https://github.com/pichillilorenzo/flutter_inappwebview/issues/2221) So when using your lib (which is great by the way), the app cannot be built for iOS 18 atm.

Just wanted to let you know.

Best,
Richard

### What is the expected behaviour?

code compiles

### How to reproduce?

Start a build for iOS and see for yourself

**Comment by flaviodsilverio** [comment]
I'm having the exact same issue. Any solution is welcome.

**Comment by emmanouilmatsis** [comment]
I'm having the same issue here after upgrading

**Comment by amit-iconflux** [comment]
+1

**Comment by rashidotm** [comment]
it is fixed

https://github.com/andychucs/flutter_inappwebview/pull/2
