### ISSUE TITLE
[BUG] Bump Flutter Inappwebview

### ISSUE THREAD

**Issue by dikynugraha1111** [sarbagyastha/youtube_player_flutter#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package

youtube_player_iframe (Default)

### What happened?

Please bump version of flutter in app webview.
Have an issues in xcode version 16. And its impact with production release

### What is the expected behaviour?

Upgrade version of flutter in app webview

### How to reproduce?

1. Pubspec.yml
2. Update flutter in app webview

**Comment by NoriThorleifs** [comment]
I'm experiencing the same issue. Downgrading youtube_player_flutter to 9.0.1 did not solve the issue. Completely removing youtube_player_flutter from pubspec.yaml and deleting all code that uses it solves the issue.

When attempting to build my app using `flutter run`, I got this error message:
ERROR:C:\Users\arnor\.gradle\caches\transforms-3\4433937d9ff24fc44f711dfc749758bd\transformed\jetified-appcompat-resources-1.7.0-runtime.jar: D8: java.lang.NullPointerException
ERROR:C:\Users\arnor\.gradle\caches\transforms-3\3cce2eb131b2f68efbf751e8b397aa69\transformed\appcompat-1.7.0-runtime.jar: D8: java.lang.NullPointerException

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-resources-1.7.0.aar (androidx.appcompat:appcompat-resources:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\arnor\.gradle\caches\transforms-3\4433937d9ff24fc44f711dfc749758bd\transformed\jetified-appcompat-resources-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform appcompat-1.7.0.aar (androidx.appcompat:appcompat:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\arnor\.gradle\caches\transforms-3\3cce2eb131b2f68efbf751e8b397aa69\transformed\appcompat-1.7.0-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

**Comment by sarbagyastha** [comment]
Published update with the fixes.

**Comment by dikynugraha1111** [comment]
Nice... thank you
